src/adapters/config.ts

chore: disable check guild before creating

---

src/commands/defi/balances.ts
src/commands/defi/token/add.ts
src/commands/defi/token/list.ts
src/commands/defi/token/remove.ts
src/utils/discordEmbed.ts

-   [x] $token add/$token remove -> use select menu

fix: guild token add/remove format

---

.env-sample

fix: rebuild mochi-bot

---

src/utils/user_xp.ts

-   [x] Fix level up message spacing

fix: level up message spacing

---

src/utils/user_xp.ts

-   [x] Change level up message arrow to symbol

fix: level up message arrow to symbol

---

package.json
src/commands/community/stats.ts
src/events/interactionCreate.ts
yarn.lock

fix: ticker and stats - interaction and chart color

---

src/adapters/defi.ts
src/commands/defi/airdrop.ts
src/commands/profile/profile.ts
src/types/defi.ts
src/types/profile.ts

-   [x] Add `transferType` to `tip`, `airdrop` or `withdraw` request payload

feat: add transfer type for defi requests

---

src/events/guildMemberUpdate.ts

-   catch boost event and post to server

feat: xp for boosters

---

src/events/guildMemberUpdate.ts

chore: update send lvlup msg channel

---

src/commands/community/stats.ts

chore: update stats and help stats

---

src/commands/config/reactionRole/add.ts
src/commands/config/reactionRole/remove.ts

-   fix cross channel bot reaction

chore: handle cross channel bot reaction

---

src/adapters/config.ts
src/commands/config/nftRole/index.ts
src/commands/config/nftRole/list.ts
src/commands/config/nftRole/remove.ts
src/commands/index.ts

-   [x] New guild nft role config commands: `$nr`, `$nr list`, `$nr remove`

feat: guild config nft roles commands

---

src/commands/config/reactionRole/add.ts
src/commands/config/reactionRole/remove.ts

-  add some additional validation stuffs for reaction role

chore: add some validation stuffs

---

src/adapters/community.ts
src/commands/community/nft/index.ts
src/commands/community/nft/top.ts
src/types/community.ts
src/utils/common.ts

-  New command for top nft by volumes
-   ```$nft top```
**Media**

feat: nft top

---

src/adapters/config.ts
src/commands/community/sales/config.ts
src/commands/community/sales/index.ts
src/commands/index.ts

- Add command to config sales tracker channel
-  ```$sales config <channel>```

feat: sales tracker config

---

src/adapters/community.ts
src/commands/community/sales/index.ts
src/commands/community/sales/track.ts

-   Add sales track command
```$sales track <address> <platform>```

feat: sales tracker cmd

---

src/commands/index.ts
src/commands/renderSalesMessage.ts
src/types/sales.ts
src/utils/canvas.ts

feat: create renderSaleMessages

---

src/commands/defi/token/compare.ts

chore: fix compare token cmd

---

src/commands/games/tripod/index.ts

fix: triple town

---

src/adapters/community.ts
src/commands/community/nft/index.ts

-   Fixed messages display by Mochi
`$nft <symbol> <id>`
- Collection found in mochi but not indexer => _sync in progress_
- Collection not found in mochi => _collection not added_
- Collection found in mochi and indexer => _shows nft_

chore: fix get nft detail

---

src/commands/games/tripod/helpers.ts
src/commands/games/tripod/index.ts

fix: triple town chess-like notation

---

src/adapters/community.ts
src/commands/community/nft/index.ts

- nft detail now returns more correct error

chore: update nft detail

---

src/commands/games/tripod/render.ts

fix: triple town coords overlay

---

src/commands/community/nft/add.ts

chore: updating UI nftCollection

---

src/adapters/community.ts
src/commands/community/nft/index.ts
src/commands/community/nft/newListed.ts

create cmd for
```
$nft newListed
$help nft newListed
```

feat: creating nft newListed cmd

---

src/commands/community/nft/ticker.ts
src/utils/common.ts

- Add new field `Marketplace`
- Fix UI issue on mobile 
**Preview image**

chore: add new field marketplace & update UI

---

src/commands/community/nft/index.ts
src/commands/community/nft/recent.ts

- Change `$nft newListed` to `$nft recent`

chore: update nft recent

---

src/commands/community/nft/ticker.ts
src/utils/common.ts

- Add unique owner field to nft ticker, rearrange contents

chore: update nft ticker

---

src/commands/community/nft/list.ts
src/types/community.ts
src/utils/common.ts

-   Change `$nft list` command output UI
**Preview**

Chore/nft list update UI

---

package.json
src/commands/community/track/slash.ts
src/commands/index.ts
src/commands/slash/index.ts
src/index.ts
yarn.lock

Create slash for sale track
/track

feat: create slash cmt for sale track

---

src/commands/community/nft/add.ts

- `$nft add` now send another field `author: msg.author.username` to the API

chore: update nft add

---

src/commands/index.ts

chore: update track cmd

---

src/commands/community/track/sales.ts

chore: update sales tracker

---

src/commands/slash/index.ts

update track slash works on multiple guild

chore: update track slash

---

src/env.ts
src/events/guildCreate.ts
src/events/guildMemberAdd.ts
src/events/interactionCreate.ts
src/events/inviteCreate.ts
src/events/inviteDelete.ts
src/events/messageCreate.ts
src/events/messageReactionAdd.ts
src/events/messageReactionRemove.ts
src/events/ready.ts
src/utils/ChannelLogger.ts

- Update sending embed error message to log channel
- Embed format: `bot crashed due to reason: <function_name> <error_name>:<error_description>`

chore: update log error

---

src/commands/community/nft/query.ts
src/utils/common.ts

chore: update UI nft query

---

src/commands/community/stats.ts

chore: update stats cmd

---

src/commands/games/tripod/index.ts
src/commands/games/tripod/render.ts
src/errors/AssetNotFoundError.ts

chore: log asset not found error

---

src/commands/config/reactionRole/add.ts
src/commands/config/reactionRole/list.ts
src/commands/config/reactionRole/remove.ts
src/commands/config/starboard/list.ts
src/events/messageReactionAdd.ts

-   Update pagination logic for $rr & update UI

chore: update pagination for rr && handle normal reaction

---

package.json
src/commands/games/tripod/index.ts
yarn.lock

fix: tripod 9

---

src/env.ts
src/utils/GameSessionManager.ts
src/utils/canvas.ts

fix: tripod 11

---

src/commands/community/verify/create.ts
src/commands/community/verify/list.ts
src/commands/community/verify/remove.ts

-  `$verify` is now admin only command

chore: update verify

---

package.json

fix: tripod 13

---

src/commands/community/nft/add.ts
src/commands/community/nft/query.ts
yarn.lock

- NFT display name is now a clickable link to `https://getmochi.co/nfts/<address>/<token_id>`
- Add error message for block not in sync

chore: update nft

---

src/utils/canvas.ts

fix: top command got clipped

---

src/commands/index.ts
src/events/messageReactionAdd.ts
src/events/messageReactionRemove.ts

-   [x] fix check msgID before call other api to prevent 500 status

fix: add check msgID config before call other api

---

package.json
src/adapters/config.ts
src/commands/community/nft/config.ts
src/commands/config/poe/index.ts
src/commands/config/poe/twitter/index.ts
src/commands/config/poe/twitter/list.ts
src/commands/config/poe/twitter/remove.ts
src/commands/config/poe/twitter/set.ts
src/commands/index.ts
src/env.ts
src/events/messageCreate.ts
src/types/common.ts
src/utils/common.ts
src/utils/discordEmbed.ts
src/utils/twitter-api.ts
yarn.lock

feat: twitter hashtag

---

src/commands/defi/token/list.ts

-   [x] Convert the `$tokens list` command output to a tabular format
**Media**

fix: tabulize token list command

---

src/utils/common.ts

chore: fix token name

---

src/utils/TwitterStream.ts

-   [x] Add the operator to exclude reply tweet in twitter stream
More info: https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/build-a-rule

fix: twitter stream exclude reply tweet

---

src/commands/defi/balances.ts
src/commands/defi/tip.ts
src/commands/defi/withdraw.ts
src/events/messageCreate.ts

- Allow commands in DM
- Remove message event listener for sales messages

chore: update DM cmds

---

src/commands/config/poe/twitter/set.ts
src/utils/TwitterStream.ts

-   [x] Normalize special value when hey arrive in discord chat message

fix: twitter stream, normalize value

---

src/commands/config/poe/twitter/set.ts

-   [x] Add support for parsing twitter account link and convert them to handle format

feat: support twitter link when setting twitter rule

---

src/adapters/config.ts
src/adapters/defi.ts
src/commands/defi/tip.ts
src/commands/defi/token/default.ts
src/commands/defi/token/index.ts

-   [x] Set default token for server
- Command: `$tokens default <symbol>`
- Example: `$tokens default eth`
**Workflow**

feat: set default token for server

---

src/adapters/community.ts
src/adapters/fetcher.ts
src/commands/community/nft/query.ts
src/commands/community/sales/track.ts
src/utils/common.ts
src/utils/discordEmbed.ts

-   [x] Add suggestion when querying a not found NFT collection symbol

feat: suggestion when query nft

---

src/commands/community/nft/query.ts
src/env.ts
src/utils/common.ts

-   [x] Replace `getmochi.co` with marketplace url

fix: replace getmochi.co with marketplace url

---

src/adapters/community.ts
src/adapters/config.ts
src/adapters/fetcher.ts
src/commands/community/nft/query.ts
src/commands/defi/ticker.ts
src/types/community.ts
src/types/config.ts

-   [x] Set default symbol if server haven't had one yet

feat: set default nft symbol

---

.env-sample
package.json

chore: set env

---

src/adapters/config.ts
src/commands/config/poe/twitter/list.ts
src/commands/config/poe/twitter/remove.ts
src/commands/config/poe/twitter/set.ts
src/utils/TwitterStream.ts

-   [x] Add support for `from:` syntax of twitter tweet watcher

feat: twitter tweet watcher support from syntax

---

src/adapters/config.ts
src/events/guildMemberAdd.ts

-   [x] Fix error set default role when new user join server
-   [x] Cannot parse empty json
**Media**
- When new user join server, `receive message:` is empty

chore: fix default role

---

src/adapters/community.ts
src/commands/community/nft/query.ts
src/utils/discordEmbed.ts

-   [x] Tweak UI of default nft symbol to be similar to default ticker

fix: tweak default nft symbol

---

src/adapters/community.ts
src/commands/community/nft/query.ts
src/utils/discordEmbed.ts

-   [x] Fix default symbol flow
**Sequence diagram**

fix: default nft symbol

---

src/adapters/defi.ts
src/commands/defi/balances.ts
src/commands/defi/withdraw.ts
src/errors/InsufficientBalanceError.ts

-  support command in DM for `bals` and `withdraw`

chore: dm support

---

src/commands/config/log/index.ts
src/commands/config/log/info.ts
src/commands/config/log/set.ts
src/commands/index.ts
src/types/config.ts

feat: view log channel cmd

---

src/utils/ChannelLogger.ts

-  Fixed channel logger crash when alert DM commands

chore: fix alert dm

---

src/commands/community/gm/info.ts

-   [x] Fix `gm` config response

fix: gm config response

---

src/commands/profile/profile.ts

-   [x] Add log for $profile command

chore: Add log for profile command

---

src/commands/config/nftRole/index.ts

-   [x] Decorate $nftrole comand
-   Use command `$nr @role <collection_address> <amount>`

refactor: decorate nftrole command

---

src/adapters/config.ts
src/adapters/defi.ts
src/commands/defi/ticker.ts
src/commands/defi/token/compare.ts
src/types/defi.ts
src/utils/canvas.ts

**Demo**
https://loom.com/share/fb89e0b6779846308f15f57bb972e518

feat: token compare suggestions

---

src/adapters/defi.ts
src/commands/defi/withdraw.ts

fix: withdraw error

---

src/adapters/config.ts
src/commands/config/levelRole/index.ts
src/commands/config/nftRole/index.ts

-   [x] Add error message role has been used
**Media**
Case role has used when configuring levelrole and nftrole

fix: add error msg when role has used

---

src/commands/community/gm/config.ts
src/events/messageCreate.ts

chore: update gm format

---

src/utils/ChannelLogger.ts

- Fix null read when send command in DM

chore: fix logger

---

src/commands/community/nft/index.ts
src/commands/community/nft/integrate.ts

-   [x] Polish $nft add response message
-   [x] Add alias `$mochi`

fix: polish nft integrate command

---

src/commands/config/nftRole/remove.ts

-   [x] Decorate command $nftrole remove
- Use command `$nftrole remove` or `$nr remove`
- Select the role, which you want to remove

refactor: decorate nftrole remove command

---

src/commands/config/levelRole/index.ts
src/commands/config/nftRole/index.ts

-   [x] handle config negative level
-   [x] handle config negative amount nftrole
**Media**

fix: handle config negative level

---

src/commands/community/nft/add.ts

- `$nft add` will reply with error message sent from server if is not 500

chore: update error msg

---

src/commands/profile/profile.ts
src/errors/CommandNotAllowedToRunError.ts
src/events/guildMemberAdd.ts
src/events/index.ts
src/events/inviteCreate.ts
src/events/inviteDelete.ts
src/events/ready.ts

fix: alert

---

src/commands/community/sales/remove.ts

-   [x] Small tweaks for the sale tracker command

fix: small tweak sale tracker command

---

src/commands/community/verify/info.ts
src/commands/community/verify/remove.ts
src/commands/community/verify/set.ts

-   [x] Fix action text in verify help message

fix: verify action text

---

src/adapters/fetcher.ts
src/adapters/profile.ts
src/commands/community/gm/streak.ts
src/commands/defi/deposit.ts
src/commands/profile/profile.ts
src/types/profile.ts

refactor: update profile adapter to use fetcher

---

src/adapters/defi.ts
src/commands/defi/airdrop.ts
src/commands/defi/ticker.ts
src/commands/defi/token/compare.ts
src/events/interactionCreate.ts
src/types/defi.ts
src/utils/common.ts

- Reason: The interactions expects that the bot should respond to user within 3 seconds. Sometimes the API response time exceed that limit so the above error appeared
- Solution: we should use `interaction.deferReply()` at the beginning of select-menu `handler` function, before proceed to handle any further logic
**Media**

fix: select menu - interaction failed

---

src/adapters/defi.ts
src/commands/defi/airdrop.ts
src/commands/defi/ticker_slash.ts
src/commands/defi/token/compare_slash.ts
src/commands/index.ts
src/env.ts
src/events/interactionCreate.ts
src/index.ts
src/types/common.ts
src/utils/commands.ts
src/utils/common.ts
src/utils/discordEmbed.ts

-   [x] Set up slash command
Currently I only worked to make the command run, other ones (e.g. help message, composeDiscordEmbed, ...) will need to be refactored in another PR
**Media**
https://user-images.githubusercontent.com/34529672/188536276-18d8cc86-7299-4f46-932a-015778eba667.mp4

feat: ticker slash command

---

.husky/pre-commit
package.json
scripts/generate-types.js
src/adapters/config.ts
src/commands/config/poe/twitter/set.ts
src/types/api.ts
src/utils/TwitterStream.ts
yarn.lock

-   [x] Generate typescript types for api
Follow the example and apply for the other apis
|Before|After|
|---|---|
|<img width="714" alt="Xnapper-2022-09-06-11 43 15" src="https://user-images.githubusercontent.com/25856620/188549084-5a635e74-286c-4137-bc58-4db65dc06f84.png">|<img width="687" alt="Xnapper-2022-09-06-11 49 29" src="https://user-images.githubusercontent.com/25856620/188549338-1a4f1a82-dcd8-4561-abdf-776f65cdc130.png">|

chore: generate ts types for api

---

src/events/interactionCreate.ts
src/types/common.ts

feat: slash command - ephemeral

---

src/commands/defi/ticker_slash.ts
src/commands/help_slash.ts
src/utils/constants.ts

-   [x] Fix: prefix `$` not working

fix: old prefix command

---

src/commands/config/log_slash/index.ts
src/commands/config/log_slash/info.ts
src/commands/config/log_slash/set.ts
src/index.ts
src/utils/discordEmbed.ts

-   [x] feat: log slash command
https://user-images.githubusercontent.com/104887632/188622368-9cd26ec2-a2f2-4565-bb32-c13193055ebf.mp4

feat: log slash command

---

src/commands/community/vote.ts
src/commands/help_slash.ts
src/commands/index.ts
src/events/interactionCreate.ts
src/index.ts
src/utils/commands.ts
src/utils/common.ts

-   [x] Add vote slash command
-   [x] Remove `slashCommands` in `src/index.ts`

feat: vote status

---

src/commands/config/log_slash/info.ts
src/commands/config/log_slash/set.ts
src/utils/discordEmbed.ts

-   [x] fix: add footer to log command

fix: add footer to log command

---

src/adapters/defi.ts
src/commands/defi/watchlist/add.ts
src/commands/defi/watchlist/index.ts
src/commands/defi/watchlist/remove.ts
src/commands/defi/watchlist/view.ts
src/commands/index.ts
src/events/interactionCreate.ts
src/types/common.ts
src/types/defi.ts
src/utils/canvas.ts
src/utils/commands.ts

**Media**
https://drive.google.com/file/d/1QrC9EXEzT637tkwUL1teHlVlUQbbI3fU/view?usp=sharing

feat: watchlist commands

---

src/adapters/community.ts
src/commands/community/top.ts
src/commands/community/top_slash.ts
src/commands/index.ts
src/index.ts

-   [x] feat: top slash command
https://user-images.githubusercontent.com/104887632/188841286-97fba01d-c57d-49a9-acbc-6b57746d858a.mp4

feat: top slash command

---

src/commands/community/verify_slash/index.ts
src/commands/community/verify_slash/info.ts
src/commands/community/verify_slash/remove.ts
src/commands/community/verify_slash/set.ts
src/commands/index.ts

-   [x] feat: verify slash command
https://user-images.githubusercontent.com/104887632/188860706-018b81d3-fc4e-4102-b548-8f130952b0b4.mp4

feat: verify slash command

---

src/adapters/community.ts
src/commands/community/vote.ts
src/types/api.ts

fix: integrate api for vote command

---

src/commands/defi/watchlist/index.ts
src/commands/defi/watchlist/remove.ts
src/commands/defi/watchlist_slash/add.ts
src/commands/defi/watchlist_slash/index.ts
src/commands/defi/watchlist_slash/remove.ts
src/commands/defi/watchlist_slash/view.ts
src/commands/index.ts

-   [x] watchlist commands text version: `$watchlist`

feat: watchlist v2

---

src/commands/defi/watchlist/view.ts
src/commands/defi/watchlist_slash/view.ts

-   [x] respond info message when watchlist is empty
**Media**

fix: handle watchlist no data

---

src/adapters/config.ts
src/adapters/fetcher.ts
src/commands/config/nftRole/index.ts
src/commands/config/nftRole/list.ts
src/commands/config/nftRole/remove.ts
src/commands/config/nftRole/set.ts

-   [x] New feature nft role with grouping
-   [x] Add new action `set` to $nr command to be consistent with other role command

feat: nft role multiple collection

---

src/adapters/defi.ts
src/commands/defi/watchlist/add.ts
src/commands/defi/watchlist/index.ts
src/commands/defi/watchlist/remove.ts
src/commands/defi/watchlist/view.ts
src/commands/defi/watchlist_slash/add.ts
src/commands/defi/watchlist_slash/index.ts
src/commands/defi/watchlist_slash/remove.ts
src/commands/defi/watchlist_slash/view.ts

feat: watchlist view pagination

---

src/adapters/config.ts
src/commands/config/levelRole/index.ts
src/commands/config/levelRole/list.ts
src/commands/config/levelRole_slash/index.ts
src/commands/config/levelRole_slash/list.ts
src/commands/config/levelRole_slash/remove.ts
src/commands/config/levelRole_slash/set.ts
src/commands/index.ts
src/types/api.ts

-   [x] Level role slash command
Demo video
https://user-images.githubusercontent.com/49946656/189180457-f973f313-e5bf-4451-a540-bc836cde5718.mov

feat: level role slash command

---

src/commands/config/defaultRole_slash/index.ts
src/commands/config/defaultRole_slash/info.ts
src/commands/config/defaultRole_slash/remove.ts
src/commands/config/defaultRole_slash/set.ts
src/commands/index.ts
src/types/api.ts

-   [x] Defaultrole slash command
https://user-images.githubusercontent.com/49946656/189254127-b6707ba2-3116-47b7-9d37-dd60499ff4f6.mov

feat: defaultrole slash command

---

src/commands/community/vote.ts
src/commands/community/vote_slash.ts
src/commands/index.ts

-   [x] Add a text version of vote command
-   [x] Fix progressBar logic

chore: add vote text command

---

src/commands/config/nftRole/list.ts
src/types/api.ts

-   [x] Sort nftrole ascending base on number of token needed

fix: tweak new nftrole command

---

src/commands/profile/profile.ts
src/types/api.ts

-   [x] feat: view other users' profile

feat: view other users profile

---

src/adapters/profile.ts
src/commands/profile/profile.ts
src/types/api.ts
src/utils/common.ts

-   [x] Add faction exp to $profile command
-   [x] Edit role text to reference role directly instead of text
-   [x] Wrap address in code format
`$profile`

feat: add faction xp to profile

---

src/adapters/fetcher.ts
src/commands/defi/watchlist/view.ts
src/commands/defi/watchlist_slash/view.ts
src/types/common.ts
src/utils/common.ts

refactor: watchlist interface

---

src/commands/community/vote.ts
src/types/api.ts

-   [x] Change the vote text dynamically base on timer
`$vote`

fix: upvote timer source

---

src/commands/profile/profile.ts
src/types/api.ts

-   [x] chore: view other profile by username

chore: view other profile by username

---

src/commands/community/vote.ts
src/types/api.ts

-   [x] Fix wrong timer source check
`$vote`
**Media**
This is the original bug

fix: wrong timer source check

---

src/commands/defi/ticker.ts
src/commands/defi/ticker_slash.ts
src/commands/defi/token/compare.ts
src/commands/defi/token/compare_slash.ts
src/commands/defi/watchlist/add.ts
src/commands/defi/watchlist/remove.ts
src/commands/defi/watchlist/view.ts
src/commands/defi/watchlist_slash/add.ts
src/commands/defi/watchlist_slash/index.ts
src/commands/defi/watchlist_slash/remove.ts
src/commands/defi/watchlist_slash/view.ts
src/commands/index.ts
src/events/interactionCreate.ts
src/types/api.ts
src/utils/CacheManager.ts

-   [x] Implement memory caching for API response

feat: response caching

---

src/commands/defi/watchlist/view.ts
src/commands/defi/watchlist_slash/view.ts
src/utils/common.ts

-   [x] Update UI for default watchlist case
**Media**

refactor: handle default watchlist case

---

src/commands/community/gift.ts
src/commands/community/gm/index.ts
src/commands/community/invite/index.ts
src/commands/community/invite/link.ts
src/commands/community/nft/add.ts
src/commands/community/nft/index.ts
src/commands/community/nft/integrate.ts
src/commands/community/sales/index.ts
src/commands/community/sales/track.ts
src/commands/community/verify/index.ts
src/commands/community/verify/info.ts
src/commands/community/verify/set.ts
src/commands/community/vote.ts
src/commands/config/defaultRole/index.ts
src/commands/config/levelRole/index.ts
src/commands/config/log/index.ts
src/commands/config/nftRole/index.ts
src/commands/config/nftRole/set.ts
src/commands/config/poe/index.ts
src/commands/config/reactionRole/add.ts
src/commands/config/reactionRole/index.ts
src/commands/defi/balances.ts
src/commands/defi/deposit.ts
src/commands/defi/token/addCustom.ts
src/commands/defi/token/index.ts
src/commands/defi/watchlist/index.ts
src/commands/defi/watchlist/view.ts
src/commands/help.ts
src/commands/profile/profile.ts

-   [x] Add and edit examples for help message, list examples: https://www.notion.so/console-labs/CLICK-HERE-Detailed-example-for-each-command-ffeb0481e47e440587fece075cc07c04

chore: edit examples for cmds

---

src/commands/config/nftRole/list.ts

-   [x] Remove extra `)` char
`$nr list`

fix: remove ) char

---

src/adapters/config.ts
src/commands/config/welcome_slash/index.ts
src/commands/config/welcome_slash/info.ts
src/commands/config/welcome_slash/message.ts
src/commands/config/welcome_slash/remove.ts
src/commands/config/welcome_slash/set.ts
src/commands/index.ts
src/events/guildMemberAdd.ts
src/types/api.ts

- New commands to config welcome channel `/welcome info` and `/welcome set <channel>`
- Bot greets new members to the guild

feat: welcome msg

---

src/commands/defi/token/compare.ts
src/commands/defi/token/compare_slash.ts
src/commands/defi/watchlist/view.ts
src/commands/defi/watchlistcompact/index.ts
src/commands/defi/watchlistcompact/view.ts
src/commands/index.ts

-   [x] $watchlistcompact: watchlist 12-item version
**Media**

feat: watchlist compact

---

src/commands/config/nftRole/set.ts
src/types/api.ts

-   [x] edit example and usage for nftrole

chore: edit example and usage for nftrole

---

src/commands/profile/profile.ts
src/types/api.ts

-   [x] chore: view other profile by displayname
**Images**

chore: view other profile by displayname

---

src/events/interactionCreate.ts

-   [x] Only send alert if a message is found in interaction, otherwise use logger.error
The bug

fix: channel alert

---

package.json

-   [x] chore: upgrade discord.js
**Solution**
https://stackoverflow.com/questions/72077172/typeerror-cannot-read-properties-of-undefined-reading-cache-discord-js
Error:

chore: upgrade discord.js

---

package.json
src/utils/CommandChoiceManager.ts
yarn.lock

-   [x] New version of discord.js has some incompatible type -> fix
-   [x] Upgrade `ts-node` and `ts-node-dev`

fix: typescript of new discord version

---

src/commands/config/poe/index.ts
src/commands/config/poe/twitter/index.ts
src/commands/config/poe/twitter/set.ts
src/commands/profile/profile.ts

chore: edit example of poe

---

src/adapters/community.ts
src/commands/community/nft/query.ts
src/commands/community/nft/stats.ts
src/commands/community/stats.ts
src/errors/APIError.ts
src/errors/CommandError.ts
src/utils/discordEmbed.ts

-   [x] Refactor the rest of community adapter module
-   [x] Cleanup alert in several commands (mostly `community` related)
**Media**
https://user-images.githubusercontent.com/25856620/190355659-cbeae0b6-aa23-4f2e-8e93-fa0b69ecec75.mp4

refactor: alert ep 2

---

src/commands/defi/token/add.ts
src/types/api.ts

-   [x] Check 25 options when sending token add options
https://user-images.githubusercontent.com/49946656/190377629-8a584296-569e-44d0-8937-b2bb5daf8064.mov

fix: check 25 options when sending token add options

---

src/adapters/profile.ts
src/commands/profile/profile.ts
src/types/api.ts

-   [x] Fix nft collection show wrong name
-   [x] Add button to switch view between my profile and my nft
- Use command `$profile`
- Select My NFT button

fix: profile nft show wrong collection name

---

.github/workflows/test.yml
.husky/pre-commit
jest.config.js
src/adapters/fetcher-utils.test.ts
src/adapters/fetcher-utils.ts
src/adapters/fetcher.ts

-   [x] Add functionality to convert body property to snake case (support nested)
-   [x] Add test for convert snake case function

feat: add convert to snake case for body payload

---

src/commands/community/nft/query.ts
src/commands/config/nftRole/list.ts

-   [x] Show chain name instead of chain id
-   [x] Add missing export of compose function
**Media**

fix: nft role chain name

---

src/adapters/fetcher-utils.test.ts
src/adapters/fetcher-utils.ts

-   [x] Handle array case when converting snake_case

fix: convert snakecase array

---

src/commands/community/sales/track.ts
src/commands/defi/token/default.ts

chore: standardize cmd

---

src/errors/BaseError.ts
src/events/interactionCreate.ts
src/events/messageCreate.ts
src/utils/discordEmbed.ts

-   [x] Pass message of unexpected error (if any) to BotBaseError so the log can show it

fix: pass message to bot base error

---

src/commands/index.ts
src/events/interactionCreate.ts

-   [x] Add text to remind user to vote when appropriate
1. Vote
2. Use any command, notice there is no text to remind
3. Wait until vote available again
4. Use any command again, there will be a remind text

feat: remind vote

---

src/commands/community/nft/query.ts
src/commands/community/nft/ticker.ts
src/commands/config/defaultRole/remove.ts
src/commands/config/levelRole/remove.ts
src/commands/config/nftRole/list.ts
src/commands/config/nftRole/remove.ts
src/commands/config/nftRole/set.ts

https://www.notion.so/console-labs/Check-all-bot-response-a843ba87c3fe406c9b7bf03b388c64b8

fix: bot response

---

src/errors/CommandNotAllowedToRunError.ts

fix: response only admin

---

src/errors/CommandNotAllowedToRunError.ts

fix: remove error emoji

---

src/events/guildMemberAdd.ts

-   [x] add send unknown msg
Before
After

chore: add send unknown msg

---

src/adapters/webhook.ts
src/errors/BaseError.ts
src/events/messageCreate.ts
src/events/messageReactionAdd.ts
src/types/api.ts
src/utils/ChannelLogger.ts

-   [x] Refactor webhook error alert message to include error message
-   [x] Refactor BotBaseError to not include full `msgOrInteraction` object

refactor: error

---

src/events/messageCreate.ts

- fixed messageCreate time format

chore: fix time format

---

src/types/webhook.ts

fix: parsing member

---

src/commands/community/nft/integrate.ts
src/commands/community/nft/query.ts
src/commands/community/nft/ticker.ts

- `$nft integrate` handle case invalid address

fix: nft integrate resp

---

src/commands/community/nft/ticker.ts
src/commands/community/verify_slash/info.ts
src/commands/config/nftRole/set.ts
src/commands/defi/tip.ts
src/types/api.ts
src/utils/discordEmbed.ts

fix: minor response

---

package.json
src/adapters/community.ts
src/adapters/fetcher.ts
src/commands/community/invite/aggregation.ts
src/commands/community/invite/info.ts
src/commands/community/invite/leaderboard.ts
src/commands/community/invite/link.ts
src/commands/community/nft/query.ts
src/commands/community/nft/stats.ts
src/commands/community/nft/ticker.ts
src/commands/community/nft/top.ts
src/commands/community/top.ts
src/commands/config/reactionRole/list.ts
src/commands/defi/ticker.ts
src/commands/defi/ticker_slash.ts
src/commands/defi/watchlist/view.ts
src/commands/defi/watchlist_slash/view.ts
src/errors/APIError.ts
src/types/api.ts
src/utils/ChannelLogger.ts
yarn.lock

-   [x] Fix $top command
-   [x] Add curl to alert message when it's an API error
`$top`
$top after fixing
Add curl to alert message so devs can try the error api and see what's wrong

refactor: alert message

---

src/adapters/defi.ts
src/events/ready.ts
src/types/api.ts
src/types/defi.ts
src/utils/constants.ts

-   [x] Show gas tracker randomly for these chains: ETH, FTM, BSC, POLYGON
-  Run bot, check the bot status

feat: gas tracker status

---

src/adapters/defi.ts
src/events/ready.ts

-   [x] Fix gas tracker status format (remove slow gas price & rename polygon -> matic)
-   Run bot, check the bot status

fix: gas tracker format

---

src/events/guildMemberAdd.ts

Demo:
https://www.loom.com/share/e43f473b58454206a53caca4ebf422db

feat: dm when user join server

---

src/adapters/fetcher.ts
src/adapters/webhook.ts
src/types/webhook.ts
src/utils/ChannelLogger.ts

-   [x] Normalize webhook payload to include only primitive values
-   [x] Abstract makeLog function to create api log
-   [x] Rework webhook alert message

fix: normalize webhook payload

---

src/adapters/config.ts
src/commands/config/telegram/config.ts
src/commands/config/telegram/index.ts
src/commands/index.ts

feat: telegram config command

---

src/adapters/config.ts
src/commands/community/vote/index.ts
src/commands/community/vote/info.ts
src/commands/community/vote/remove.ts
src/commands/community/vote/set.ts
src/commands/community/vote/vote_slash.ts
src/commands/index.ts
src/types/api.ts

-   [x] Config vote channel
`$vote info`
`$vote set`
`$vote remove`

feat: config vote channel

---

src/events/guildMemberAdd.ts

-   [x] fix: deleted account response
- Create invite link and delete account, api cannot find the inviter by code

fix: deleted account response

---

src/events/guildMemberAdd.ts
src/types/api.ts

chore: DM messgae

---

src/commands/community/gm/streak.ts
src/commands/community/vote/index.ts
src/commands/defi/balances.ts
src/commands/help.ts
src/commands/profile/profile.ts
src/utils/discordEmbed.ts

**Original**
**Fixed - Mobile**
**Fixed - Desktop**

fix: mobile view

---

src/adapters/usage_stats.ts
src/commands/index.ts

-   [x] send usage stats to server

feat: send usage stats to server

---

src/commands/community/vote/index.ts

-   [x] Add a check when a guild set a vote channel
`$vote set #channel`
`$vote`

fix: add vote channel check

---

src/commands/community/vote/index.ts

-   [x] Add missing same channel id check

fix: vote channel miss check same channel id

---

src/adapters/config.ts
src/commands/config/reactionRole/list.ts
src/events/messageReactionAdd.ts
src/events/messageReactionRemove.ts

-   [x] Fix bug cannot read property role of undefined
Use `$rr` to set up some reaction role for a message, then remove that then run `$rr list`

fix: cannot read role of undefined

---

.github/workflows/gke-dev.yml
src/env.ts
src/events/ready.ts
src/index.ts

-   [x] chore: add healthcheck
**Media**
https://user-images.githubusercontent.com/104887632/191474465-4bea0992-8666-4d10-88f4-cd509990314a.mp4

chore: add healthcheck

---

src/commands/community/nft/list.ts

-   [x] Change read nft list response
https://user-images.githubusercontent.com/49946656/191479252-e0971553-e0ae-4769-8040-6bb8d8a7f929.mov

chore: change nft list response

---

src/adapters/community.ts
src/commands/community/nft/query.ts
src/types/api.ts
src/utils/common.ts

- `$nft magicats 1`
- `$nft neko 5`

feat: nft query transaction history

---

src/events/guildCreate.ts

- Send introduce msg to system channel in server
https://www.loom.com/share/27deaa233a854496a2f3e3a30a14653b
- System channel: require enable in server settings

chore: intro mochi in system channel

---

src/commands/community/prune/inactive.ts
src/commands/community/prune/index.ts
src/commands/community/prune/without.ts
src/commands/community/prune_slash/inactive.ts
src/commands/community/prune_slash/index.ts
src/commands/community/prune_slash/without.ts
src/commands/index.ts
src/env.ts
src/types/api.ts

- Command to purge inactive or users without a specific role

feat: prune

---

src/events/guildMemberAdd.ts

-   [x] fix: user block DM
- Error:
- Fixed:
https://user-images.githubusercontent.com/104887632/191701198-e195fc26-3239-40d5-b3e1-7374142d6f34.mp4

fix: user block DM

---

src/adapters/community.ts
src/commands/community/verify/info.ts
src/commands/community/verify/remove.ts
src/commands/community/verify/set.ts
src/commands/community/verify_slash/info.ts
src/commands/community/verify_slash/remove.ts
src/commands/community/verify_slash/set.ts
src/errors/GuildIdNotFoundError.ts
src/types/api.ts

-   [x] Add optional role param of $verify set command
-   [x] Fix bug $verify remove if there is already no verify channel
`$verify remove`
`$verify set #general @role`

feat: assign role after verify

---

src/commands/defi/watchlist/index.ts
src/commands/defi/watchlist/view.ts
src/commands/defi/watchlist_slash/add.ts
src/commands/defi/watchlist_slash/index.ts
src/commands/defi/watchlist_slash/view.ts
src/index.ts
src/types/api.ts

e.g. $wl add sol/usdt
**Media**

feat: wl - support pair

---

src/types/api.ts
src/utils/common.ts

-   [x] fix util func `capitalizeFirst()` - handle empty string

fix: capitalizeFirst - handle empty string

---

src/adapters/config.ts
src/commands/community/prune/inactive.ts
src/commands/community/prune/index.ts
src/commands/community/prune/remove.ts
src/commands/community/prune/whitelist.ts
src/commands/community/prune/without.ts
src/commands/community/prune_slash/without.ts
src/types/api.ts

- New commands: `$prune whitelist` and `$prune remove` to add and remove whitelisted role from being pruned
- Bot DM user after being kicked
1 user doesn't have role `@test` but he has a whitelisted role so no prune happens

feat: prune config

---

src/adapters/config.ts
src/commands/config/starboard/index.ts
src/commands/config/starboard/list.ts
src/commands/config/starboard/remove.ts
src/commands/config/starboard/set.ts
src/commands/index.ts
src/events/messageReactionAdd.ts

https://www.loom.com/share/7d6bee26d7804a15ac1d54aacf9d61f6

refactor: starboard flow

---

src/commands/config/reactionRole/add.ts
src/events/guildMemberAdd.ts

-   [x] fix: cached emojis
-   [x] fix: catch error when createDM
- When add new emojis, bot cannot handle it because emojis get from cache

fix: cached emojis

---

package.json
src/commands/index.ts
src/utils/commands.ts
yarn.lock

- When users use a wrong command, return a suggestion if found else a help message

feat: suggest cmd

---

src/commands/defi/watchlist/add.ts
src/commands/defi/watchlist/view.ts
src/commands/defi/watchlist_slash/add.ts
src/commands/defi/watchlist_slash/view.ts

refactor: pair for watchlist

---

src/commands/config/reactionRole/index.ts
src/commands/config/reactionRole/set.ts
src/commands/index.ts
src/events/messageReactionAdd.ts

- Fix api return 500 not found. When user add emoji which is not config in reaction role -> return null with status 200
- Wrap data response in `data`
- Update `$rr add` to `$rr set`

fix: rr flow

---

src/commands/community/vote/index.ts
src/commands/community/vote/info.ts
src/commands/community/vote/remove.ts
src/commands/community/vote/set.ts
src/commands/community/vote/top.ts
src/commands/config/starboard/index.ts
src/commands/config/starboard/list.ts
src/commands/config/telegram/config.ts
src/commands/config/telegram/index.ts
src/types/api.ts
src/utils/constants.ts

-   [x] Add gitbook for cmd vote, starboard, telegram
-   [x] Standardlize cmd telegram and starboard

chore: add gitbook and standardlize cmd

---

src/commands/index.ts
src/utils/commands.ts
src/utils/common.ts
src/utils/discordEmbed.ts

- update command suggestion UI
- change vote remind chance to appear to 30%

chore: update suggestion

---

src/commands/community/prune/inactive.ts
src/commands/community/prune/index.ts
src/commands/community/prune/remove.ts
src/commands/community/prune/whitelist.ts
src/commands/community/prune/without.ts
src/utils/constants.ts

-   [x] add gitbook for cmd prune

chore: add gitbook for cmd prune

---

src/types/api.ts
src/utils/TwitterStream.ts

-   [x] Wrap methods of TwitterStream to avoid crashing the bot

fix: handle exception twitter stream

---

src/commands/config/defaultRole/index.ts
src/commands/config/levelRole/index.ts
src/commands/config/nftRole/index.ts
src/commands/config/reactionRole/index.ts

-   [x] Complementary for #400

fix: add missing roles command

---

src/commands/defi/ticker.ts
src/commands/defi/ticker_slash.ts
src/events/guildMemberAdd.ts

- Welcome message now mentions user
- Removed credit text in `watchlist`

chore: update texts

---

src/commands/community/nft/query.ts
src/types/api.ts

-   [x] Add listing marketplace field to NFT Detail view
-   `$nft neko 3400`

fix: nft detail show listing marketplace

---

src/commands/help.ts
src/commands/help_slash.ts
src/types/api.ts
src/utils/common.ts

-   [x] Rework $help interface
-   [x] New /help interface
`$help`
`/help`

fix: new help interface

---

src/events/guildMemberAdd.ts
src/types/api.ts
src/utils/discordEmbed.ts

chore: update welcome UI

---

src/adapters/config.ts
src/commands/config/levelRole/remove.ts
src/commands/config/reactionRole/remove.ts
src/commands/config/reactionRole/set.ts
src/types/api.ts

-   [x] chore: wrap response for reaction role + level role
- Reaction role + level role flow
https://user-images.githubusercontent.com/104887632/192502983-73ea4ffe-c0e8-4755-a7a9-0746545473e0.mp4
https://user-images.githubusercontent.com/104887632/192524430-fd3858c1-48b0-4fe3-81c3-2678d6811e7c.mp4

chore: wrap response

---

src/commands/defi/ticker.ts
src/commands/defi/ticker_slash.ts
src/types/api.ts

-   [x] ticker - show credit only when display bull/bear meme

refactor: ticker credit

---

package.json
src/commands/defi/token/index.ts
src/commands/defi/token/info.ts
src/types/api.ts
src/types/defi.ts
yarn.lock

-   [x] Add command token info
-  [ ] Token info in ticker command (will do in next PR)
https://user-images.githubusercontent.com/49946656/192667412-509fac25-7143-4bcf-b056-ff019830663f.mov

feat: token info command

---

src/errors/BaseError.ts
src/events/messageDelete.ts
src/types/api.ts

-   [x] fix: missing author
https://user-images.githubusercontent.com/104887632/192686269-a158df33-51cb-4937-b5ec-977aeeddd8f8.mp4

fix: missing author

---

src/commands/profile/profile.ts
src/events/messageReactionAdd.ts

-   [x] Filter out empty collection
https://user-images.githubusercontent.com/25856620/192729529-e472b062-e03e-4025-af89-9b88075d42e1.mp4

fix: profile empty collection name

---

src/adapters/defi.ts
src/adapters/fetcher.ts

-   [x] Add silent mode to gas price api (only log if there is an error)

fix: add silent mode to gas api

---

src/commands/community/nft/query.ts

-   [x] Handle token not found and token syncing case
`$nft bb 1`
`$nft neko 200000000`

fix: nft query edge case token not synced

---

src/commands/help.ts
src/commands/help_slash.ts
src/types/api.ts

-   [x] Tweaks for help message
`/help`
`$help`

fix: help interface

---

src/adapters/community.ts

-   [x] fix: stats method
https://user-images.githubusercontent.com/104887632/192945537-579254b5-498b-401c-8afa-d77f9ab03831.mp4

fix: stats method

---

src/adapters/defi.ts
src/commands/defi/watchlist/add-nft.ts
src/commands/defi/watchlist/index.ts
src/commands/defi/watchlist/remove-nft.ts
src/commands/defi/watchlist/view.ts
src/commands/defi/watchlist_slash/add-nft.ts
src/commands/defi/watchlist_slash/index.ts
src/commands/defi/watchlist_slash/remove-nft.ts
src/commands/defi/watchlist_slash/view.ts
src/types/api.ts

-   [x] View/add/remove nft watchlist
-   [x] Support slash command
-  `$wl add-nft neko` | `/watchlist add-nft neko`
-  `$wl remove neko` | `/watchlist remove-nft neko`
- `$wl view` | `/watchlist view`

feat: nft watchlist

---

src/commands/community/nft/recent.ts
src/types/api.ts

fix: nft recent

---

src/adapters/config.ts
src/commands/config/starboard/remove.ts
src/commands/config/starboard/set.ts
src/types/api.ts

-   [x] chore: wrap response in config

chore: wrap response in config

---

src/commands/games/tripod/index.ts
src/events/guildCreate.ts
src/events/guildDelete.ts
src/events/guildMemberAdd.ts
src/events/index.ts
src/events/interactionCreate.ts
src/events/inviteCreate.ts
src/events/inviteDelete.ts
src/events/messageCreate.ts
src/events/messageDelete.ts
src/events/messageReactionAdd.ts
src/events/messageReactionRemove.ts
src/events/ready.ts
src/types/api.ts
src/utils/ChannelLogger.ts
src/utils/discordEmbed.ts
src/utils/wrapError.ts

-   [x] Add `wrapError` to abstract exception handling
-   [x] Add `alertStackTrace` method

refactor: add wrapError helper

---

package.json
src/adapters/defi.ts
src/commands/community/nft/top.ts
src/commands/index.ts
src/events/index.ts
src/events/inviteCreate.ts
src/events/inviteDelete.ts
src/events/ready.ts
src/types/api.ts
src/utils/ChannelLogger.ts
src/utils/CommandChoiceManager.ts
src/utils/commands.ts
src/utils/common.ts
src/utils/discordEmbed.ts
src/utils/invites.ts

-   [x] Remove all circular dependencies

fix: circular dependency

---

src/adapters/config.ts
src/env.ts
src/errors/BaseError.ts
src/utils/ChannelLogger.ts
src/utils/wrapError.test.ts
src/utils/wrapError.ts
tests/mocks/client.ts
tests/mocks/index.ts
tests/mocks/message.ts

-   [x] Add test for `wrapError`
`yarn test`

chore: add test for wrapError

---

src/adapters/defi.ts
src/commands/defi/airdrop.ts
src/commands/defi/balances.ts

chore: wrap response defi

---

src/commands/community/invite/info.ts

fix: invalid field

---

.husky/pre-commit
src/commands/defi/ticker.ts
src/commands/defi/ticker_slash.ts
src/events/interactionCreate.ts
src/types/api.ts

-   [x] token info in ticker cmd
https://www.loom.com/share/4450fde31cb044438ac1361b95eb90f6

feat: token info in ticker cmd

---

src/commands/defi/ticker.ts
src/commands/defi/ticker_slash.ts
src/commands/help.ts
src/types/api.ts

-   [x] fix typo in help msg for cmd stats
-  [x] new emoji for ticker cmd
help:
ticker:

chore: fix typo stats help cmd

---

src/commands/help.ts
src/types/api.ts

fix: use new telegram logo

---

src/utils/wrapError.ts

-   [x] Fix bad logic check and not able to fetch reference message

fix: wrapError not able to fetch reference message

---

src/events/messageCreate.ts

Allow emoji and sticker for gm

chore: allow gm emoji and sticker

---

package.json
src/commands/games/tripod/index.ts
src/commands/index.ts
src/env.ts
src/logger.ts
src/types/common.ts

-   [x] Disable logger when running test
-   [x] Enable `experimental` feature

chore: small tweaks

---

src/commands/defi/ticker.ts
src/commands/defi/ticker_slash.ts
src/events/guildMemberAdd.ts

-   [x] add defer update for interaction in ticker command
-  [x] fix typo in invite count message

fix: add defer update for ticker interaction

---

src/adapters/community.ts
src/commands/community/nft/ticker.ts
src/events/interactionCreate.ts

-   [x] Add suggestion to nft ticker
-   [x] Add marketcap info and update pricing, date format for ticker
-   [x] Add nft info view
- `$nft ticker mgc`

fix: add marketcap and token info to ticker nft

---

src/commands/defi/ticker.ts
src/commands/defi/ticker_slash.ts

-   [x] remove defer update in handler selection

fix: remove defer selection

---

src/commands/community/nft/ticker.ts

-   [x] Add change percentage (1d, 7d, 1M)
-   [x] Update styling address + hyperlink in ticker info
- `$nft ticker neko`

fix: add change percentage and update styling nft ticker

---

src/commands/community/nft/query.ts
src/commands/config/nftRole/remove.ts

Add price in listing fields in nft query

chore: token price nft detail

---

src/commands/community/nft/ticker.ts
src/commands/defi/ticker.ts
src/commands/defi/ticker_slash.ts
src/commands/defi/token/compare.ts
src/commands/defi/token/compare_slash.ts
src/events/interactionCreate.ts
src/types/api.ts
src/utils/canvas.ts

fix: ticker errors

---

src/utils/canvas.ts

refactor: update ETH chart color

---

src/errors/APIError.ts

-   [x] Update api error response

fix: update api error response

---

src/commands/community/trade/index.ts
src/commands/community/trade/utils.ts

-   [x] Add emoji for confirm/cancel case
-   [x] Add logic require 2 confirm to close trade

fix: minor tweaks to the trade flow

---

src/commands/community/trade/index.ts
src/commands/community/trade/utils.ts
src/events/interactionCreate.ts
src/events/messageCreate.ts

-   [x] Refactor some code + change reply offer to click button offer
`$trade a b`

refactor: trade

---

src/commands/community/nft/query.ts
src/utils/common.ts

-   [x] Add separator and group listing/price together

chore: group and cleanup nft query tx and listing

---

src/adapters/config.ts
src/commands/community/nft/ticker.ts

-   [x] Add select default for `$nft ticker`
-  `$nft ticker neko`

fix: select default nft ticker

---

src/adapters/config.ts
src/commands/config/defaultRole/info.ts
src/commands/config/defaultRole/set.ts
src/commands/config/levelRole/list.ts
src/commands/config/levelRole/remove.ts
src/commands/config/nftRole/list.ts
src/commands/config/nftRole/remove.ts
src/commands/config/reactionRole/list.ts
src/utils/common.ts

refactor: update role commands interface

---

src/events/guildMemberAdd.ts
src/types/api.ts

-   [x] fix: error when create dm
- Error

fix: error when create dm

---

src/commands/community/nft/query.ts
src/commands/community/nft/ticker.ts
src/commands/defi/ticker.ts
src/commands/defi/ticker_slash.ts
src/commands/defi/token/compare.ts
src/commands/defi/token/compare_slash.ts
src/commands/index.ts
src/events/interactionCreate.ts
src/types/api.ts
src/types/common.ts
src/utils/common.ts
src/utils/default-setters.ts
src/utils/discordEmbed.ts

-   [x] Abstract the set default flow

refactor: set default handler

---

.github/workflows/test.yml
.husky/pre-commit
package.json
src/commands/defi/watchlist/add.test.ts
src/commands/defi/watchlist/remove.test.ts
src/types/api.ts

-   [x] test: watchlist add + remove

test: watchlist

---

src/commands/defi/watchlist/add-nft.test.ts
src/commands/defi/watchlist/remove-nft.test.ts
src/commands/defi/watchlist/remove-nft.ts
src/commands/defi/watchlist/remove.test.ts
src/commands/defi/watchlist/view.test.ts

-   [x] test: add more tests for watchlist

test: add more tests for watchlist

---

src/commands/defi/ticker.test.ts

-   [x] unit test for $ticker 
yarn test

test: unit test for ticker

---

src/commands/community/vote/index.test.ts
src/commands/community/vote/index.ts
src/commands/community/vote/info.test.ts
src/commands/community/vote/info.ts
src/commands/community/vote/remove.test.ts
src/commands/community/vote/remove.ts
src/commands/community/vote/set.ts
src/commands/community/vote/top.test.ts
src/commands/community/vote/top.ts

chore: test vote

---

src/commands/community/nft/ticker.ts
src/commands/defi/ticker.ts
src/commands/defi/ticker_slash.ts

-   [x] Fix binding `this` to null value in `getDefaultSetter`

fix: bind null in getDefaultSetter

---

src/commands/defi/token/info.ts

-   [x] default token for $token info
$token info abc
https://www.loom.com/share/626a59013c0a4707bb71a358192d2998

chore: default for token info

---

src/adapters/config.ts
src/commands/defi/token/addCustom.ts

-   [x] Fix split error fail
Alert: 
https://www.loom.com/share/1d3eb636bec5418ba9fd8304f1f51adb

fix: fix split error fail

---

src/commands/community/nft/query.ts
src/commands/community/sales/remove.ts
src/commands/defi/watchlist/view.ts
src/commands/defi/watchlist_slash/view.ts
src/commands/profile/profile.ts
src/events/interactionCreate.ts
src/utils/common.ts
src/utils/discordEmbed.ts

- refactor button interaction filter

chore: author filter

---

src/commands/community/quest/daily.ts
src/commands/community/quest/index.ts
src/commands/community/quest_slash/daily.ts
src/commands/community/quest_slash/index.ts
src/commands/index.ts
src/events/interactionCreate.ts
src/types/api.ts
src/utils/common.ts

-   [x] UI for quest command
`$quest daily`
`/daily`

feat: daily quests (not bind api yet)

---

src/adapters/config.ts
src/commands/config/starboard/index.ts
src/commands/config/starboard/set-start-stop.ts
src/events/messageReactionAdd.ts
src/types/api.ts
src/types/common.ts

Flow: 
- Store start_message_id and stop_message_id in backend
- Use channel.messages.fetch(options: {after: start_message_id, before: stop_message_id}}
- The result is not correct 100% -> i filter again with 2 array
https://www.loom.com/share/e64332bb2c1347b6b5e88efa04426452

feat: sb start stop conversation

---

src/adapters/community.ts
src/commands/community/quest/daily.ts
src/commands/community/quest_slash/daily.ts
src/utils/common.ts

-   [x] Bind data quest command
`/daily`

feat: bind quest data

---

src/events/messageReactionAdd.ts
src/events/messageReactionRemove.ts
src/utils/discordEmbed.ts

-   [x] chore: reduce reaction number when remove reaction
[Screencast from 14-10-2022 21:10:38.webm](https://user-images.githubusercontent.com/104887632/195868132-278b7bff-f805-419b-8078-c4dfa06f9489.webm)

chore: reduce reaction number when remove reaction

---

src/adapters/usage_stats.ts
src/commands/index.ts
src/utils/wrapError.ts

- usage log now can tell if command failed
->**Error must be thrown to be logged as failed**

chore: log usage

---

src/adapters/usage_stats.ts
src/commands/index.ts

- Added timer to benchmark execution time of commands
- Failed commands may take too long to timeout so they will not be benchmarked

chore: benchmark cmd

---

src/adapters/config.ts
src/commands/config/starboard/index.ts
src/commands/config/starboard/list.ts
src/commands/config/starboard/set-chat.ts
src/types/api.ts
src/utils/common.ts

-   [x] chore: refactor sb set chat
https://www.loom.com/share/ffc95d47cdd9483d8c9a5da92de953e7

chore: refactor sb set chat

---

src/adapters/community.ts
src/commands/community/feedback/index.ts
src/commands/community/feedback_slash/index.ts
src/commands/index.ts
src/types/api.ts

-`$feedback <optional_command> <description>`, the feedback will be sent to a feedback channel
https://user-images.githubusercontent.com/84314071/196651645-2b921f3b-58c3-45b2-8eb0-b2bf34016553.mov

feat: feedback

---

src/commands/community/feedback_slash/index.ts
src/types/api.ts

- change feedback slash command permission to public

chore: fix feedback

---

src/commands/community/feedback/index.ts
src/commands/config/joinleave/index.ts
src/commands/config/joinleave/info.ts
src/commands/config/joinleave/remove.ts
src/commands/config/joinleave/set.ts
src/types/api.ts
src/utils/constants.ts

- change all `join-leave` to `joinleave`
- update gitbook link

chore: update jl

---

src/commands/defi/ticker/default.ts
src/types/api.ts
src/utils/CacheManager.ts

-   [x] Remove related cache after use `$ticker default`

fix: default ticker

---

src/commands/community/invite/aggregation.ts
src/commands/community/invite/config.ts
src/commands/community/prune/remove.ts
src/commands/community/prune/whitelist.ts
src/commands/community/prune/without.ts
src/commands/community/sales/remove.ts
src/commands/community/sales/track.ts
src/commands/community/verify/set.ts
src/commands/community/vote/set.ts
src/commands/community/vote/top.test.ts
src/commands/config/defaultRole/set.ts
src/commands/config/defaultRole_slash/set.ts
src/commands/config/joinleave/set.ts
src/commands/config/welcome_slash/set.ts
src/commands/profile/profile.ts
src/types/api.ts
src/utils/commands.test.ts
src/utils/commands.ts
src/utils/constants.ts

-   [x] Use regex to check in `parseDiscordToken`
-   [x] Rename `id` to `value` for more generic meaning
-   [x] Add test for `parseDiscordToken`
-   [x] (not related) increase timeout for `top.test.ts`

refactor: parseDiscordToken

---

package.json
src/utils/commands.test.ts
src/utils/commands.ts
src/utils/constants.ts
yarn.lock

-   [x] Fix native emoji check

fix: native emoji check

---

src/adapters/config.ts
src/commands/config/starboard/index.ts
src/commands/config/starboard/list.ts
src/commands/config/starboard/remove.ts
src/commands/config/starboard/set-chat.ts
src/commands/config/starboard/set.ts
src/types/api.ts
src/types/common.ts

-   [x] Sb remove conversation
-  [x] Standardize sb command
$sb remove
- $sb romove
https://www.loom.com/share/cab0a374eb084ae6b82541f1f87b76a0
- Standardize sb command

feat: sb remove conversation

---

src/adapters/config.ts
src/commands/community/quest/daily.ts
src/commands/config/starboard/blacklist/index.ts
src/commands/config/starboard/blacklist/list.ts
src/commands/config/starboard/blacklist/remove.ts
src/commands/config/starboard/blacklist/set.ts
src/commands/config/starboard/index.ts
src/types/api.ts
src/types/common.ts

-   [x] sb blacklist channel repost
https://www.loom.com/share/9fb2bc29a3884c0caa4947f26c30a369

feat: sb blacklist channel repost

---

src/commands/config/starboard/blacklist/index.ts
src/commands/config/starboard/blacklist/set.ts

-   [x] fix help msg of sb blacklist

chore: fix help msg of sb blacklist

---

src/commands/community/prune/inactive.ts
src/commands/community/prune/index.ts
src/commands/community/prune/remove.ts
src/commands/community/prune/whitelist.ts
src/commands/community/prune/without.ts
src/commands/community/prune_slash/inactive.ts
src/commands/community/prune_slash/without.ts
src/commands/community/quest/daily.ts
src/types/api.ts

- Update text messages for `prune`
- Add custom day to `prune inactive`

chore: update prune

---

src/commands/index.ts
src/types/api.ts

- Chaned vote reminding rate to 10% (previously 30%)

chore: vote reminder rate

---

src/commands/community/quest/index.ts
src/commands/community/quest_slash/index.ts
src/types/api.ts

-   [x] Remove `experimental` and `onlyAdministrator` check for quest command

chore: remove experimental and admin check for quest command

---

src/utils/commands.test.ts
src/utils/commands.ts
src/utils/constants.ts

-   [x] Add nickname regex to parse

feat: add parse nickname discord

---

src/commands/community/prune/inactive.ts
src/commands/community/prune/without.ts
src/commands/community/prune_slash/inactive.ts
src/utils/wrapError.ts

- Fixed error occurs when command with no subcommand like `/feedback` failed

chore: fix cmd log

---

src/commands/defi/offchain_tip_bot/balance.ts

- Seems like msg.author not working

fix: bals author id

---

src/adapters/config.ts
src/commands/config/poe/twitter/block/index.ts
src/commands/config/poe/twitter/block/list.ts
src/commands/config/poe/twitter/block/remove.ts
src/commands/config/poe/twitter/index.ts
src/utils/TwitterStream.ts

New twitter blacklist commands: `$poe twitter block <user>` or `$poe twitter block <action>`
-   [x] Block a user: `$poe twitter block <@username or ID>`
-   [x] Unblock a user: `$poe twitter block remove <@username or ID>`
-   [x] Show blacklist: `$poe twitter block list`
**Media**

feat: twitter blacklist commands

---

src/commands/config/starboard/remove.ts
src/types/api.ts

chore: update sb remove brief

---

src/commands/defi/offchain_tip_bot/tip.ts
src/types/api.ts

fix: handle api error

---

src/adapters/defi.ts
src/commands/community/nft/query.ts
src/commands/community/vote/top.test.ts
src/commands/defi/offchain_tip_bot/withdraw.ts
src/types/api.ts
src/types/defi.ts

feat: apply logic withdraw

---

src/commands/config/reactionRole/list.ts
src/commands/config/reactionRole/remove.ts
src/commands/config/reactionRole/set.ts
src/types/api.ts
src/types/common.ts
src/utils/common.ts

- Changed `$rr set` and `$rr remove` argument from `message_id` to `message_link`
- Refactor `$rr list`
New argument

chore: rework rr

---

src/commands/config/reactionRole/list.ts

- Update `$rr list` UI, grouping roles by message

chore: update rr UI

---

src/commands/community/feedback_slash/index.ts
src/commands/community/prune_slash/inactive.ts
src/commands/community/prune_slash/without.ts
src/commands/community/top_slash.ts
src/commands/community/verify_slash/set.ts
src/commands/config/defaultRole_slash/set.ts
src/commands/config/levelRole_slash/remove.ts
src/commands/config/levelRole_slash/set.ts
src/commands/config/log_slash/set.ts
src/commands/config/welcome_slash/message.ts
src/commands/config/welcome_slash/set.ts
src/commands/defi/ticker_slash/ticker_slash.ts
src/commands/defi/watchlist_slash/add-nft.ts
src/commands/defi/watchlist_slash/add.ts
src/commands/defi/watchlist_slash/remove-nft.ts
src/commands/defi/watchlist_slash/remove.ts
src/commands/help_slash.ts

- Update slash command description

chore: update slash example

---

src/commands/defi/tip.ts

chore: lock tip cmd

---

src/events/interactionCreate.ts
src/utils/ConversationManager.ts

-   [x] Add timeout mechanic to ConversationManager

chore: add timeout to conversation manager

---

src/utils/TwitterStream.ts

_Reason_: No need to delete rule if there is a `ruleId`, this will unnecessarily delete & create new ruleId (with same rule value) everytime new bot version is released no matter what

fix: twitter upsert rule

---

src/commands/config/poe/twitter/block/list.ts
src/types/api.ts

-   [x] Response message if twitter blacklist is empty
**Media**

fix: empty blacklist

---

src/commands/community/swap/index.ts

-   [x] Rename the link from trade to swap
-   [x] Remove hard code wallet value

chore: rename trade to swap

---

src/utils/ChannelLogger.ts

fix: dm check logic

---

src/commands/community/gm_slash/index.ts
src/commands/community/gm_slash/info.ts
src/commands/community/gm_slash/set.ts
src/commands/community/gm_slash/streak.ts
src/commands/community/stats_slash.ts
src/commands/index.ts

-  Fix slash command for `stat` and `gm`

chore: fix slash

---

src/commands/defi/balances.ts
src/commands/defi/deposit.ts
src/commands/defi/tip.ts
src/commands/defi/withdraw.ts
src/commands/index.ts

-   [x] Move tipoff, wdoff, baloff, depoff -> tip, wd, bal, dep
-  [x] Unlock withdraw, tip, deposit
$bal
$wd
$tip

chore: move tip wd bal to offchain

---

src/commands/defi/tip.ts
src/commands/defi/withdraw.ts
src/errors/APIError.ts

-   [x] Show specific error from API to user
Before:
After:

chore: show error api

---

src/utils/TwitterStream.ts

-   [x] Error logging for twitter stream

chore: twitter stream error logging

---

src/commands/defi/tip.ts

-   [x] Handle tip all case 
https://www.loom.com/share/222b2a369e704c57a42e7651c29ff46f

chore: handle tip all

---

src/commands/defi/airdrop.ts
src/events/interactionCreate.ts

chore: airdropoff to airdrop

---

src/commands/defi/tip.ts

chore: handle tip role

---

src/commands/config/poe/twitter/block/index.ts
src/utils/constants.ts

-   [x] Change the block syntax from username/id to twitter profile link

fix: twitter

---

src/commands/config/defaultRole/set.ts

-   [x] Remove default role unnecessary check for `isId`

fix: default role

---

README.md

chore: add credit section

---

src/adapters/defi.ts
src/commands/defi/tip.ts

-   [x] Tip multiple roles
-  [x] Tip each
Tip multiple roles
Tip each
Tip users

feat: tip multiple role and each

---

src/commands/config/nftRole_slash/index.ts
src/commands/config/nftRole_slash/list.ts
src/commands/config/nftRole_slash/remove.ts
src/commands/config/nftRole_slash/set.ts
src/commands/config/reactionRole_slash/index.ts
src/commands/config/reactionRole_slash/list.ts
src/commands/config/reactionRole_slash/remove.ts
src/commands/config/reactionRole_slash/set.ts
src/commands/index.ts
src/types/api.ts
src/utils/discordEmbed.ts

-   [x] feat: nr & rr slash command

feat: nr rr slash command

---

src/commands/community/nft/add.ts
src/commands/community/nft/config.ts
src/commands/community/nft/integrate.ts
src/commands/community/nft/list.ts
src/commands/community/nft_slash/add.ts
src/commands/community/nft_slash/config.ts
src/commands/community/nft_slash/index.ts
src/commands/community/nft_slash/integrate.ts
src/commands/index.ts
src/types/common.ts
src/utils/discordEmbed.ts

- Remove author filter for pagination
- slash command for `$nft add / integrate / config twitter-sale`

chore: nft slash

---

.github/workflows/test.yml
LICENSE
README.md
package.json
src/types/api.ts
yarn.lock

-   [x] Add required node version
-   [x] Add badges to README
-   [x] Add GNU LICENSE

chore: more update to readme

---

src/utils/TwitterStream.ts

-   [x] Skip handling tweet if it has over 7 mentions

fix: skip spam tweet

---

src/commands/defi/airdrop.ts
src/commands/defi/tip.ts

-   [x] Convert to usd for airdrop and tip
airdrop
tip

chore: convert price for airdrop and tip

---

src/commands/profile/profile.ts

-   [x] Add buttons to back to My Profile view in $profile command when user has no nfts

fix: profile cannot back to profile

---

src/adapters/config.ts
src/commands/config/starboard/list.ts
src/types/api.ts
src/utils/common.ts

-   [x] Add new UI for starboard list (cover mobile case)

fix: mobile view starboard

---

src/adapters/defi.ts
src/commands/defi/airdrop.ts
src/commands/defi/tip.ts

-   [x] Fix airdrop convert to amount usd
-  [x] Update tip help menu
-  [x] Change syntax tip (remove comma, function parseRecipients only use for tip offchain and old tip, cuz disable old tip so wont affect)
Airdrop
Tip

chore: update tip syntax

---

src/commands/community/feedback/index.ts
src/commands/community/feedback_slash/index.ts
src/utils/common.ts

-   [x] Add new buttons to feedback command
`$feedback something`

chore: add new buttons for feedback command

---

src/commands/defi/balances.ts

-   [x] remove zero balance
Before:
After:

fix: remove zero balance

---

package.json
src/adapters/defi.ts
yarn.lock

chore: support time alias

---

src/events/guildMemberAdd.ts

fix: unknow chanel

---

src/adapters/defi.ts
src/commands/defi/tip.ts

-   [x] fix tip role exceed maximum length msg
Bug:
Fix:

fix: tip role maximum length msg

---

src/commands/defi/watchlist/view.ts
src/commands/defi/watchlist_slash/view.ts
src/commands/index.ts
src/utils/canvas.ts

**Media**
https://user-images.githubusercontent.com/34529672/200528739-f27ef5ed-67d3-447c-b6c1-a35bf30b507c.mp4

feat: cache wl images

---

src/commands/defi/tip.ts
src/types/api.ts

-   [x] fix add usd amount tip

fix: add usd amount tip

---

src/adapters/community.ts
src/commands/community/feedback/index.ts
src/env.ts
src/events/interactionCreate.ts

-   [x] the public feedback flow (without the view feedback list feature)
https://user-images.githubusercontent.com/25856620/200555652-7684b6d7-dccd-4392-82fb-203fa864cb50.mp4

feat: bind feedback api

---

src/commands/community/sales/index.ts
src/commands/help.ts
src/commands/help_slash.ts

-   [x] Small tweak to help menu
**Media**

chore: help menu tweak

---

src/events/guildMemberAdd.ts

- Remove embed wrapper from welcome message

chore: update welcome msg

---

src/commands/defi/ticker/ticker.ts
src/commands/defi/ticker_slash/ticker_slash.ts
src/commands/defi/watchlist/add.test.ts
src/commands/defi/watchlist/add.ts
src/events/interactionCreate.ts

- `Add to watchlist` button for `$ticker`
- Fixed vote reminder embed for slash commands

chore: update wl

---

src/adapters/community.ts
src/commands/community/feedback/index.ts
src/commands/community/feedback_slash/index.ts
src/events/interactionCreate.ts

-   [x] Feedback list
`$feedback something`
https://user-images.githubusercontent.com/25856620/200844446-dfa80574-f380-4595-8f25-06ab107f34ca.mp4

feat: feedback list

---

src/commands/defi/watchlist/view.ts

-   [x] Wrap error when switching view in watchlist
`$wl view` then click button

fix: wrapError wl nft when switching view

---

src/commands/help.ts

-   [x] Minor text fix in help example

fix: minor edit help example

---

src/events/interactionCreate.ts

-  Add daily quest reminder every 24h

feat: quest reminder

---

src/commands/config/reactionRole/list.ts
src/commands/config/reactionRole/remove.ts
src/commands/config/reactionRole/set.ts
src/commands/config/reactionRole_slash/list.ts
src/utils/common.ts

-   [x] Show empty list when message of reaction role is deleted

fix: deleted message in reaction role

---

src/commands/defi/airdrop.ts

-   [x] Format airdrop duration

fix: airdrop duration format

---

src/adapters/defi.ts
src/commands/defi/ticker/compare.ts
src/commands/defi/ticker/compare_fiat.ts
src/types/api.ts
src/utils/canvas.ts

-   [x] `$ticker`: support fiat (sgd / usd / eur / gbp)
**Media**

feat: ticker - support fiat

---

src/adapters/community.ts
src/commands/community/nft/query.ts
src/commands/community/nft/ticker.ts
src/types/api.ts

refactor: nft activity

---

src/commands/community/nft/query.ts

-   [x] use wrap error when switching view

fix: nft query crash

---

src/commands/community/nft/query.ts

chore: sold format

---

src/adapters/defi.ts
src/commands/defi/tip.test.ts
src/commands/defi/tip.ts

-   [x] Tip in a channel
-   [x] Filter out users that are bot when tipping

feat: tip in a text channel

---

src/adapters/defi.ts
src/commands/defi/tip.test.ts
src/commands/defi/tip.ts
src/index.ts

feat: tip by online status

---

src/events/messageDelete.ts

-   [x] Fix rr config when delete msg (remove fetch msg because after deleting cannot fetch the msg)
https://www.loom.com/share/0c21b8883ef2417ea0a91a018545d63f

fix: remove fetch delete msg

---

src/adapters/defi.ts
src/commands/defi/tip.test.ts
src/commands/defi/tip.ts
src/errors/DiscordWalletTransferError.ts

-   [x] Refactor tip syntax parsing
-   [x] `online` modifier with channel
-   [x] `online` modifier with role
-   [x] Update tip message
-   [x] Update test
`$tip online #general 1 eth` -> means tip to anyone currently online and is in channel `general`
`$tip #general online 1 eth` -> same as above, just switch place
`$tip online #private 1 eth` -> anyone online and able to view channel `private`
`$tip online @peeps 1 eth` -> same as channel but for role

feat: online combine with channels and roles

---

src/adapters/defi.ts
src/commands/defi/ticker/compare.ts
src/commands/defi/watchlist/add.test.ts
src/commands/defi/watchlist/add.ts

chore: wl fiat

---

src/commands/community/feedback/index.ts
src/types/api.ts

-   [x] Scope feedback buttons to author

fix: feedback buttons scope author

---

src/adapters/defi.ts
src/index.ts

-   [x] Enable tipping in voice channel
https://user-images.githubusercontent.com/25856620/203033820-2d7bdbf3-32ba-4130-b17f-2bc1fecbd6ab.mp4

feat: voice tip

---

src/adapters/defi.ts
src/types/api.ts

-   [x] Hot fix the tip voice channel

fix: invalid recipients

---

src/adapters/community.ts
src/commands/community/feedback/index.ts

fix: feedback

---

src/adapters/defi.ts
src/commands/defi/ticker/compare.ts
src/commands/defi/ticker/compare_fiat.ts
src/commands/defi/ticker/ticker.ts
src/commands/defi/watchlist/view.ts
src/types/canvas.ts
src/utils/canvas.ts
src/utils/common.ts
src/utils/defi.ts

fix: wl - fiat icons

---

src/adapters/defi.ts
src/commands/defi/statements.ts
src/commands/defi/tip_bot_slash/statements.ts
src/commands/index.ts
src/types/api.ts
src/utils/common.ts

-   [x] Statements cmd
https://www.loom.com/share/fb5cec8c86164e759d8dca2e85264cef

feat: statements cmd

---

src/commands/defi/watchlist/view.ts

-   [x] Revert back to the old icon look

fix: watchlist icon remove border

---

src/commands/defi/watchlist_slash/view.ts
src/types/api.ts

fix: watchlist slash collector crash

---

src/adapters/config.ts
src/commands/community/gm/config.ts
src/commands/community/gm_slash/set.ts
src/types/api.ts

feat: config msg emoji sticker gm

---

src/commands/defi/statements.ts
src/commands/defi/tip_bot_slash/statements.ts

-   [x] fix statements cmd when data null

fix: fix statement data null

---

src/commands/community/gm/config.ts

-   [x] Edit $gm config help message

chore: edit gm config

---

src/commands/community/gm/config.ts
src/utils/common.ts

-   [x] Fallback in gm message

fix: fallback gm

---

src/adapters/community.ts
src/commands/community/feedback/index.ts

-   [x] Feedback discord id get api
-   [x] Change UI a bit
**Media**

fix: feedback discord id

---

src/commands/community/prune/inactive.ts
src/commands/community/prune/without.ts

-   [x] Remove the user check in prune

chore: remove prune limit

---

src/adapters/config.ts
src/commands/config/poe/twitter/index.ts
src/commands/config/poe/twitter/stats.ts
src/types/api.ts
src/utils/TwitterStream.ts
src/utils/canvas.ts

feat: twitter stats (leaderboard)

---

src/adapters/config.ts
src/commands/config/moniker/index.ts
src/commands/config/moniker/list.ts
src/commands/config/moniker/remove.ts
src/commands/config/moniker/set.ts
src/commands/config/moniker_slash/index.ts
src/commands/config/moniker_slash/list.ts
src/commands/config/moniker_slash/remove.ts
src/commands/config/moniker_slash/set.ts
src/commands/defi/tip_bot_slash/statements.ts
src/commands/index.ts
src/types/api.ts
src/utils/common.ts

-   [x] moniker command
set moniker
list moniker
remove moniker

feat: moniker command

---

src/events/messageReactionAdd.ts
src/types/api.ts

-   [x] Fix starboard fetching unknown message

fix: starboard fetch unknown message

---

src/commands/config/defaultRole/info.ts
src/commands/config/defaultRole/remove.ts
src/commands/config/defaultRole/set.ts
src/commands/config/defaultRole_slash/info.ts
src/commands/config/defaultRole_slash/remove.ts
src/commands/config/defaultRole_slash/set.ts
src/errors/CommandArgumentError.ts

-   [x] Refactor default role command (show info after set/remove)
**Media**

refactor: default role

---

src/commands/defi/statements.ts
src/commands/defi/tip_bot_slash/statements.ts

-   [x] Statement all tokens 
Command $
Slash command

chore: add statement all token

---

src/commands/defi/balances.ts
src/types/api.ts

-   [x] Fix balance data api is null

fix: balance null

---

src/adapters/defi.ts
src/commands/defi/airdrop.ts
src/commands/defi/tip_bot_slash/airdrop.ts
src/commands/defi/tip_bot_slash/withdraw.ts
src/commands/defi/withdraw.ts
src/commands/index.ts

- migrate `airdrop` and `withdraw` to slash cmd

chore: migrate slash tipbot

---

src/commands/community/gm/config.ts
src/commands/config/reactionRole/index.ts
src/commands/config/reactionRole/set.ts
src/commands/config/starboard/index.ts
src/commands/config/starboard/set-chat.ts
src/commands/config/starboard/set.ts
src/errors/InternalError.ts
src/types/api.ts
src/utils/emoji.ts

-   [x] Add unsupported message for starboard
-   [x] Add unsupported message for reaction role
-   [x] Add unsupported message for gm

chore: add message for unsupported external emoji

---

src/adapters/defi.ts
src/commands/defi/tip.test.ts
src/commands/defi/tip.ts
src/types/api.ts

chore: parse moniker in tip

---

src/adapters/defi.ts
src/commands/defi/airdrop.ts
src/commands/defi/tip_bot_slash/airdrop.ts
src/commands/index.ts

chore: airdrop moniker

---

src/commands/community/nft/stats.ts
src/utils/common.ts

chore: nft stat all chains

---

src/utils/emoji.ts

-   [x] Fix external emoji check

fix: external emoji check

---

src/commands/defi/token/add.ts
src/commands/defi/token/addCustom.ts
src/commands/defi/token/default.ts
src/commands/defi/token/info.ts
src/commands/defi/token/list.ts
src/commands/defi/token/remove.ts
src/commands/defi/token_slash/add.ts
src/commands/defi/token_slash/addCustom.ts
src/commands/defi/token_slash/default.ts
src/commands/defi/token_slash/index.ts
src/commands/defi/token_slash/info.ts
src/commands/defi/token_slash/list.ts
src/commands/defi/token_slash/remove.ts
src/commands/index.ts

- migrate `$token` to slash cmd

chore: migrate slash token

---

src/commands/community/sales/list.ts
src/commands/community/sales/remove.ts
src/commands/community/sales/track.ts
src/commands/community/sales_slash/index.ts
src/commands/community/sales_slash/list.ts
src/commands/community/sales_slash/remove.ts
src/commands/community/sales_slash/track.ts
src/commands/index.ts
src/index.ts

- Migrate `sales` commands to slash
- Changed discord slash API request body

chore: migrate slash sales

---

src/commands/defi/tip.ts
src/commands/defi/tip_bot_slash/tip.ts
src/types/api.ts
src/types/defi.ts

-   [x] tip with message and img

feat: tip with message and img

---

src/commands/defi/withdraw.ts

chore: remove tx fee

---

src/commands/defi/withdraw.ts

fix: fix amount wd

---

src/commands/config/poe/twitter/stats.ts

-   [x] Render text version of twitter stats command
`$poe twitter stats`

feat: simplify ui of twitter stats

---

src/commands/defi/tip.ts
src/commands/defi/tip_bot_slash/tip.ts

chore: update tip help menu

---

src/commands/defi/tip.ts
src/commands/defi/tip_bot_slash/tip.ts

-   [x] edit response tip with case msg and image
-  [x] fix tip slash cmd work with msg 

chore: edit response tip with case msg and image

---

src/commands/config/poe/twitter/list.ts
src/commands/config/poe/twitter/remove.ts
src/commands/config/poe/twitter/set.ts
src/commands/config/poe/twitter/stats.ts
src/commands/config/poe_slash/index.ts
src/commands/config/poe_slash/twitter/index.ts
src/commands/config/poe_slash/twitter/list.ts
src/commands/config/poe_slash/twitter/remove.ts
src/commands/config/poe_slash/twitter/set.ts
src/commands/config/poe_slash/twitter/stats.ts
src/commands/index.ts

- migrate `poe twitter` to slash

chore: migrate slash poe

---

src/adapters/config.ts
src/adapters/defi.ts
src/commands/config/moniker/list.ts
src/utils/common.ts

-   [x] moniker list with default moniker
-  [x] tip & airdrop with default moniker
- When users haven't setup moniker, will use default moniker 
- When users have setup moniker, will use their moniker

feat: default moniker

---

src/commands/defi/watchlist/add-nft.test.ts
src/commands/defi/watchlist/add-nft.ts
src/commands/defi/watchlist_slash/add-nft.ts
src/commands/defi/watchlist_slash/index.ts

-   [x] Update some error messages

chore: update error message

---

src/env.ts
src/events/messageCreate.ts
src/index.ts
src/producer.ts
src/types/common.ts
src/utils/Queue.ts

- send discord message to kafka queue

feat: add kafka queue

---

src/commands/defi/ticker/compare.ts
src/commands/defi/ticker/compare_fiat.ts
src/commands/defi/ticker/ticker.ts
src/commands/defi/watchlist/add.ts
src/commands/defi/watchlist/remove.ts
src/utils/defi.ts

fix: parse ticker args

---

src/adapters/defi.ts
src/commands/defi/tip.test.ts
src/commands/defi/tip.ts

-   [x] support " and non " in message tip cmd

chore: improve parse msg tip

---

src/adapters/community.ts
src/adapters/config.ts
src/adapters/defi.ts
src/adapters/profile.ts
src/adapters/usage_stats.ts
src/utils/constants.ts

chore: update routes

---

src/adapters/defi.ts
src/commands/defi/deposit.ts
src/commands/defi/tip.test.ts
src/commands/defi/tip.ts
src/commands/defi/withdraw.ts

- Update tip bot err response ref: https://www.notion.so/console-labs/Tip-bot-command-response-error-3f3440973c984ecea107ac6080b65815

chore: err response tip

---

src/commands/defi/tip.ts
src/types/api.ts

-   [x] update tip moniker msg response
**Request**

chore: update tip moniker msg response

---

src/adapters/defi.ts
src/commands/defi/airdrop.ts
src/commands/defi/statements.ts
src/commands/defi/tip_bot_slash/statements.ts
src/events/interactionCreate.ts
src/utils/defi.ts

- update err response for `statements` and `airdrop`

chore: update response tipbot

---

src/commands/defi/airdrop.ts
src/commands/defi/tip.test.ts
src/events/interactionCreate.ts

chore: reimport kafka

---

src/adapters/defi.ts
src/commands/defi/tip_bot_slash/airdrop.ts
src/errors/BaseError.ts
src/utils/wrapError.ts

- Add check token before airdrop
- Update error response handling

chore: fix airdrop response

---

src/commands/config/defaultRole/info.ts
src/commands/config/defaultRole/remove.ts
src/commands/config/defaultRole/set.ts
src/commands/config/reactionRole/list.ts
src/commands/config/reactionRole/remove.ts
src/commands/config/reactionRole/set.ts
src/commands/config/reactionRole_slash/remove.ts
src/errors/CommandNotAllowedToRunError.ts
src/utils/emoji.ts

-   [x] Update response for $dr & $rr commands

chore: update response for rr & dr features

---

src/adapters/community.ts
src/commands/community/nft/query.ts
src/commands/profile/profile.ts

-   [x] Update query for get nft detail api

fix: nft ticker suggestion

---

src/adapters/defi.ts
src/commands/defi/deposit.ts
src/commands/defi/statements.ts
src/commands/defi/tip.test.ts
src/commands/defi/tip.ts
src/commands/defi/tip_bot_slash/statements.ts
src/commands/defi/tip_bot_slash/withdraw.ts
src/commands/defi/withdraw.ts
src/utils/defi.ts

- update tipbot responses
- add balance check before tip
- move functions from `util` to `adapter` to avoid circular import

chore: update tipbot response

---

src/commands/community/gm/streak.ts
src/commands/community/prune/inactive.ts
src/commands/community/prune/remove.ts
src/commands/community/prune/whitelist.ts
src/commands/community/prune/without.ts
src/commands/community/prune_slash/inactive.ts
src/commands/community/prune_slash/without.ts

- Update response for `gm` and `prune`

chore: update cmd response

---

src/commands/defi/tip.test.ts
src/commands/defi/tip.ts

chore: fix tip

---

src/utils/common.ts

fix: nft stats update arb logo

---

src/commands/defi/watchlist/add-nft.ts
src/commands/defi/watchlist/add.ts
src/commands/defi/watchlist/remove-nft.test.ts
src/commands/defi/watchlist/remove-nft.ts
src/commands/defi/watchlist/view.ts
src/commands/defi/watchlist_slash/index.ts

chore: update wl response

---

src/adapters/community.ts
src/commands/community/nft/stats.ts
src/utils/common.ts

-  [x] sort nft stats by collection count
-  [x] Add missing emoji for okx

fix: sorted nft stats

---

src/commands/community/nft/query.ts

-   [x] Fix logic to get attribute icon from server

fix: missing attribute icon

---

src/adapters/defi-api.test.ts
src/adapters/defi.test.ts
src/adapters/defi.ts
src/commands/config/moniker_slash/set.ts

- add tests for some text parsers
- tip message support single quote `'`
- minor update to moniker ui

chore: test parser

---

src/events/guildCreate.ts

- fix bug sending msg when users block DM

chore: fix guild add msg

---

src/commands/community/sales/track.ts
src/commands/community/verify/set.ts

- fix commands dont give correct response

chore: update response

---

src/commands/config/reactionRole/list.ts
src/commands/config/starboard/blacklist/list.ts
src/commands/config/starboard/blacklist/remove.ts
src/commands/config/starboard/blacklist/set.ts
src/commands/config/starboard/list.ts
src/commands/config/starboard/remove.ts
src/commands/config/starboard/set-chat.ts
src/commands/config/starboard/set.ts

-   [x] Recheck reaction role response
-   [x] Update starboard command response

Chore/recheck on $rr & $sb command response

---

src/adapters/defi.ts
src/commands/defi/tip-onchain.ts
src/commands/defi/tip.ts
src/types/api.ts

-   [x] Ofchain tip command: `$tip <recipient> <amount> <token> [message] --onchain`
1. Enter command: `$tip @krafe#3445 0.1 ftm "love u sm" --onchain`
2. Bot DM

feat: tip onchain

---

src/commands/defi/tip-onchain.ts
src/types/api.ts

- Fix error - send `null` message

fix: tip onchain

---

src/adapters/config.ts
src/commands/config/daovote/index.ts
src/commands/config/daovote/set.ts
src/commands/index.ts
src/utils/common.ts

-   [x] config channel proposal
https://www.loom.com/share/8d296cced8304d26ab8ad4f7083db8f8

feat: config channel proposal

---

src/adapters/defi.ts
src/commands/defi/claim.ts
src/utils/common.ts

-   [x] Update onchain tipping + claim dm message format
**Media**

fix: tip onchain msg

---

src/adapters/fetcher.ts
src/commands/defi/claim.ts

fix: claim error msg

---

src/adapters/config.ts
src/commands/config/daovote/index.ts
src/commands/config/daovote/info.ts
src/commands/config/daovote/remove.ts
src/commands/config/daovote/set.ts
src/utils/common.ts

-   [x] delete and info config channel dao vote

feat: delete and info config channel dao vote

---

src/commands/config/daovote/info.ts

-   [x] change to emoji daovote info

chore: change to emoji daovote info

---

src/adapters/community.ts
src/commands/community/dao-voting/proposal.ts
src/commands/community/dao-voting/voting.ts
src/events/interactionCreate.ts
src/utils/common.ts

- Interact -> Send DM -> Collect proposal's data -> Create discussion channel (BE) -> Post proposal to interaction's channel
https://www.loom.com/share/6b5bcf86b2de4693a063c0aaa93d4219

feat: proposal posting interaction

---

src/commands/community/dao-voting/proposal.ts

- fix proposal condition checks

chore: fix proposal

---

src/commands/games/tripod/index.ts
src/utils/common.ts

- update $tripod to redirect user

chore: update tripod

---

src/commands/community/vote/index.test.ts
src/commands/community/vote/index.ts
src/commands/community/vote/vote_slash.ts
src/utils/common.ts

chore: update vote

---

src/commands/sendxp/index/processor.ts

chore: update sendxp ui

---

src/adapters/defi.ts
src/commands/balances/index/processor.ts
src/commands/balances/index/slash.ts
src/commands/balances/index/test.ts
src/commands/balances/index/text.ts
src/commands/claim/index.ts
src/commands/claim/index/processor.ts
src/commands/index.ts
src/commands/watchlist/view/processor.ts
src/errors/command-not-allowed.ts
src/handlers/discord/button.ts
src/listeners/discord/interactionCreate.ts
src/types/common.ts
src/utils/constants.ts

refactor: update balances cmd

---

src/adapters/community.ts
src/adapters/config.ts
src/commands/index.ts
src/commands/level-message/index.ts
src/commands/level-message/info/processor.ts
src/commands/level-message/info/text.ts
src/commands/level-message/remove/processor.ts
src/commands/level-message/remove/text.ts
src/commands/level-message/set/processor.ts
src/commands/level-message/set/text.ts
src/utils/common.ts

-   [x] levelmessage cmd
$lm set
$lm info
$lm remove

feat: levelmsg config text cmd

---

src/commands/level-message/index.ts

-   [x] fix help menu levelmessage

chore: fix help menu levelmessage

---

src/adapters/config.ts
src/commands/index.ts
src/commands/token-role/index.ts
src/commands/token-role/list/processor.ts
src/commands/token-role/list/slash.ts
src/commands/token-role/list/text.ts
src/commands/token-role/set/processor.ts
src/commands/token-role/set/slash.ts
src/commands/token-role/set/text.ts
src/utils/constants.ts

-   [x] Set token role config
-   [x] List token role config
- `$tr set @role 20.5 0x8798249c2E607446EfB7Ad49eC89dD1865Ff4273 eth`
- `$tr list`
- Set 
- List

feat: token role

---

src/commands/level-role/index.ts
src/commands/level-role/set/text.ts

-   [x] Update response level role feature

chore: update response level role

---

src/commands/level-message/remove/processor.ts

chore: fix ui

---

src/commands/sendxp/index/processor.ts

chore: fix sendxp

---

src/commands/top/index/processor.ts
src/commands/top/index/text.ts

chore: update top

---

src/commands/envelop/processor.ts

chore: add img

---

src/commands/dao-voting/voting/processor.ts
src/commands/daovote/set/text.ts

- add crypto holder check to proposal creating

chore: fix daovote

---

src/commands/daovote/set/text.ts

chore: fix vote set

---

src/commands/statements/index/processor.ts

-   [x] fix undefined token args

fix: undefined token args

---

src/adapters/config.ts
src/commands/index.ts
src/commands/xp-role/index.ts
src/commands/xp-role/list/processor.ts
src/commands/xp-role/list/slash.ts
src/commands/xp-role/list/text.ts
src/commands/xp-role/processor.ts
src/commands/xp-role/remove/processor.ts
src/commands/xp-role/remove/slash.ts
src/commands/xp-role/remove/text.ts
src/commands/xp-role/set/processor.ts
src/commands/xp-role/set/slash.ts
src/commands/xp-role/set/text.ts
src/types/api.ts
src/utils/constants.ts

-   [x] Text command `$xprole set, list, remove`
-   [x] Slash command `/xprole set, list, remove`
- Set
- List
- Remove

feat: xp role

---

src/commands/dao-voting/proposal/processor.ts
src/commands/dao-voting/voting/processor.ts
src/commands/daovote/info/text.ts
src/types/api.ts

chore: update daovote

---

src/commands/daovote/info/text.ts

chore: update dv

---

src/commands/watchlist/add/processor.ts
src/commands/watchlist/add/slash.ts
src/commands/watchlist/add/text.ts
src/types/api.ts

-   [x] Fix wl add message (no duplicated and support multiple symbols)
- $wl add ftm eth

fix: wl add message

---

Dockerfile

-   [x] @openseajs-stream support minimum node ver = 16.11.0

fix: upgrade node to 16.11.0

---

src/commands/nft/processor.ts
src/commands/nft/query/processor.ts
src/utils/common.ts

- Update tab soulbound
- Soulbound token will have `soulbound` next to rank

feat: soulbound token

---

src/adapters/defi.ts
src/env.ts
src/listeners/discord/ready.ts
src/listeners/paintswap/index.ts

fix: paintswap sales - update tweet format

---

package.json
src/clients/opensea-stream.ts
src/listeners/discord/ready.ts
src/listeners/opensea/index.ts
src/listeners/paintswap/index.ts
src/utils/common.ts
yarn.lock

fix: opensea stream

---

src/commands/deposit/index/processor.ts

**Media**
1. case not supported
2. case no more available contracts

fix: deposit error response

---

src/commands/airdrop/index/processor.ts

-   [x] Fix: Airdrop participants can be gt max entries

fix: airdrop max entries

---

src/commands/moniker/set/processor.ts

-   [x] add unsupport token error 

chore: add unsupport token error

---

src/adapters/defi.ts
src/commands/index.ts
src/commands/wallet/add/processor.ts
src/commands/wallet/add/slash.ts
src/commands/wallet/add/text.ts
src/commands/wallet/index.ts
src/commands/wallet/remove/processor.ts
src/commands/wallet/remove/slash.ts
src/commands/wallet/remove/text.ts
src/commands/wallet/view/processor.ts
src/commands/wallet/view/slash.ts
src/commands/wallet/view/text.ts
src/ui/discord/embed.ts
src/utils/commands.ts
src/utils/common.ts

New `$wallet` commands
**Media**
1. view list
2. view details
3. add
4. remove

feat: wallet tracking

---

src/commands/tip/index/processor.test.ts
src/commands/tip/index/processor.ts
src/commands/tip/index/slash.test.ts
src/commands/tip/index/slash.ts
src/commands/tip/index/text.test.ts
src/commands/tip/index/text.ts

-  add confirmation for tip payload > 100 USD

feat: tip confirmation

---

src/commands/dao-voting/proposal/processor.ts
src/commands/index.ts
src/commands/proposal/untrack/processor.ts
src/commands/wallet/add/processor.ts
src/commands/wallet/remove/processor.ts
src/commands/wallet/view/processor.ts
src/commands/wallet/view/text.ts
src/types/api.ts
src/utils/common.ts

-   [x] `$wallet add`: button to view wallet details after successfully added
-   [x] `$wallet view`: drop-down to select wallet to view details
**Media**
1. $wallet add
2. $wallet view

feat: wallet UI update

---

src/commands/airdrop/index/processor.ts
src/commands/default-role/set/text.ts
src/commands/deposit/index/processor.ts
src/commands/gm/set/text.ts
src/commands/moniker/list/processor.ts
src/commands/moniker/set/processor.ts
src/commands/nft/integrate/processor.ts
src/commands/reaction-role/index.ts
src/commands/reaction-role/remove/processor.ts
src/commands/reaction-role/set/processor.ts
src/commands/reaction-role/set/slash.ts
src/commands/starboard/index.ts
src/commands/starboard/set/text.ts
src/commands/starboard/set_chat/text.ts
src/commands/statements/index/slash.ts
src/commands/statements/index/text.ts
src/commands/tip/index.ts
src/commands/tip/index/processor.ts
src/commands/token/default/processor.ts
src/commands/token/index.ts
src/commands/token/list/processor.ts
src/commands/withdraw/index/processor.ts
src/types/api.ts
src/utils/emoji.ts

- replace unicode emojis
- remove `token add-custom` texts

chore: update ui

---

src/commands/help/index/processor.ts
src/commands/wallet/view/processor.ts
src/utils/common.ts
src/utils/constants.ts
tests/assertions/discord.ts

feat: wallet in help cmd

---

src/commands/wallet/add/text.ts
src/commands/wallet/index.ts
src/commands/wallet/remove/text.ts
src/commands/wallet/view/text.ts

-   [x] Allow `$wallet` commands in DM

fix: wallet - allow DM

---

src/commands/wallet/view/processor.ts
src/utils/common.ts

refactor: wallet UI

---

src/adapters/config.ts
src/adapters/defi.ts
src/commands/index.ts
src/commands/mix-role/index.ts
src/commands/mix-role/list/processor.ts
src/commands/mix-role/list/slash.ts
src/commands/mix-role/list/text.ts
src/commands/mix-role/processor.ts
src/commands/mix-role/remove/processor.ts
src/commands/mix-role/remove/slash.ts
src/commands/mix-role/remove/text.ts
src/commands/mix-role/set/processor.ts
src/commands/mix-role/set/slash.ts
src/commands/mix-role/set/text.ts
src/errors/internal.ts
src/types/api.ts
src/types/community.ts
src/types/config.ts
src/ui/discord/button.ts
src/utils/common.ts
src/utils/constants.ts

- Text command: `$mixrole` / `$mr`
- Slash command: `/mixrole`
- Set
- List & Remove

feat: mix role

---

src/commands/mix-role/set/processor.ts

-   [x] Improve submit with defer update
-   [x] Fix handle error

fix: mix role handle error

---

src/commands/index.ts
src/listeners/discord/interactionCreate.ts
src/ui/discord/embed.ts

- 4% chance for partners ad to appear

feat: partner ad

---

src/commands/help/index/processor.ts
src/utils/constants.ts

chore: update help menu

---

tests/mocks/discord.ts

-   [x] Update mocks: `msg.guild` and `msg.client` for mockMessage

chore: update mocks

---

src/commands/nft/processor.ts
src/commands/nft/query/processor.ts

-   [x] Fix: ticker for nft details
**Media**

fix: nft details - ticker

---

src/commands/mix-role/set/processor.ts

-   [x] Add cancel button for every question
-   [x] Retry when user gives invalid arg
-   [x] Update error message
-   [x] Increase timeout to 3m
-   [x] Update styling for embed msg and confirm button
- `$mixrole set`

fix: mix role

---

package.json
src/adapters/defi.ts
src/commands/wallet/add/processor.ts
src/commands/wallet/view/processor.ts
src/utils/common.ts
yarn.lock

-   [x] $wallet: support solana

feat: wallet - support solana

---

src/adapters/profile.ts
src/commands/profile/index/processor.ts

-   [x] Fix $profile - nft tab

fix: profile - nft tab

---

src/commands/proposal/track/slash.ts
src/commands/proposal/track/text.ts

chore: update proposal

---

src/commands/poe/twitter/block/index.ts
src/commands/poe/twitter/block/remove/text.ts
src/commands/poe/twitter/index.ts
src/commands/proposal/set/text.ts
src/commands/proposal/track/processor.ts
src/commands/proposal/track/slash.ts
src/commands/proposal/track/text.ts
src/commands/starboard/blacklist/remove/text.ts
src/utils/constants.ts

https://www.notion.so/console-labs/Bug-from-Mochi-67c7098ca3424d87a5837ed165dbe274

fix: reported bugs

---

src/commands/deposit/index.ts
src/commands/deposit/index/process.test.ts
src/commands/deposit/index/slash.test.ts
src/commands/deposit/index/slash.ts
src/commands/deposit/index/text.test.ts
src/commands/deposit/index/text.ts
tests/mocks/discord.ts

chore: add test for deposit

---

src/commands/withdraw/index/processor.test.ts
src/commands/withdraw/index/slash.test.ts
src/commands/withdraw/index/slash.ts
src/commands/withdraw/index/text.test.ts
src/commands/withdraw/index/text.ts

-   [x] Test for withdrawal feature

chore: add test for withdrawal

---

src/commands/mix-role/set/processor.ts

-   [x] Fix mix role cancel failed
- `$mixrole set`

fix: mix role cancel

---

src/commands/profile/index/processor.ts

-   [x] `$profile`: hide faction XPs

fix: profile - hide faction xp

---

src/adapters/defi.ts
src/commands/alert/add/slash.ts
src/commands/alert/add/text.ts
src/commands/alert/index.ts
src/commands/alert/list/processor.ts
src/commands/alert/list/slash.ts
src/commands/alert/list/text.ts
src/commands/alert/remove/processor.ts
src/commands/alert/remove/slash.ts
src/commands/alert/remove/text.ts
src/commands/index.ts

-   [x] alert cmd
Media
https://www.loom.com/share/681f7813c7b3434b8cecd8499e159753

feat: alert cmd

---

src/commands/airdrop/index/processor.ts
src/commands/help/index/processor.ts
src/commands/nft/query/processor.ts
src/commands/nft/volume/processor.ts
src/commands/quest/daily/processor.ts
src/types/api.ts
src/utils/common.ts

chore: update emoji
