consolelabs/mochi-discord

- src/commands/config/reactionRole/list.ts
-  Show msg on `$rr list` data is empty
> chore: show not found msg on reaction role list null

- src/commands/community/nft/recent.ts
- `$nft recent` no longer has paging
> chore: update nft recent

- src/adapters/community.ts
- src/commands/community/nft/query.ts
- src/types/community.ts
-  Trait icons now query from API instead of hardcoded
> chore: update attribute icon

- src/adapters/community.ts
- src/commands/community/verify/create.ts
- src/commands/community/verify/index.ts
- src/commands/community/verify/list.ts
- src/commands/community/verify/remove.ts
- Add 2 commands for `$verify`
- `$verify list` shows currently config verify wallet channel
- `$verify remove` delete currently config verify wallet channel
- Rename `$verify wallet` to `$verify create`
In case config channel is empty
> feat: verify wallet cmds

- src/adapters/community.ts
- src/commands/community/nft/add.ts
- src/commands/community/nft/index.ts
- src/commands/community/nft/stats.ts
- src/utils/common.ts
- New cmd `$nft stats` to show total collections added
- `$nft add` error message change to color red
> feat: collection stats

- src/adapters/config.ts
- src/commands/community/nft/config.ts
- src/commands/community/nft/index.ts
- src/env.ts
- src/events/messageCreate.ts
- New cmd `nft config twitter-sale <consumer_key> <consumer_key_secret> <access_token> <access_token_secret>` to set twitter sales bot
- Webhook works with bot message only in `#sales-feed` channel
> feat: config twitter api

- src/adapters/config.ts
- src/commands/config/poe/twitter/index.ts
- src/commands/config/poe/twitter/list.ts
- src/commands/config/poe/twitter/remove.ts
- src/commands/config/poe/twitter/set.ts
- src/events/messageCreate.ts
- src/events/ready.ts
- src/types/InmemoryStorage.ts
- src/utils/GameSessionManager.ts
- src/utils/TwitterStream.ts
-   [x] Add Twitter watch event feature: user setup a twitter config in discord to detect for tweets that has hashtag or user mention -> log tweet if detected and post link into discord channel
-   In discord text channel, enter `$poe twitter set #general #some_hashtag`
-   Go to twitter, tweet something with the `#some_hashtag` hashtag
-   After a brief delay, discord bot will post the link of that tweet into the channel `#general`
**Edge cases**
Note: The discord bot restarts regularly every time the team release a new version, this PR introduces a new abstract class called `InmemoryStorage`: subclass extending `InmemoryStorage` will need to implement the `up` method which are responsible for restoring the state when the bot starts
-   Some edge …
> feat: twitter watch event

- src/adapters/defi.ts
- src/commands/defi/balances.ts
- src/commands/defi/tip.ts
- src/commands/defi/withdraw.ts
- src/errors/DiscordWalletTransferError.ts
- `withdraw` works in DM
- `bals` only works in servers but sends reply to DM
- activity log saves DM activities `guild_id` as `N/A`
> chore: update dm cmds

- src/adapters/profile.ts
- src/commands/profile/profile.ts
- src/env.ts
- src/types/profile.ts
- src/utils/common.ts
- src/utils/constants.ts
- src/utils/discordEmbed.ts
-   [x] Update My Profile view from canvas to textbase
-   [x] Add NFT collections view to $profile command
- Use the command `$profile` to check the new profile view
- Select My NFT from Selection Menu to view the user's NFT collections
> feat: add nft view for profile command

- src/commands/community/nft/query.ts
-   [x] Add select menu to choose other collections after nft query (has default symbol)
Same flow
> fix: add select menu to choose other collection after nft query

- src/commands/community/nft/query.ts
-   [x] Capitalize trait value when rendering nft embed
> fix: capitalize trait value when render nft embed

- src/adapters/config.ts
- src/adapters/fetcher.ts
- src/commands/config/defaultRole/index.ts
- src/commands/config/defaultRole/info.ts
- src/commands/config/defaultRole/remove.ts
- src/commands/config/defaultRole/set.ts
- src/commands/index.ts
- src/utils/commands.ts
- src/utils/constants.ts
-   [x] Enable and rework default role command
-   [x] Add a small feature in default role set command (support role id)
-   [x] Add a helper for parsing discord arg (`parseDiscordToken`) 
-   [x] Small tweak to the `jsonFetch` method
-   `$dr`
-   `$dr info`
-   `$dr set`
-   `$dr remove`
**Edge cases**
-   User passing in something that is not a role or role id (handled), image below
Handle invalid case
|Before|After|
|---|---|
|<img width="434" alt="Xnapper-2022-08-23-18 09 34" src="https://user-images.githubusercontent.com/25856620/186144401-408c6160-e7d8-475d-ab25-eda6ba6cfb5a.png">|<img width="434" alt="Xnapper-2022-08-23-18 04 56" src="https://user-images.githubusercontent.com/25856620/186144391-aa43bb87-6842-4440-9c9 …
> fix: rework default role command

- src/commands/config/poe/twitter/list.ts
- src/commands/config/poe/twitter/set.ts
- src/utils/TwitterStream.ts
-   [x] Rename `from_username` to `from_twitter` to match api response
-   [x] Add `from_twitter` value when running `up` when starting bot
-   [x] Add filter to remove empty string value when showing format message
> fix: from_twitter not adding to config

- src/commands/community/nft/query.ts
-   [x] Fallback to `{collectionName}#{token_id}` when token name is empty
-   [x] Include chain info
> fix: tweak nft query embed

- src/commands/community/nft/query.ts
- src/commands/profile/profile.ts
-   [x] Return null instead of empty embed (discord api error if embed empty)
-   [x] Reuse nft render method from nft query command in profile command
-   [x] Show specific error if user hasn't verify yet (a.k.a no wallet address -> can't use $profile command to view nfts)
> fix: profile command

- src/commands/community/gm/config.ts
- src/commands/community/gm/info.ts
-   [x] Restrict gm command to admin only
> fix: scope gm/gn command to admin

- src/events/messageCreate.ts
-   [x] Refuse to handling empty message (triggered when a user join guild)
> fix: refuse handling empty message

- src/commands/community/sales/list.ts
-   [x] Show collection name, chain name
`$sale list`
|Before|After|
|---|---|
|<img width="402" alt="Xnapper-2022-08-31-17 22 30" src="https://user-images.githubusercontent.com/25856620/187658059-80ab7e7e-19ac-448b-aac2-cb11b427a95e.png">|<img width="444" alt="Xnapper-2022-08-31-17 22 20" src="https://user-images.githubusercontent.com/25856620/187658046-430c789c-6de7-4be5-a5e1-6a37f917cb98.png">
> fix: sale tracker show collection and chain name

- .env-sample
- src/adapters/config.ts
- src/commands/defi/ticker_slash.ts
- src/commands/help_slash.ts
- src/commands/index.ts
- src/errors/CommandIsNotScopedError.ts
- src/events/interactionCreate.ts
- src/index.ts
- src/types/common.ts
- src/utils/commands.ts
- src/utils/constants.ts
- src/utils/discordEmbed.ts
- yarn.lock
Continue slash commands migration
**Media**
https://user-images.githubusercontent.com/34529672/188629300-2af280cb-d71a-48c6-a60d-d408b3be0352.mp4
> feat: slash commands migration

- src/commands/profile/profile.ts
-   [x] Use emoji with animated param set to true
Faction XP emojis are animated so we must set the 2nd param of `getEmoji` to true for it to render correctly
> fix: profile faction xp emoji

- src/commands/profile/profile.ts
-   [x] Decrease the faction xp length to 7 (10 will cause a new line in discord)
**Media**
We take 7 instead of 8 because safer value and won't cause newline
> fix: decrease faction xp length

- src/errors/CommandNotAllowedToRunError.ts
-   [x] running a disallowed-DM command in DM will pass `missingPermissions` as empty array, which will cause `empty field value` error
-> Check length
> fix: dm command crash issue

- src/commands/profile/profile.ts
- src/types/api.ts
-   [x] Hide some private info (user address, wallet, protocol, nft value) if msg author is not an admin 
-  As an not admin user, use command $profile / $profile @other-user -> the private info will be mask with ***
- As an admin user, use command $profile / $profile @other-user -> the private info will be fully shown
> fix: profile privacy logic

- src/commands/config/nftRole/list.ts
-   [x] Add chain id and embed link to explorer
```
$nr set <role> <amount> <address>
$nr list
```
**Edge cases**
-  In case of unidentifiable chain, chain id will not show
> chore: add chain id to nft role list

- src/commands/defi/watchlist/view.ts
- src/commands/defi/watchlist_slash/view.ts
> chore: default watchlist logic

- src/commands/defi/watchlist/add.ts
- src/commands/defi/watchlist/remove.ts
- src/commands/defi/watchlist/view.ts
- src/commands/defi/watchlist_slash/add.ts
- src/commands/defi/watchlist_slash/index.ts
- src/commands/defi/watchlist_slash/remove.ts
- src/commands/defi/watchlist_slash/view.ts
- src/commands/defi/watchlistcompact/view.ts
Handle wl error cases
1. duplicate item
2. symbol not exists/supported
2. symbol does not exist in user's wl
**Media**
> fix: handle wl error cases

- src/adapters/community.ts
- src/commands/community/vote.ts
- src/commands/config/welcome_slash/info.ts
- `$vote` now calls API to cache message data
- fixed `/welcome` response
> chore: cache upvote msg

- src/events/ready.ts
-   [x] fix: missing permission
- Server disable `ADMINISTRATOR` permission lead to when bot restart, event `ready` cannot get invites from this server.
Error:
> fix: missing permission

- src/commands/community/invite/aggregation.ts
-   [x] Because using the `parseDiscordToken` and check the `isUser` flag, we must use user format
`$invite aggregation`
> fix: invite aggregation

- src/errors/CommandArgumentError.ts
- src/events/ready.ts
-   [x] Change text of command argument error
-   [x] Presence text: change to use a dot as separator and change Watching -> Playing because it is the shortest word so the MATIC text can be viewed
> chore: small tweaks

- src/commands/community/vote/top.ts
-   [x] Remove only admin check
-   [x] Add `leaderboard` alias to vote top command
The bug
> fix: vote top admin

- src/commands/community/vote/top.ts
- src/utils/canvas.ts
-   [x] Leaderboard canvas right column are right aligned
-   [x] In `$vote top` command, if data is null default to empty array
`$vote top`
`$top`
|Before|After|
|---|---|
|<img width="499" alt="CleanShot 2022-09-21 at 16 31 06@2x" src="https://user-images.githubusercontent.com/25856620/191469471-ec78b852-6ead-448e-804b-29cadfef51cb.png">|<img width="491" alt="CleanShot 2022-09-21 at 16 31 20@2x" src="https://user-images.githubusercontent.com/25856620/191469565-0eb3d585-e9c4-473e-a2aa-b020bd63a880.png">|
> fix: leaderboard canvas

- src/events/guildCreate.ts
- Send intro msg when Mochi joins new guild
- Discord doesnt have `Moderation channel` so i will send to first text channel which Mochi can access, Mochi has administrator so it can see most of channel
> feat: send intro msg to new guild

- src/commands/index.ts
-   [x] Fix for case command such as $lr list, $gm info, ... not to show help cmd.
For case $nr, $nr set, .. still show help cmd without alert
> fix: fix case for list and info or streak

- src/commands/defi/token/info.ts
-   [x] Remove only admin for cmd token info
Error:
> fix: remove admin only

- src/commands/community/nft/query.ts
- src/commands/community/sales/remove.ts
- src/commands/config/globalxp.ts
- src/commands/defi/airdrop.ts
- src/commands/profile/profile.ts
- src/commands/profile/verify.ts
- src/events/interactionCreate.ts
- src/events/messageReactionAdd.ts
- src/utils/CommandChoiceManager.ts
- src/utils/discordEmbed.ts
-   [x] Fix editing an unknown/already deleted message crash the bot
** Solution **
Add catch clause wherever an `edit` or `editReply` method is called, because we cannot traceback the origin from the stacktrace
`$profile`
remove the message -> mochi bot will throw discord error
https://share.cleanshot.com/ihkoXr
> fix: edit unknown message

- src/commands/config/welcome_slash/index.ts
- src/events/guildMemberAdd.ts
- src/types/api.ts
- Update welcome UI
- Changed `welcome` to admin only
Non-admin trying to use `welcome`
New UI
> chore: update welcome

- src/commands/community/prune_slash/index.ts
- src/commands/community/verify_slash/index.ts
- src/commands/config/defaultRole_slash/index.ts
- src/commands/config/levelRole_slash/index.ts
- src/commands/config/log_slash/index.ts
- src/commands/config/welcome_slash/index.ts
- src/events/interactionCreate.ts
- src/types/common.ts
-   [x] Block user from using some admin-only commands
We can no longer hide/show slash commands for a specific role by code anymore. To achieve this, we have to setting this from the client side  `Settings > Integrations > Your application > Manage`
https://stackoverflow.com/questions/72339242/discord-js-trying-to-set-slash-command-permissions
- As a non-admin user use these commands `/defaultrole` | `/levelrole` | `/prune` | `/log` | `/welcome`
> fix: scope some slash commands to admin only

- src/commands/defi/watchlist/view.ts
- src/commands/defi/watchlist_slash/view.ts
-   [x] Temporary fix for `$wl view` when the message is deleted before the edit operation finishes.
`$wl view`
click NFT button to switch to nft view
quickly delete the message
the collector handler will run but now `msg` had been removed so Uknown Message exception is thrown
> fix: temp fix for watchlist view unknown message

- src/events/guildMemberAdd.ts
-   [x] fix: cannot send msg
**Description**
- When server add new bot, mochi will trigger event `guildMemberAdd` and send DM to bot, but discord does not allow a bot send DM to another bot
> fix: cannot send msg

- src/commands/community/nft/query.ts
- src/types/api.ts
- src/utils/common.ts
-   [x] Add floor price beside listing price nft query
`$nft neko 3400`
> fix: add floor price nft query

- src/commands/config/reactionRole/list.ts
- src/types/api.ts
-   [x] Show title and description when content of rr config message is empty
$rr list
Before: 
After:
> fix: show title and description when msg rr empty

- src/commands/config/reactionRole/list.ts
- src/types/api.ts
-   [x] Get tilte after fetchMsg
Bug
> fix: get title after get fetchMsg

- src/adapters/defi.ts
- src/commands/community/quest/daily.ts
- src/commands/defi/ticker.ts
- src/commands/defi/ticker_slash.ts
- src/env.ts
- src/events/guildMemberAdd.ts
- src/utils/canvas.ts
- src/utils/common.ts
Update quest commands
Reason: ticker API (`/api/v1/defi/market-chart`) does not send `discord_id` to server
=> Send `discord_id` when call the API
**Media**
> refactor: quests rewards

- src/commands/community/nft/ticker.ts
=> Solution: `marketplace = "-"` when data from api is `[] or null`
> fix: empty marketplace

- src/adapters/config.ts
- src/commands/config/joinleave/index.ts
- src/commands/config/joinleave/info.ts
- src/commands/config/joinleave/remove.ts
- src/commands/config/joinleave/set.ts
- src/commands/index.ts
- src/events/guildMemberAdd.ts
- src/events/guildMemberRemove.ts
- src/events/index.ts
- src/types/api.ts
- New command set `$joinleave` or `$jl`  with actions `set, info, remove` to config join-leave monitoring channel
- Add a new intent `GUILD_PRESENCES`
- Send webhook with event `guildMemberRemove` - user kicked or leaving server
> feat: joinleave channel

- src/commands/community/quest/daily.ts
- src/types/api.ts
-   [x] Render streak quest rewards when claim rewards
**Media**
1. Without streak bonus
2. With upvoting streak bonus (`multiplier = 1.2`)
a. Before claim
b. Claim rewards
> refactor: quest rewards - streak

- src/commands/defi/ticker/ticker.ts
- src/types/api.ts
-   [x] $ticker: right bull/bear sometimes overlapping the chart
**Media**
> fix: ticker chart overlapped

- src/commands/community/prune/inactive.ts
- src/commands/community/prune/without.ts
- src/commands/community/prune_slash/inactive.ts
- src/commands/community/prune_slash/without.ts
- src/types/api.ts
-   [x] Fix slash command not able to run, use `editReply` instead of `reply` because interaction already deferred
-   [x] Add hollow user id for easy demo
-   [x] Correct `inactive` help message
-   [x] `without` case: handle situation where user disables DM => flow exit before kick command is run
-   [x] Replace cancel button with exit button
> fix: prune

- src/adapters/defi.ts
- src/commands/defi/offchain_tip_bot/airdrop.ts
- src/commands/defi/offchain_tip_bot/balance.ts
- src/commands/defi/offchain_tip_bot/deposit.ts
- src/commands/defi/offchain_tip_bot/tip.ts
- src/commands/defi/offchain_tip_bot/withdraw.ts
- src/commands/index.ts
- src/events/interactionCreate.ts
- src/types/defi.ts
- src/utils/common.ts
> feat: deposit offchain

- src/commands/config/reactionRole/list.ts
-   [x] Fix `$rr list`: hide rr configs which do not have `channel_id`
> fix: rr list

- src/commands/defi/airdrop.ts
-   [x] airdrop duplicate msg ( when call emit expire, node cache execute the function and when node expire by ttl it execute again and create duplicate content in msg )
Before
After
> fix: airdrop duplicate msg

- src/utils/TwitterStream.ts
-   [x] Add expansion of mentions (otherwise the property will be undefined)
> fix: include expansion in twitter

- src/commands/community/nft/ticker.ts
-   [x] toggle chart render and add emoji token (with option 1 day and 7 days api response does not include times and prices to render chart)
https://www.loom.com/share/ed21a070992b44a093d945f35b30ed67
> fix: toggle chart render and add emoji

- src/commands/community/nft/ticker.ts
-   [x] delete blank nft ticker
Before:
After:
> chore: delete blank in price

- src/commands/community/nft/ticker.ts
-   [x] format volume number (total_volume return does not have decimals so use decimals of other field with same token)
API return does not have decimals for total volume:
> chore: format volume number

- src/commands/defi/tip.ts
-   [x] Replace all spaces (2 or more) to be a single space
> fix: tip handle case multiple spaces in command string

- src/commands/community/gm/index.ts
- src/commands/community/gm_slash/index.ts
- src/commands/community/invite/index.ts
- src/commands/community/sales/index.ts
- src/commands/community/verify/index.ts
- src/commands/community/verify_slash/index.ts
- src/commands/community/vote/index.ts
- src/commands/community/vote/vote_slash.ts
- src/commands/config/defaultRole/index.ts
- src/commands/config/defaultRole_slash/index.ts
- src/commands/config/log/index.ts
- src/commands/config/nftRole/index.ts
- src/commands/config/nftRole_slash/index.ts
- src/commands/config/reactionRole/index.ts
- src/commands/config/reactionRole_slash/index.ts
- src/commands/config/telegram/index.ts
- src/commands/defi/ticker/ticker.ts
- src/commands/defi/ticker_slash/ticker_slash.ts
- src/commands/defi/token/index.ts
- src/commands/defi/watchlist/index.ts
- src/commands/defi/watchlist_slash/index.ts
- src/types/api.ts
-   [x] add example command in help menu (check list: https://www.notion.so/console-labs/Example-in-command-main-help-menu-7d48fb6229b241b7b70eec78d69d23a0)
> chore: add example command in help menu

- src/commands/community/nft/stats.ts
- src/types/api.ts
- src/utils/common.ts
-   [x] Fix embedded msg nft stats
Before
After
> chore: fix-embed-msg-nft-stats

- src/commands/community/gm/config.ts
- src/utils/emoji.ts
-   [x] Handle case only phrase, no emoji
-   [x] Handle case only emoji, no phrase
`$gm config #general morning`
`$gm config #general 🌔`
> fix: handle different cases of gm config

- src/commands/config/poe/twitter/stats.ts
-   [x] Join two code text together
`$poe twitter stats`
|Before|After|
|---|---|
|<img width="264" alt="CleanShot 2022-12-07 at 15 07 22@2x" src="https://user-images.githubusercontent.com/25856620/206123464-7ab0fb46-b61a-4283-b605-f0bc86b9ace2.png">|<img width="258" alt="CleanShot 2022-12-07 at 15 07 25@2x" src="https://user-images.githubusercontent.com/25856620/206123489-615004a7-6019-4603-89c5-50ac2cfbbef1.png">|
> fix: poe twitter stats ui tweak

- src/commands/config/defaultRole/set.ts
-   [x] Update the help menu message of $dr set
> fix: default role set help menu

- src/adapters/defi.ts
- src/commands/defi/withdraw.ts
- src/types/api.ts
-   [x] Remove old withdraw address validation (starts with `0x`): we support solana now
**Media**
> feat: remove wd address validation

- src/commands/nft/query/processor.ts
> fix: nft attr name

- src/commands/log/info/processor.ts
- tests/assertions/discord.ts
-   [x] `$log info`:  pass emoji to `author` -> should pass emoji URL instead
> Fix: log info emoji

- src/adapters/defi.ts
- src/commands/airdrop/index/processor.ts
- src/commands/withdraw/index/processor.test.ts
- src/commands/withdraw/index/processor.ts
- src/commands/withdraw/index/slash.test.ts
- src/commands/withdraw/index/slash.ts
- src/commands/withdraw/index/text.ts
- src/utils/common.ts
-   [x] `$withdraw`: add address validation
**Media**
1. EVM wallet
2. solana wallet (ignore last error -> dont have any SOL left to make it successful)
> fix: withdraw - address validation

- src/commands/alert/add/text.ts
- src/commands/alert/list/text.ts
- src/commands/alert/remove/text.ts
- src/commands/index.ts
- src/commands/wallet/index.ts
- src/commands/wallet/view/slash.ts
- src/utils/constants.ts
-   [x] Refactor wallet view to slash command
- Use `/wallet` or `/wallet view`
> refactor: migrate wallet slash command

- src/ui/discord/embed.ts
- change partner ad from Bimp's to Sunfire's
> chore: change partner ad

- src/utils/defi.ts
-   [x] case fiat: check if both base & target belongs to our supported fiats. if not => not comparison query => no target
> fix: parse ticker args

- src/commands/proposal/processor.ts
-   [x] Remove the required amount of token msg, since user just need to own the token
> fix: dao voting checking msg

- src/adapters/profile.ts
- src/commands/proposal/processor.ts
- src/commands/verify/processor.ts
- src/commands/wallet/add/processor.ts
- src/types/api.ts
Migrate wallet verification: use new mochi-profile [endpoint](https://api-develop.mochi-profile.console.so/swagger/index.html#/profiles/post_profiles__id__codes) `/api/v1/profiles/{id}/code`
> refactor: migrate wallet verification

- src/commands/pay/index.ts
-   [x] When use uses `$pay` command with recipient, treat that as a `$tip` command
`$pay @user 1 ftm`
`$pay @role 1 ftm`
`$pay voice 1 ftm`
> feat: redirect pay with recipient command to tip command

- src/handlers/tagme.ts
- src/listeners/discord/interactionCreate.ts
-   [x] Make the unsub button become resub instead of disabling it
> feat: tagme command, turn unsub button to resub

- src/commands/swap/index/processor.ts
-   [x] Remove all buttons once swap request is submitted
-   [x] Keep the "View in web" button
-   [x] Remove the profile API call because the swap API auto use Mochi Wallet
> fix: swap mochi

- src/commands/watchlist/index.ts
-   [x] Add `$wlv` as alias to `$wl view`
**Note**
We can not simply add alias to the `watchlist/view/text.ts` file because our structure doesn't support alias in command's action, so we must add alias to the command root and then handle it in the command's run function
> chore: add alias watchlist view

- src/commands/airdrop/index.ts
- src/commands/airdrop/index/processor.ts
- src/commands/airdrop/index/slash.ts
- src/errors/base.ts
- src/errors/insufficient-balance.ts
- src/utils/wrap-error.ts
-   [x] some errors related to show token amount and usd value for case `airdrop all`
-   [x] can't show insufficient balance response due to slash unhandled select-menu
-   [x] /airdrop only allow to input amount as number
> fix: airdrop - all option

- src/commands/transaction/index/processor.ts
-   [x] filter out transactions that has empty `other_profile_id` field
-   [x] Get 10 most recent transaction to prevent from embed character limit
> fix: transaction empty other profile id

- src/commands/airdrop/index/processor.ts
- src/commands/index.ts
- src/commands/tip/index.ts
- src/commands/tip/index/processor.ts
- src/utils/tip-bot.ts
-   [x] Add alias `send` to `tip` command
-   [x] Support no-space case for tip (`1butt`, `0.2eth`, `100.2btc`, etc...)
> chore: resolve feedbacks

- src/commands/airdrop/index/handler.ts
- src/commands/airdrop/index/processor.ts
- src/commands/airdrop/index/slash.ts
- src/commands/balances/index/processor.ts
- src/commands/swap/index/processor.ts
- src/commands/tip/index.ts
- src/commands/tip/index/processor.ts
- src/commands/tip/mail/processor.ts
- src/commands/tip/telegram/processor.ts
- src/commands/tip/twitter/processor.ts
- src/commands/withdraw/index/processor.ts
- src/types/transfer.ts
- src/ui/canvas/chart.ts
- src/utils/defi.ts
- src/utils/tip-bot.ts
Handle tip/airdrop edge cases
$tip
$airdrop
- if `maxEntries` is specified, calculate max recipients and check if `maxEntries` exceed that  
- if `maxEntries` is not specified, implicitly calculate maxRecipients and only send tokens to first `maxRecipients` participants
in the video, `maxEntries` was not specified but the amount can only splitted to at max 1 recipient -> airdrop session auto ended
https://user-images.githubusercontent.com/34529672/236790714-8b9dc117-fcbb-4cd8-bc9b-c68cbfc702e7.mov
> fix: tip edge cases

- src/commands/withdraw/index/processor.ts
-   [x] change message dm to user when withdrawal
From:
To:
> feat: change withdraw message dm user

- src/commands/token/add/processor.ts
- src/errors/internal.ts
-   [x] `/token add`: Handle errors when token already exists or token data not found
**Media**
> fix: token add - handle errors

- src/commands/swap/index.ts
- src/commands/swap/index/processor.ts
This PR cover most of case for ticker swap
- On evm -> already handle case token exist on multiple chain, ex: usdc on eth, ftm, arb, ...
- Edge case
->  we cant swap to Spell on chain ftm right now
->  if choose swap from ftm -> spell on ethereum will return no route
> fix: cover case ticker swap

- src/index.ts
- src/utils/commands.ts
- src/utils/defi.ts
-   [x] Enhance `formatDigit()`: add flag `shorten` (bool). When enabled (true), shorten big number
.e.g 
- 3000 -> 3K
- 2,512,534,123 -> 2.5B
- 1,000,000 -> 1M
- 4,111,111,111,111 -> 4.1T
> feat: enhance big number formatter

- src/commands/balances/index/processor.ts
- src/utils/defi.ts
Rounding token amount in /balances
-   [x] 2 digits if < 100K
-   [x] 0 digits if >= 100K
> fix: rounding balances

- scripts/generate-types.js
- src/adapters/profile.ts
- src/commands/verify/processor.ts
- src/utils/profile.ts
-   [x] Use env to set generate api url instead of hardcode using dev api
-   [x] Add option `noFetchAmount` when calling api get by discord
> chore: update type gen swagger and get by discord with avoiding amount

- src/commands/wallet/copy/processor.ts
- src/commands/wallet/copy/slash.ts
- src/commands/wallet/follow/processor.ts
- src/commands/wallet/follow/slash.ts
- src/commands/wallet/list/processor.ts
- src/commands/wallet/track/processor.ts
- src/commands/wallet/track/slash.ts
-   [x] Update successful UI for cmd `/wallet track` and button to route to watchlist wallet
-   [x] Update successful UI for cmd `/wallet copy` and button to route to watchlist wallet
> fix: update ui for cmd wallet track and copy when success

- src/commands/default/ticker/info/slash.ts
- src/types/api.ts
-   [x] handle empty case get guild's default ticker list
`/default ticker info`
> fix: default ticker empty view

- src/commands/balances/index/processor.ts
- src/commands/wallet/common/tracking.ts
- src/commands/wallet/copy/processor.ts
- src/commands/wallet/follow/processor.ts
- src/commands/wallet/index.ts
- src/commands/wallet/list/slash.ts
- src/commands/wallet/remove/processor.ts
- src/commands/wallet/track/processor.ts
- src/commands/wallet/view/slash.ts
- src/commands/watchlist/view/processor.ts
-   [x] Add cmd `/wallet list` to view list tracking wallets
-   [x] Fix API `/wallet view <address>` to view wallet detail
-   [x] Modify `machineConfig` of wallet cmd group to route between states, and re-map/add button `wallets` to a few messages such as wallet details. 
-   [x] Map list wallet dropdown to see wallet detail when clicking on each item
> fix: wallet tracking flow mapping

- src/commands/default/index.ts
-   [x] Fix autocomplete for default ticker set
`/default ticker set`
> fix: default ticker set autocomplete

- src/adapters/defi.ts
- src/commands/wallet/alias/index.ts
- src/commands/wallet/alias/remove/slash.ts
- src/commands/wallet/alias/set/processor.ts
- src/commands/wallet/alias/set/slash.ts
- src/commands/wallet/index.ts
- src/commands/wallet/list/processor.ts
- src/types/api.ts
- src/utils/common.ts
-   [x] add cmd wallet alias
- `/wallet alias set <address/current alias> <new alias>` ->  add/update alias
- `/wallet alias remove <address/current alias>` -> remove alias
- Error messages
- Reformat wallet watchlist, show both address and alias
> feat: add cmd wallet alias

- src/commands/balances/index/processor.ts
- src/utils/common.ts
> fix: ronin recent txns

- src/commands/balances/index/slash.ts
- src/commands/wallet/common/tracking.ts
- src/commands/wallet/copy/processor.ts
- src/commands/wallet/copy/slash.ts
- src/commands/wallet/follow/processor.ts
- src/commands/wallet/follow/slash.ts
- src/commands/wallet/list/processor.ts
- src/commands/wallet/track/processor.ts
- src/commands/wallet/track/slash.ts
- src/commands/watchlist/view/slash.ts
- src/listeners/discord/interactionCreate.ts
-   [x] Remove option `chain` from `/wallet follow/track/copy`
- `/wlv -> wallets -> view wallet detail` does not work
- `/profile-> pick wallet` shows wrong button, and these buttons is not updated as expected behavior: 
- For example:
- When I followed wallet X, then I view profile `/profile Meme -> pick wallet X` show `follow` button, but the expected button is `unfollow`
- Reason: When routing to the view balance state, target user ID is another person (ex: Meme who has wallet X). And this person does not follow X.
- Solution: 
- When onchain wallet is picked  -> show balance by view of cmd’s author 
- In other cases, show balance depend on target user
> fix: wallet flow bugs

- src/utils/providers.ts
-   [x] Use new JSON RPC URL for eth: `https://eth.llamarpc.com`
> fix: ens lookup

- src/commands/wallet/index.ts
- src/commands/wallet/view/address/slash.ts
- src/commands/wallet/view/index.ts
- src/commands/wallet/view/profile/slash.ts
- src/types/api.ts
-   [x] Update current cmd syntax: `/wallet view` -> `/wallet view address`
**Media**
1. `/wallet view profile`:  View other members' wallets
2. `/wallet view address`: view my wallets
> feat: view member wallets

- src/commands/profile/index/processor.ts
- src/commands/vault/list/processor.ts
-   [x] add server name for list vault
- use /profile in dm
- use /profile in guild
> chore: add server name for list vault

- src/commands/balances/index/processor.ts
- src/commands/wallet/copy/processor.ts
- src/commands/wallet/follow/processor.ts
- src/commands/wallet/list/processor.ts
- src/commands/wallet/track/processor.ts
- src/commands/wallet/view/address/slash.ts
- src/utils/common.ts
- yarn.lock
-   [x] Missing context alias let tracking buttons ignore this field when update the tracking status
Example:  Using wallet track with alias -> click on button follow -> click on button wallets -> The alias is still remained in the tracking list
-   [x] Cmd `wallet list` does not show name service domain
> fix: bug missing context alias when click tracking buttons

- src/commands/invest/portfolio/processor.ts
- src/commands/invest/portfolio/slash.ts
- src/commands/profile/index/processor.ts
- src/commands/profile/index/slash.ts
-   [x] Move invest port into a section of profile 
- use command `/profile`
> fix: move invest portfolio to profile section

- src/commands/swap/index.ts
- src/commands/ticker/index.ts
-   [x]  update description for swap `to` and `from`
before:
after: 
-   [x]  update  ticker command for dm
> chore: udpate ticker dm and swap description

- src/commands/profile/index/processor.ts
-   [x] Add spacing in profile command (Wallets)
`/profile`
> chore: add space in profile cmd

- src/commands/guess/new/slash.ts
> fix: add game bet amount guess game

- src/commands/vault/transfer/processor.ts
- src/types/api.ts
-   [x] /vault transfer address: handle empty user's profile ID properly
> fix: vault transfer address

- src/adapters/defi.ts
- src/types/api.ts
> fix: remove response dexpair type

- src/types/api.ts
- src/utils/common.ts
> fix: domain validation before resolving

- src/commands/airdrop/index/processor.ts
- src/commands/tip/index/processor.ts
- src/commands/v/index.ts
- src/types/api.ts
- src/types/transfer.ts
- src/utils/discord.ts
-   [x] show channel url in tip notification message
> fix(tip): show channel url in tip notification message

- src/commands/deposit/index/processor.ts
- src/commands/deposit/index/slash.ts
- src/types/api.ts
Different chains with the same deposit contract hash let missing options when choosing contract to deposit
> fix: handle case same contract hash at different chains

- src/commands/balances/index/processor.test.ts
- src/commands/deposit/index/processor.ts
- src/commands/pay/me/processor.ts
- src/commands/vault/info/slash.ts
- src/utils/chain.ts
Change from using isEvm to chainType, to be compatible with change of following migrations:
- https://github.com/consolelabs/mochi-pay-api/pull/334
- https://github.com/consolelabs/mochi-pay-api/pull/338
> fix: replace is evm by chain type

- src/utils/wrap-error.ts
-   [x] error name prop can be readonly sometime, just ignore and give more context to sentry when this happen
> fix(sentry): handle read-only error

- .github/workflows/gke-preview.yml
- .github/workflows/gke-prod.yml
- src/commands/v/index.ts
- src/types/api.ts
-   [x] update CI to rebuild image
> feat: update CI to rebuild image

- src/commands/tip/index/processor.ts
- src/commands/tip/index/text.ts
- src/utils/tip-bot.ts
-   support diff format tip: /tip <users> <amount> or /tip <amount> <users>
-  keep the follow up msg as it is
-  fix bug for float with "," make the amount wrong
> fix: support diff format tip and keep the follow up msg

- src/commands/watchlist/add/processor.ts
Add token to watchlist from ticker: update payload data
- Current: pass coin ID to `symbol`
- Solution: use correct symbol in the request payload
> fix: track token - adjust payload

- src/commands/ticker/index/processor.ts
- Ticler: add more market data
> fix: ticker - add more market data

- package.json
- pnpm-lock.yaml
- src/adapters/mochi-pay.ts
- src/commands/vault/index.ts
- src/commands/vault/info/processor.ts
- src/commands/vault/info/slash.ts
- src/commands/vault/key/processor.ts
- src/commands/vault/key/slash.ts
- src/commands/vault/list/processor.ts
- src/commands/vault/new/processor.ts
- src/commands/vault/new/slash.ts
- src/commands/vault/view/processor.ts
- src/commands/vault/view/slash.ts
- src/types/api.ts
- src/utils/slash-command.ts
> feat: trading vault

- src/ui/canvas/chart.ts
- Ticker chart: fix y-axis number format
Reason: Seems like there is a bug from `chartjs` - when we try to overwrite the default y-axis value format configuration option (`ticks.callback`),  integers will somehow unnecessarily get extra zero decimals (e.g. 3-> 3.0000000000000004)
> fix: ticker chart - y-axis number format

- src/adapters/mochi-pay.ts
- src/commands/vault/info/processor.ts
- src/commands/vault/info/slash.ts
- src/commands/vault/list/processor.ts
> fix(vault): render all rounds ui

- src/adapters/mochi-pay.ts
- src/commands/vault/info/processor.ts
- src/utils/chart.ts
-   [x] add render pnl chart when show trading vault info
> fix(vault): add chart pnl for trading vault

- src/adapters/mochi-pay.ts
- src/commands/vault/info/processor.ts
- src/commands/vault/info/slash.ts
> feat: trading vault deposit
