consolelabs/mochi-discord

tests/assertions/discord.ts
=> test: update assertion

src/listeners/discord/interactionCreate.ts, src/types/api.ts, src/ui/discord/select-menu.ts
=> fix: interaction issue

src/commands/wallet/view/processor.ts, src/types/api.ts
=> fix: wallet view - temp solution

src/commands/claim/index/processor.test.ts, src/commands/claim/index/text.test.ts, src/commands/claim/index/text.ts
-   [x] Add test for claim feature
=> chore: add test for claim

src/commands/quest/daily/processor.test.ts, src/commands/quest/daily/slash.test.ts, src/commands/quest/daily/slash.ts, src/commands/quest/daily/text.test.ts, src/types/api.ts
=> test: quest cmd

src/commands/verify/info/processor.test.ts, src/commands/verify/info/processor.ts, src/commands/verify/info/slash.test.ts, src/commands/verify/info/slash.ts, src/commands/verify/info/text.test.ts, src/commands/verify/remove/processor.test.ts, src/commands/verify/remove/processor.ts, src/commands/verify/remove/slash.test.ts, src/commands/verify/remove/slash.ts, src/commands/verify/remove/text.test.ts, src/commands/verify/remove/text.ts, src/commands/verify/set/processor.test.ts, src/commands/verify/set/slash.test.ts, src/commands/verify/set/text.test.ts, src/types/api.ts
=> test: verify cmd

src/commands/airdrop/index/processor.ts, src/ui/discord/embed.ts
- fix airdrop confirmation
- fix partner ad thumbnail
=> chore: fix airdrop

src/commands/nft/add/processor.ts, src/commands/nft/add/slash.test.ts, src/commands/nft/add/slash.ts, src/commands/nft/add/text.test.ts, src/commands/nft/config/slash.test.ts, src/commands/nft/config/slash.ts, src/commands/nft/config/text.test.ts, src/commands/nft/integrate/processor.test.ts, src/commands/nft/integrate/processor.ts, src/commands/nft/integrate/slash.test.ts, src/commands/nft/integrate/slash.ts, src/commands/nft/integrate/text.test.ts, src/commands/nft/list/processor.test.ts, src/commands/tip/index/processor.ts, src/types/api.ts
=> test: test for nft cmd

package.json, src/commands/tip/index/processor.ts, src/types/api.ts
-   [x] fix tip msg with moniker
=> fix: fix tip msg with moniker

src/commands/watchlist/view/processor.test.ts, src/commands/watchlist/view/processor.ts, src/commands/watchlist/view/text.test.ts, src/commands/watchlist/view/text.ts
- add paging function to `$wl view`
=> feat: wl pagination

src/commands/tip/index/processor.test.ts
- revived and updated tests for `tip`
=> chore: revive test

src/commands/airdrop/index/processor.ts, src/commands/alert/add/text.ts, src/commands/alert/index.ts, src/commands/alert/list/slash.ts, src/commands/alert/list/text.ts, src/commands/alert/remove/text.ts, src/commands/moniker/set/processor.ts, src/commands/statements/index/slash.ts, src/commands/statements/index/text.ts, src/commands/tip/index/processor.ts, src/commands/token/default/processor.test.ts, src/commands/token/default/processor.ts, src/utils/constants.ts
-   [x] Update copy writing for $token and $alert command
- `$token`
- `$alert`
=> fix: token and price alert copy writing

src/commands/balances/index/processor.ts, src/commands/index.ts, src/commands/tip/index/processor.ts, src/commands/wallet/add/processor.ts, src/listeners/discord/interactionCreate.ts, src/types/common.ts, src/ui/discord/select-menu.ts
-   [x] Fix duplicate tip when pressing confirm button multiple times
- `$tip someone >= 100$ token`
=> fix: duplicate tip

src/commands/help/index/processor.ts, src/utils/constants.ts
- fix help menu `Server Management` not clickable
=> chore: fix help menu

src/adapters/community.ts, src/adapters/profile.ts, src/commands/profile/index/processor.ts, src/commands/profile/index/slash.ts, src/commands/profile/index/text.ts, src/commands/wallet/remove/processor.ts, src/commands/wallet/view/processor.ts, src/utils/common.ts, src/utils/constants.ts
=> refactor: profile command

src/utils/common.ts
-   [x] Add emoji for token $mclb, $fbomb
=> chore: add emoji token fbomb and mclb

src/commands/airdrop/index/processor.ts
-   [x] Fix assign balance logic
=> fix: airdrop assign balance logic

src/commands/ticker/compare-token/processor.test.ts, src/commands/ticker/compare-token/processor.ts, src/commands/ticker/compare-token/slash.ts, src/commands/ticker/compare-token/text.ts, src/commands/ticker/default/processor.test.ts, src/commands/ticker/index/processor.test.ts, src/commands/ticker/index/slash.test.ts, src/commands/ticker/index/text.test.ts
=> chore: test ticker

src/commands/watchlist/view/processor.ts
=> chore: fix wl

src/commands/airdrop/index/processor.ts, src/commands/balances/index/processor.ts, src/commands/globalxp/index/text.ts, src/commands/nft/query/text.ts, src/commands/proposal/info/processor.ts, src/commands/proposal/processor.ts, src/commands/prune/inactive/slash.ts, src/commands/prune/inactive/text.ts, src/commands/prune/without/slash.ts, src/commands/prune/without/text.ts, src/commands/starboard/list/processor.ts, src/commands/statements/index/processor.ts, src/ui/discord/button.ts, src/ui/discord/select-menu.ts
=> chore: change btn color

src/commands/tip/index/processor.ts, src/commands/tip/index/text.ts, src/commands/wallet/add/processor.ts, src/commands/withdraw/index/processor.test.ts, src/commands/withdraw/index/processor.ts, src/commands/withdraw/index/text.test.ts, src/commands/withdraw/index/text.ts, src/utils/discord.ts
=> fix: withdraw - await recipient addr

src/commands/tip/index/processor.test.ts, src/commands/tip/index/processor.ts
=> chore: test tip

src/errors/base.ts
-   [x] Fix log bug
**References**
https://www.notion.so/console-labs/Log-bug-73a2db7765f842f7afb685e9fdeefb05
=> chore: fix log bug

src/ui/discord/embed.ts
=> chore: update ad

src/adapters/defi.ts, src/commands/ticker/index/processor.test.ts, src/commands/ticker/index/processor.ts, src/commands/ticker/index/slash.ts, src/commands/ticker/index/text.ts, src/commands/watchlist/add/processor.ts
-   [x] Generic function for text + slash cmd `composeTickerResponse
**Media**
1. if ticker hasn't been added to wl
2. if ticker added to wl before
=> refactor: ticker

src/adapters/config.ts, src/commands/proposal/track/processor.ts, src/listeners/discord/interactionCreate.ts, src/types/api.ts
-   [x] Handle create thread and subscribe discussion commonwealth
- Click join thread in discussion log message
=> feat: proposal discussion

src/commands/alert/add/processor.ts, src/commands/alert/remove/processor.ts
=> chore: fix remove err

src/cache/node-cache.ts, src/commands/airdrop/index/processor.test.ts, src/commands/airdrop/index/processor.ts, src/commands/deposit/index.ts, src/commands/deposit/index/processor.test.ts, src/commands/deposit/index/processor.ts, src/commands/moniker/set/processor.ts, src/commands/statements/index/slash.ts, src/commands/statements/index/text.ts, src/commands/tip/index/processor.test.ts, src/commands/tip/index/processor.ts, src/commands/withdraw/index/processor.test.ts, src/commands/withdraw/index/processor.ts, src/errors/direct-message-not-allowed.ts, src/utils/tip-bot.ts
Deposit updates:
**Bonus**: rename `tipTokenIsSupported()` to `isTokenSupported()`
**Media**
- Before
- After
=> fix: deposit expiration

src/adapters/defi.ts, src/commands/airdrop/index/slash.test.ts, src/commands/deposit/index/processor.test.ts, src/commands/deposit/index/processor.ts, src/commands/deposit/index/slash.test.ts, src/commands/tip/index.ts, src/commands/tip/index/processor.test.ts, src/commands/tip/index/processor.ts, src/commands/tip/index/slash.test.ts, src/commands/tip/index/slash.ts, src/commands/tip/index/text.test.ts, src/commands/tip/index/text.ts
-   [x] Additional test for tip-bot slash commands
=> test: tip-bot slash

src/commands/deposit/index/processor.ts, src/env.ts, src/utils/constants.ts
-   [x] Update deposit expiration message
**Media**
=> fix: deposit expiration msg

src/commands/index.ts, src/env.ts, src/listeners/discord/ready.ts, src/logger/usage-tracker.ts, src/logger/usage-tracking.ts, src/types/api.ts
-   [x] usage tracking channel
=> chore: usage tracking channel

src/commands/gm/set/text.ts, src/commands/prune/inactive/slash.ts, src/commands/prune/inactive/text.ts, src/commands/wallet/add/text.ts, src/commands/wallet/index.ts
=> chore: update old ui

src/commands/index.ts, src/commands/stats/index.ts, src/commands/stats/index/processor.ts, src/commands/stats/index/slash.ts, src/commands/stats/index/text.ts, src/types/api.ts
-   [x] revert stats cmd
https://www.loom.com/share/30e3e805ccd84c929328c22108a12d73
=> chore: revert stats cmd

src/commands/proposal/processor.ts, src/utils/wrap-error.ts
-   [x] Fix handling error when proposal expired
=> fix: expired proposal handle throw error

src/commands/profile/index/processor.ts, src/types/api.ts
=> chore: profile remove appellation

src/commands/proposal/set/text.ts, src/types/api.ts
-   [x] fix proposal ui bug: response when error api for nft holder, validate chain
=> chore: fix proposal ui bug

src/commands/verify/processor.ts
=> chore: fix verify address

src/commands/proposal/processor.ts
=> chore: fix proposal msg

src/commands/verify/processor.ts
-   [x] Use the new mochi-profile api to link account
=> feat: add discord id in verify

src/commands/token/list/processor.test.ts, src/commands/token/list/processor.ts, src/commands/token/list/slash.test.ts, src/commands/token/list/slash.ts, src/commands/token/list/text.test.ts, src/commands/token/list/text.ts
- change `token list` API call from guild config to all supported tokens
=> chore: update token list

src/commands/airdrop/index/processor.ts
-   [x] fix ui usd amount of airdrop
-  [x] fix invalid max entries
=> fix: airdrop bug

src/adapters/defi.ts, src/commands/token/add/processor.ts, src/commands/token/add/text.test.ts, src/commands/token/add/text.ts, src/listeners/discord/interactionCreate.ts
-   [x] $token add
- `$token add xsushi  0x1234556 eth`
=> feat: token add

src/adapters/defi.ts, src/commands/gas/index.ts, src/commands/gas/index/processor.ts, src/commands/gas/index/slash.ts, src/commands/gas/index/text.ts, src/types/api.ts
=> feat: gas tracker one chain

src/adapters/game-store.ts, src/commands/game/index.ts, src/commands/game/index/processor.ts, src/commands/game/index/slash.ts, src/commands/game/index/text.ts, src/commands/index.ts, src/types/api.ts
-   [x] Add alias `games` for `$game` command
-   [x] Handle not found case
-   [x] Handle invalid game id case
-   [x] Embed content tweak
=> chore: add alias for game command

src/commands/nft-role/processor.ts, src/commands/proposal/processor.ts, src/commands/token-role/processor.ts, src/listeners/discord/guildMemberAdd.ts, src/utils/constants.ts
-   [x] Use `HOMEPAGE_URL` constant
-   [x] Modify the proposal connect wallet url
=> fix: proposal verify url

src/commands/gm/info/processor.ts, src/commands/gm/set/slash.ts, src/commands/gm/set/text.ts, src/commands/poe/twitter/block/index.ts, src/commands/proposal/set/text.ts, src/commands/verify/remove/processor.test.ts, src/commands/verify/remove/processor.ts, src/commands/verify/remove/slash.test.ts, src/commands/verify/remove/text.test.ts
- fix `gm` `verify` `poe twitter` ui
=> chore: fix bugs

src/commands/verify/processor.ts, src/commands/wallet/add/processor.ts, src/env.ts
-   [x] Convert all places where `WEBSITE_ENDPOINT` was used to `HOMEPAGE_URL` (they are the same)
-   [x] Remove `WEBSITE_ENDPOINT`
=> fix: remove redundant env

src/adapters/mochi-pay.ts, src/commands/index.ts, src/commands/new-tip/telegram/processor.ts, src/commands/pay/index.ts, src/commands/pay/link/processor.ts, src/commands/pay/link/text.ts, src/errors/insufficient-balance.ts, src/ui/discord/embed.ts, src/utils/common.ts
-   [x] New command: `$pay link <amount> <token> [note]`
=> feat: cmd pay link

src/commands/activity/index/processor.ts
-   [x] update activity based on new response format
=> chore: update activity based on new response format

src/adapters/profile.ts, src/commands/activity/index.ts, src/commands/activity/index/processor.ts, src/commands/activity/index/slash.ts, src/commands/activity/index/text.ts
=> chore: update activity ui

src/adapters/defi.ts, src/commands/convert/index.ts, src/commands/convert/index/processor.ts, src/commands/convert/index/slash.ts, src/commands/convert/index/text.ts, src/commands/index.ts, src/utils/common.ts
=> feat: convert token price

src/commands/log/set/slash.ts, src/commands/log/set/text.ts
-   [x] Merge config notify tip tx api call into log command
=> chore: merge config notify tx into log command

src/adapters/profile.ts, src/commands/activity/index/processor.ts, src/commands/convert/index/processor.ts
-   [x] Update activity & convert UI
=> chore: update activity & convert ui

src/commands/activity/index/processor.ts, src/commands/inbox/index/processor.ts, src/commands/wallet/index.ts, src/commands/wallet/new/processor.ts, src/commands/wallet/new/text.ts
-   [x] Update inbox & clone pay link to wallet new
=> chore: update inbox & clone pay link to wallet new

src/commands/convert/index/processor.ts
-   [x] Add additional info of 2 tokens
-   [x] Fix the ratio
`/conversion 2 eth btc`
`/conversion 10 usdt eth`
=> fix: conversion

src/commands/convert/index.ts, src/commands/convert/index/processor.ts, src/commands/convert/index/slash.ts, src/commands/convert/index/text.ts
=> feat: add emoji to conversion

src/commands/quest/daily/processor.ts
-   [x] hide trade and vote from quest
=> chore: hide trade and vote from quest

src/commands/gas/index.ts, src/commands/new-tip/index.ts, src/commands/pay/link/text.ts, src/commands/pay/me/text.ts, src/types/api.ts, src/utils/constants.ts
-   [x] Update help interface for $pay, $tip, $gas
=> chore: update help interface

src/commands/new-tip/index.ts, src/commands/pay/index.ts, src/commands/pay/link/text.ts, src/commands/pay/me/text.ts, src/types/api.ts
-   [x] Add missing info & fix typo issues
=> chore: clean typo issues

src/adapters/defi.ts, src/commands/token/add/processor.ts, src/commands/token/add/slash.test.ts, src/commands/token/add/slash.ts, src/commands/token/add/text.ts, src/commands/token/index.ts
-   [x] Move from text cmd to slash cmd for `token add`
=> chore: update token add cmd

src/commands/config/index.ts, src/commands/config/logchannel/info/processor.ts, src/commands/config/logchannel/info/slash.ts, src/commands/config/logchannel/set/processor.ts, src/commands/config/logchannel/set/slash.ts, src/commands/index.ts, src/types/api.ts, src/types/common.ts
-   [x] Add `/config logchannel` subcommands
`/config logchannel set`
`/config logchannel info`
=> feat: config logchannel command

src/commands/new-tip/index.ts, src/commands/new-tip/index/slash.test.ts, src/commands/new-tip/index/slash.ts
-   [x] edit description of tip
Requirement:
=> chore: edit description of tip

src/commands/token/list/processor.ts, src/types/api.ts
-   [x] Update token list order
=> chore: update token list order

src/adapters/config.ts, src/commands/vault/add/processor.ts, src/commands/vault/new/processor.ts, src/listeners/discord/interactionCreate.ts, src/utils/common.ts
https://www.loom.com/share/b55b2dd94ebe4bbbb74185971ddcce8e
=> feat: flow add treasurer

package.json, src/adapters/defi.ts, src/commands/heatmap/index.ts, src/commands/heatmap/index/processor.ts, src/commands/heatmap/index/slash.ts, src/commands/heatmap/index/text.ts, src/commands/index.ts, src/types/api.ts, src/ui/canvas/draw.ts, yarn.lock
=> feat: heatmap cmd

src/commands/config/logchannel/info/slash.ts, src/commands/config/logchannel/set/slash.ts, src/commands/moniker/index.ts, src/commands/moniker/list/slash.ts, src/commands/moniker/list/text.ts
-   [x] Remove `>` character in /config logchannel info
-   [x] Lowercase all log types
-   [x] Change output of /moniker list
| Header | Header |
|--------|--------|
|<img width="207" alt="CleanShot 2023-04-05 at 10 29 59@2x" src="https://user-images.githubusercontent.com/25856620/229974142-2e12a0b5-e52a-417f-be2f-5dc1eddc488d.png">| <img width="172" alt="CleanShot 2023-04-05 at 10 40 37@2x" src="https://user-images.githubusercontent.com/25856620/229975518-d5066095-a308-4249-8fd4-018f9770918f.png"> |
| <img width="439" alt="CleanShot 2023-04-05 at 10 41 26@2x" src="https://user-images.githubusercontent.com/25856620/229975633-48b58e00-d6a2-41c3-81d9-b17d2d5847e9.png"> | <img width="454" alt="CleanShot 2023-04-05 at 10 41 05@2x" …
=> chore: command tweaks

src/adapters/config.ts, src/commands/vault/add/processor.ts, src/commands/vault/remove/processor.ts, src/types/api.ts
- Not allow to submit vote when reach threshold
- Notify result submit in user DM, not only in channel
=> chore: lock vote when reach threshold

src/commands/withdraw/index/processor.ts
-   [x] use `interaction.editReply` instead of `interaction.reply`
=> fix: wd slash interaction

package.json, src/commands/heatmap/index.ts, src/commands/heatmap/index/processor.ts, yarn.lock
=> fix: heatmap

src/adapters/config.ts, src/commands/config/currency/index/processor.ts, src/commands/config/currency/index/slash.ts, src/commands/config/index.ts
-   [x] Config default currency
`/config currency symbol`
=> feat: new default currency

src/commands/new-tip/index/processor.ts
=> fix: calculate amount moniker

src/commands/ticker/index.ts, src/commands/watchlist/index.ts
allow DM for watchlist and ticker
=> chore: allow some DM

src/commands/vault/info/processor.ts, src/utils/common.ts
=> feat: track vault history

src/adapters/defi.ts, src/commands/index.ts, src/commands/swap/index.ts, src/commands/swap/index/processor.ts, src/commands/swap/index/slash.ts, src/types/api.ts, src/utils/common.ts
-   [x] 1st version of /swap command (no wallet select because no mochi wallet + no api to swap yet) so user can only preview route and get redirect to kyberswap
`/swap 1000 eth usdt`
=> feat: swap command

src/commands/new-nft/query/processor.ts
=> fix: format nft icon

src/adapters/defi.ts, src/commands/token/add/slash.ts, src/listeners/discord/ready.ts, src/types/api.ts
-   [x] Change text from `bsc` to `bnb`
=> chore: change bsc to bnb

src/adapters/community.ts, src/commands/index.ts, src/commands/tagme/index.ts, src/handlers/tagme.ts, src/listeners/discord/interactionCreate.ts, src/listeners/discord/messageCreate.ts, src/types/api.ts, src/utils/common.ts
-   [x] Tagme feature
`/tagme`
https://user-images.githubusercontent.com/25856620/230862921-4541951c-7ed7-4460-b341-268ef008cf11.mp4
=> feat: tagme

src/adapters/community.ts, src/commands/tagme/index.ts, src/handlers/tagme.ts, src/types/api.ts
=> chore: simplify tagme

src/handlers/tagme.ts
-   [x] Do not notify user if that user if the one being replied to
=> chore: tagme filter replied user

src/listeners/discord/guildMemberAdd.ts
-   [x] Remove the DM message of Mochi (spammy)
-   [x] Move the push discord webhook call to last to prevent it from interrupting the execution flow
=> chore: some adjustments to new member logic

src/commands/new-tip/index/processor.ts, src/types/api.ts
=> chore: change logic convert token to usd in tip discord

src/adapters/defi.ts, src/commands/swap/index/processor.ts, src/commands/swap/index/slash.ts, src/commands/tagme/index.ts, src/listeners/discord/interactionCreate.ts, src/ui/discord/embed.ts, src/utils/common.ts, src/utils/discord.ts
-   [x] Swap with api
`/swap 10 ftm usdc`
=> feat: swap with mochi api

src/commands/airdrop/index/processor.ts
-   [x] Add max airdrop duration
=> chore: handle max duration

src/commands/new-tip/index/parser.test.ts, src/commands/new-tip/index/processor.test.ts, src/commands/new-tip/index/processor.ts, src/utils/common.ts
-   [x] Add test for tip payload parser
=> chore: add test for new-tip payload parser

src/utils/common.ts
-   [x] Add SAMO, BONK token emoji
=> chore: add SAMO, BONK token emoji

src/commands/airdrop/index/processor.ts, src/types/api.ts
-   [x] Only slice the participants list if `maxEntries` is specified
`$airdrop 10 butt`
=> fix: airdrop slice participants

src/commands/balances/index/processor.ts
-   [x] Show chain name for tokens balance
**Media**
=> feat: balance - show token's chain

src/commands/airdrop/index.ts, src/commands/airdrop/index/processor.ts, src/commands/swap/index/processor.ts, src/utils/common.ts, src/utils/constants.ts, src/utils/defi.ts
-   [x] Show correct amount in airdrop DM message (approximately)
-   [x] Add STG token
-   [x] Airdrop command duration description edit text
=> fix: airdrop dm message incorrect amount

src/commands/swap/index.ts, src/commands/swap/index/processor.ts
-   [x] Disable unsupported chains in swap
=> chore: swap disable uncommon chains

src/adapters/mochi-pay.ts, src/commands/pay/link/text.ts, src/commands/pay/me/processor.ts, src/commands/pay/me/text.ts, src/commands/tip/index/parser.old-test.ts, src/commands/tip/index/processor.ts, src/commands/wallet/new/text.ts, src/errors/insufficient-balance.ts, src/ui/discord/embed.ts, src/utils/tip-bot.ts
=> refactor: tip

src/commands/withdraw/index/processor.ts
-   [x] add chain id to withdraw
+ solana chain
+ evm 
+ multi chain token
+ on-chain
=> feat: add chain id to withdraw

src/commands/airdrop/index/processor.ts, src/commands/airdrop/index/slash.old-test.ts, src/commands/tip/index/processor.ts
-   [x] Somehow I accidentally git stash multiple chains handler for airdrop and clear all stashes. So here's the PR
=> fix: airdrop - token existing on multiple chains

src/commands/tip/index/processor.ts, src/ui/discord/embed.ts, src/utils/common.ts
-   [x] Tip message author's image
-   [x] Add a safety net for emojis that start with `ANIMATED_` to have animated flag
=> chore: cleanup emojis

src/commands/withdraw/index/processor.ts, src/types/api.ts
-   [x] fix withdraw all
- single chain
233054279-58171871-ef61-40df-b251-46a084c0772f.png">
- multiple chain
=> fix: withdraw all

src/commands/withdraw/index/processor.ts
-   [x] remove round float in withdraw when withdraw all
=> fix: remove round float in withdraw

src/commands/tip/index/processor.ts, src/ui/canvas/chart.ts
-   [x] Round scientific notation number
=> fix: ticker very small number

src/adapters/defi.ts, src/commands/index.ts, src/commands/trending/index.ts, src/commands/trending/index/processor.ts, src/commands/trending/index/slash.ts, src/utils/constants.ts
Note: Currently no design for this so just show data first
=> feat: trending search api

src/adapters/defi.ts, src/commands/gainer/index.ts, src/commands/gainer/index/processor.ts, src/commands/gainer/index/slash.ts, src/commands/index.ts, src/commands/loser/index.ts, src/commands/loser/index/processor.ts, src/commands/loser/index/slash.ts, src/types/api.ts, src/utils/constants.ts
=> feat: command gainer loser

src/adapters/mochi-pay.ts, src/adapters/profile.ts, src/commands/index.ts, src/commands/tip/mail/processor.ts, src/commands/tip/telegram/processor.ts, src/commands/tip/twitter/processor.ts, src/commands/transaction/index.ts, src/commands/transaction/index/processor.ts, src/commands/transaction/index/slash.ts
=> feat: list tx

src/commands/airdrop/index/processor.ts, src/commands/tip/index/processor.ts
-   [x] Format usd amount to four digit (tip + airdrop)
=> fix: tip-bot usd format

src/commands/deposit/index/processor.ts
-   [x] Add chain name to deposit DM
`/deposit ftm`
=> chore: add chain name to deposit dm

src/adapters/defi.ts, src/commands/gainer/index/processor.ts, src/commands/loser/index/processor.ts
=> feat: gainer loser for all token

src/commands/gainer/index.ts, src/commands/gainer/index/processor.ts, src/commands/gainer/index/slash.ts, src/commands/loser/index.ts, src/commands/loser/index/processor.ts, src/commands/loser/index/slash.ts, src/listeners/discord/interactionCreate.ts, src/types/api.ts
=> chore: add button for gainer loser

src/commands/pay/link/processor.ts, src/ui/discord/embed.ts
-   [x] show insufficient balance message instead of common error message
**Media**
=> fix: paylink - handle insufficient balance

src/adapters/config.ts, src/commands/airdrop/index/processor.ts, src/commands/balances/index/processor.ts, src/commands/config/index.ts, src/commands/config/maxtipped/index/processor.ts, src/commands/config/maxtipped/index/slash.ts, src/commands/config/minrain/index/processor.ts, src/commands/config/minrain/index/slash.ts, src/commands/config/tiprange/index/processor.ts, src/commands/config/tiprange/index/slash.ts, src/commands/tip/index/processor.ts
New tip range cmds
-   [x] /minrain
-   [x] /maxtipped
-   [x] /tiprange
**Media**
- Config
- behavior with tip
- behavior with airdrop
=> feat: tiprange commands

src/commands/airdrop/index/processor.ts, src/commands/tip/index/processor.ts
=> fix: rounding usd amount in tip and airdrop

src/commands/transaction/index/processor.ts
-   [x] Hide section if empty
|Before|After|
|---|---|
|<img width="387" alt="CleanShot 2023-04-24 at 16 17 42@2x" src="https://user-images.githubusercontent.com/25856620/233954135-c74a96a4-d665-4f90-97aa-5525db3ff879.png">|<img width="400" alt="CleanShot 2023-04-24 at 16 17 48@2x" src="https://user-images.githubusercontent.com/25856620/233954216-8bc5e842-5d22-484a-af98-e1f4aba5dcc1.png">|
=> fix: transaction ui rework

src/commands/airdrop/index/handler.ts, src/commands/airdrop/index/processor.old-test.ts, src/commands/airdrop/index/processor.ts, src/commands/airdrop/index/slash.old-test.ts, src/commands/airdrop/index/slash.ts, src/commands/nft/query/processor.ts, src/commands/nft/ticker/processor.ts, src/commands/tip/index.ts, src/commands/tip/index/processor.ts, src/commands/tip/mail/processor.ts, src/commands/tip/telegram/processor.ts, src/commands/tip/twitter/processor.ts, src/commands/withdraw/index/processor.ts, src/errors/discord-wallet-transfer.ts, src/errors/unsupported-token.ts, src/listeners/discord/interactionCreate.ts, src/types/transfer.ts, src/utils/common.ts, src/utils/discord.ts, src/utils/emoji.ts, src/utils/tip-bot.ts
=> refactor: tip and airdrop

package.json, src/commands/airdrop/index/handler.ts, src/commands/airdrop/index/processor.ts, src/errors/api.ts, src/errors/base.ts, src/ui/discord/embed.ts, src/utils/tip-bot.ts
-   [x] Edit airdrop messages
-   [x] Add missing `entries` text
-   [x] Convert all error except API error to different color
=> fix: airdrop 2

src/adapters/defi.ts, src/commands/gainer/index.ts, src/commands/gainer/index/processor.ts, src/commands/loser/index.ts, src/commands/loser/index/processor.ts, src/types/api.ts
=> refactor: gainer loser

src/commands/airdrop/index/processor.ts, src/commands/tip/index/processor.ts, src/types/api.ts, src/ui/discord/embed.ts
-   [x] Unhandled `DiscordWalletTransferError` -> add `await`
=> fix: tip range error

.eslintrc, src/commands/tip/index/processor.ts, src/types/api.ts
-   [x] Add new rule to warn about no `await` before `async` functions
=> chore: add new eslint rule

src/commands/airdrop/index.ts, src/commands/nft-role/set/slash.ts, src/commands/sendxp/index.ts, src/commands/xp-role/set/slash.ts
-   [x] airdrop entries
-   [x] nft role amount
-   [x] sendxp amount
-   [x] xprole amount
=> chore: use integer option in some commands

src/utils/tip-bot.ts
-   [x] Tip error when target is one of the following `in voice channel`, `voice channel`, `in voice channel`
=> fix: tip voice

src/commands/vault/info/processor.ts, src/commands/vault/list/processor.ts, src/commands/vault/new/processor.ts, src/commands/vault/threshold/processor.ts
- Highlight slash command
- Handle empty case
=> fix: vault empty case

src/commands/airdrop/index/processor.test.ts, src/commands/airdrop/index/processor.ts
-   [x] Add test for airdrop parser
=> chore: add test for airdrop parser

src/commands/tip/mail/processor.ts, src/commands/tip/telegram/processor.ts, src/commands/tip/twitter/processor.ts
=> fix: remove transfer api tip cross plat

src/commands/tip/index.ts, src/commands/tip/mail/processor.ts, src/commands/tip/telegram/processor.ts, src/commands/tip/twitter/processor.ts
Refactor + fix tip cross platform
-   [x] twitter
-   [x] email
-   [x] telegram
**Media**
- Email
- Twitter
- Telegram
=> refactor: tip cross platform

src/commands/tip/index.ts, src/commands/tip/mail/slash.ts, src/commands/tip/telegram/slash.ts, src/commands/tip/twitter/slash.ts
-   [x] Slash commands for tip cross-platfrom: telegram, twitter, mail
=> feat: slash cmd - tip cross platform

src/adapters/mochi-telegram.ts, src/commands/pay/me/processor.ts, src/commands/tip/telegram/processor.ts
-   [x] Update tip telegram + pay me: Use new endpoint from mochi-telegram to get telegram user info by username
=> fix: get telegram user

src/errors/base.ts, src/errors/command-not-scoped.ts
-   [x] assign message/interaction to Error obj
-   [x] add handle method for CommandIsNotScopedError
=> fix: error

src/commands/tip/index/processor.ts
Tip amount usd not divide for number of recipients
- Old -> 1 ftm ~ $0.39
- New
=> fix: amount usd for each rep

src/adapters/fetcher.ts, src/errors/base.ts, src/listeners/discord/guildCreate.ts, src/listeners/discord/guildDelete.ts, src/listeners/discord/guildMemberAdd.ts, src/listeners/discord/guildMemberRemove.ts, src/listeners/discord/interactionCreate.ts, src/listeners/discord/messageCreate.ts, src/listeners/discord/messageDelete.ts, src/listeners/discord/messageReactionAdd.ts, src/listeners/discord/messageReactionRemove.ts, src/utils/async-storages.ts
-   [x] add metadata to kafka msg in discord events
=> chore: add metadata to kafka msg in discord events

src/adapters/config.ts, src/commands/vault/new/processor.ts
- Gen wallet when desig mode = false -> default is false
- Vault info show real wallet
=> chore: vault use real wallet address

src/adapters/config.ts, src/commands/vault/index.ts, src/commands/vault/remove/processor.ts, src/commands/vault/transfer/processor.ts, src/commands/vault/transfer/slash.ts, src/listeners/discord/interactionCreate.ts
https://www.loom.com/share/133cb9afdca24317b29fb29434bc37db
=> feat: treasurer transfer

src/commands/profile/index/processor.ts
-   [x] Role in profile command
=> fix: profile role

src/commands/tip/index/processor.ts
=> fix: each parsing

src/adapters/config.ts, src/commands/vault/transfer/processor.ts, src/commands/vault/transfer/slash.ts
https://www.loom.com/share/4d649ae1b2624d06bc9009bdf745637b
=> feat: treasurer transfer send money

src/commands/vault/info/processor.ts, src/commands/vault/list/processor.ts, src/commands/vault/transfer/processor.ts, src/utils/common.ts
=> chore: update some vault ui

src/commands/airdrop/index/handler.ts, src/commands/airdrop/index/processor.ts, src/commands/tip/index/processor.ts, src/commands/tip/mail/processor.ts, src/commands/tip/telegram/processor.ts, src/commands/tip/twitter/processor.ts, src/types/transfer.ts
-   [x] fix: tip amount showing wrong USD value
**Media**
=> fix: tip - wrong USD amount

src/commands/vault/add/processor.ts, src/commands/vault/channel/processor.ts, src/commands/vault/info/processor.ts, src/commands/vault/list/processor.ts, src/commands/vault/new/processor.ts, src/commands/vault/remove/processor.ts, src/commands/vault/threshold/processor.ts, src/commands/vault/transfer/processor.ts, src/utils/common.ts
requirement: https://www.notion.so/console-labs/Vault-UI-ab0504f392294b9db1ad57565ef05c22#ad168bda12284493b4935708892cd4e4
=> fix: ui vault

src/commands/vault/info/processor.ts, src/commands/vault/list/processor.ts
=> chore: update thumbnail vault

src/commands/convert/index.ts, src/commands/convert/index/processor.ts, src/commands/convert/index/text.ts, src/commands/index.ts, src/commands/reaction-role/set/processor.test.ts, src/commands/reaction-role/set/processor.ts, src/errors/base.ts, src/utils/wrap-error.ts
-   [x] fix kafka msg + reaction role set msg
=> backmerge develop

src/commands/ticker/index/processor.ts, src/commands/ticker/index/slash.ts, src/commands/ticker/index/text.ts, src/ui/canvas/color.ts, src/ui/discord/select-menu.ts
-   [x] $ticker: support btc dominance chart
**Media**
=> feat: ticker btc.d

src/adapters/config.ts, src/commands/vault/transfer/processor.ts, src/commands/vault/transfer/slash.ts
behaviour of transfer by address the same transfer to user
=> feat: transfer vault by address

src/commands/vault/new/processor.ts, src/commands/vault/threshold/processor.ts
-   [x] add vault not found message
=> chore: add vault not found message

src/adapters/fetcher.ts, src/adapters/mochi-pay.ts, src/commands/airdrop/index.ts, src/commands/airdrop/index/handler.ts, src/commands/airdrop/index/processor.test.ts, src/commands/airdrop/index/processor.ts, src/types/transfer.ts, src/utils/common.ts
=> feat: new airdrop qr command

src/commands/profile/index/processor.ts, src/utils/common.ts
-   [x] Show connected wallets in profile
=> chore: show connect wallets in profile

src/adapters/fetcher.ts, src/env.ts
-   [x] Attach API key for mochi-pay's requests
=> feat: mochi-pay authorization

src/adapters/config.ts, src/commands/bot-manager/index.ts, src/commands/bot-manager/info/slash.ts, src/commands/bot-manager/processor.ts, src/commands/bot-manager/remove/slash.ts, src/commands/bot-manager/set/slash.ts, src/commands/index.ts, src/listeners/discord/interactionCreate.ts
-   [x] set, remove, info admin role
-   [x] check admin role config for command
- `/bot-manager set`
- `/bot-manager remove`
- `/bot-manager info`
=> feat: set guild admin role

src/adapters/defi.ts, src/commands/index.test.ts, src/commands/ticker/index.ts, src/commands/ticker/index/processor.ts, src/commands/ticker/index/slash.ts, src/commands/ticker/index/text.ts, src/types/api.ts
- this is used to support case $tick pepe brc20 only, so the param "chain" i will set to optional
- update bot first to send param "chain" to api, phucnh will update api later
=> feat: support chain ticker for brc20

src/commands/convert/index/processor.ts, src/commands/ticker/compare-token/processor.ts, src/listeners/discord/interactionCreate.ts
-   [x] Fix `/convert` (show invalid data when multiple tokens with duplicated symbol found): Show token selection
**Media**
=> fix: token price conversion

src/errors/command-not-allowed.ts
-   [x] edit the message of not-allowed-command error (I guess it looks like bug error because of the sad neko emoji)
=> chore: edit msg of not allowed command

src/commands/vault/add/processor.ts, src/commands/vault/add/slash.ts, src/commands/vault/info/processor.ts, src/commands/vault/remove/processor.ts, src/commands/vault/remove/slash.ts, src/commands/vault/transfer/processor.ts, src/commands/vault/transfer/slash.ts, src/utils/vault.ts
Khôi tạo request thêm Huy vô vault (66%)
+ Lúc này chỉ có Khôi là treasurer -> số approve là 1/1 = 100 % -> add luôn 
+ Khôi tiếp tục tạo request thêm Minh vô -> lúc này số approve chỉ là 1/2 (do Huy chưa approve) -> đợi Huy bấm nút -> ... -> flow như cũ
=> chore: enhance vault logic

src/commands/profile/index/processor.ts
-   [x] Add hidden character to avoid empty value error in Discord
=> fix: empty embed value in profile

src/commands/withdraw/index/processor.ts
=> fix: fix withdraw dm when bot can't dm

src/commands/nft/query/processor.ts
-   [x] add message when nft not found
=> fix: add message when nft not found

src/commands/vault/info/processor.ts, src/commands/vault/new/processor.ts
=> feat: vault transfer solana

src/commands/vault/new/processor.ts
=> chore: limit vault name 24 char

src/commands/airdrop/index/handler.ts, src/commands/pay/me/processor.ts, src/commands/proposal/processor.ts, src/commands/swap/index/processor.ts, src/commands/withdraw/index/processor.ts, src/types/api.ts, src/utils/dm.ts
-   [x] write dm usse common function
=> chore: add dm user common function

src/adapters/config.ts
=> fix: vault list no fetch amount

src/commands/ticker/index/processor.ts, yarn.lock
=> feat: ticker add platform

src/types/defi.ts
=> fix: fix ticker platform

.gitignore, src/adapters/profile.ts, src/utils/common.ts
-   [x] get sui wallet assets and txns
=> chore: get sui wallet info

src/adapters/defi.ts, src/commands/wallet/add/processor.ts, src/commands/wallet/track/processor.ts
-   [x] Update track wallet request based on API changes
=> fix: wallet track

src/commands/ticker/index/processor.ts
-   [x] $ticker: show chain abbr instead of full name
**Media**
=> fix: ticker - chain abbreviation

src/commands/vault/info/processor.ts
Update logic for filtering out spammy tokens
=> fix: filter out spammy txns

src/commands/qr/index/processor.ts
-   [x] Add handle save apple wallet passes
https://github.com/consolelabs/mochi-discord/assets/28944972/50d05fef-4417-45a8-8dc1-c4bc86a59c12
=> chore: init gen pkpass file

src/commands/wallet/common/tracking.ts, src/commands/wallet/copy/processor.ts, src/commands/wallet/copy/slash.ts, src/commands/wallet/follow/processor.ts, src/commands/wallet/follow/slash.ts, src/commands/wallet/remove/processor.ts, src/commands/wallet/track/processor.ts, src/commands/wallet/track/slash.ts, src/utils/router.ts
-   [x] Add states and map all button for tracking wallet follow
- Follow successfully: `Watchlist`,  `Track`, `Copy`, `Unfollow`
- Track successfully: `Watchlist`,  `Follow`, `Copy`, `Untrack`
- Copy successfully: `Watchlist`,  `Follow`, `Trade`, `Uncopy`
=> feat: add full states for tracking wallet flow

src/commands/wallet/common/tracking.ts
=> fix: wallet track states

src/adapters/config.ts, src/listeners/discord/interactionCreate.ts, src/types/api.ts
- random show fact and tip for commands
=> feat: create content for reminder

src/adapters/config.ts, src/listeners/discord/interactionCreate.ts, src/ui/discord/embed.ts
- move tip advice to footer instead of header
=> chore: tip to footer

src/commands/vault/transfer/processor.ts, src/utils/vault.ts
=> chore: update transfer vault msg

src/commands/balances/index/slash.ts, src/utils/common.ts
-   [x] Query .sol domain: get rid of deprecated functions
=> chore: adapt deprecated functions

src/utils/router/index.ts
=> fix: edit msg router

src/adapters/community.ts, src/adapters/fetcher.ts, src/commands/drop/available/index.ts, src/commands/drop/available/processor.ts, src/commands/earn/index/processor.ts, src/types/api.ts
-   [x] Binding airdrop campaign list
-   [x] Binding airdrop campaign stats
=> feat: binding campaign list and stats

src/cache/tip-fact-cache.ts
=> fix: footer

src/adapters/community.ts, src/commands/drop/available/index.ts, src/commands/drop/available/processor.ts, src/types/api.ts
-   [x] Binding campaign detail and set status API
=> feat: binding campaign detail

src/commands/balances/index/processor.ts
-   [x] Wallet details: show farming rewards and staking info
**Media**
=> feat: wallet staking data

scripts/generate-types.js, src/adapters/community.ts, src/adapters/fetcher.ts, src/commands/index.ts, src/commands/invest/index.ts, src/commands/invest/index/processor.ts, src/commands/invest/token/processor.ts, src/listeners/discord/interactionCreate.ts, src/types/krystal-api.ts
-  [x] Invest homepage
-  [x] Invest by token
-   Type `/invest` to see all earning options 
-  Type `/invest eth` to see all earning options for *ETH*
=> feat: invest command

src/ui/discord/embed.ts
=> fix: divider

src/commands/balances/index/processor.ts
=> fix: own wallet bug

src/commands/balances/index/processor.ts, src/ui/discord/embed.ts
=> fix: expand earn

src/listeners/discord/messageReactionAdd.ts
-   [x] update params for trigger react event
=> feat: auto trigger

src/commands/tip/index/processor.ts
-   [x] Show `Tx ID` when tip successfully
**Media**
=> feat: tip - show tx id

package.json, src/adapters/fetcher/index.ts, src/commands/balances/index/processor.ts, yarn.lock
=> feat: show binance earn

scripts/generate-types.js, src/commands/role/token/processor.ts, src/types/api.ts
-   [x] add field next_sync in minutes to cmd get list role token
-   run cmd `/role token list` 
=> chore: add field next_sync to cmd get list role token

.github/workflows/gke-dev.yml, .github/workflows/gke-prod.yml, .github/workflows/test.yml, Dockerfile, src/types/api.ts
-   [x] update github action test to use swagger_url dev
-   [x] update Dockerfile to allow discord dev to use swagger dev
=> ci: update github action test

src/adapters/profile.ts, src/commands/balances/index/processor.ts, src/commands/balances/index/slash.ts, src/types/api.ts, src/utils/common.ts, src/utils/profile.ts
=> feat: unlink wallet

src/commands/balances/index/processor.ts
=> chore: hide unlink wallet button

src/commands/wallet/alias/set/processor.ts, src/commands/wallet/copy/processor.ts, src/commands/wallet/follow/processor.ts, src/commands/wallet/track/processor.ts, src/commands/wallet/untrack/processor.ts
-   [x] Resolve name service domain before process `/wallet` cmds
=> fix: resolve name service domain

src/adapters/community.ts, src/commands/drop/available/processor.ts, src/commands/drop/index.ts, src/commands/drop/search/index.ts, src/commands/drop/search/processor.ts, src/commands/earn/index/processor.ts
-   [x] Create sub command `/drop search [keyword]`
-   type `/drop search space id ` to search airdrops have space id in description or title
-   type `/drop search #34` to search airdrop have id **34**
=> feat: search airdrop campaign

src/commands/activity/index/processor.ts
-   [x] reformat activity view
=> chore: reformat activity view

src/commands/balances/index/processor.ts
-   [x] Fix: Total onchain balance - not include farm + stake total
=> fix: wrong total onchain balance

src/commands/activity/index/processor.ts, src/commands/activity/index/slash.ts, src/commands/balances/index/processor.ts
-   [x] add pagination for activity cmd
=> chore: add pagination activity cmd

src/adapters/profile.ts, src/commands/inbox/index.ts, src/commands/inbox/index/processor.ts, src/commands/inbox/index/slash.ts, src/commands/inbox/index/text.ts, src/commands/index.ts, src/commands/profile/index/processor.ts
-   [x] correct number of read / unread msg
=> refactor: correct /inbox behavior

package.json
=> chore: add watch flag

src/listeners/discord/interactionCreate.ts
=> fix: remove timeout

src/adapters/mochi-pay.ts, src/commands/balances/index/processor.ts, src/commands/vault/info/processor.ts
=> chore: add bals swap tx

src/commands/balances/index/processor.ts, src/commands/vault/info/processor.ts
-   [x] fix render data swap tx
=> chore: fix bug swap render data

.github/workflows/gke-prod.yml, yarn.lock
-   [x] release v1 will update discord-v2 as well
=> chore: update mochi-discord cd v2

src/commands/activity/index/processor.ts, src/utils/activity.ts
-   [x] Update render activities cmd
=> chore: update render activity cmd

src/adapters/config.ts
-   [x]  fix create new group nft role
=> fix: config role nft

src/adapters/config.ts, src/commands/role/nft/remove/processor.ts, src/types/api.ts
=> fix: remove nft role

src/commands/inbox/index/processor.ts
-   [x] Handle inbox with new response
=> chore: handle mark read activity

src/adapters/chotot.ts, src/commands/chotot/index.ts, src/commands/chotot/index/processor.ts, src/commands/index.ts, src/utils/constants.ts
-   [x] Search with auto-complete from Chotot
-   Type `/chotot [keywords]`
-   Select from the suggested results
- Select the ad want to see detail
**Edge cases**
=> feat: chotot

src/adapters/config.ts
-   [x]  list vault for /profile dm
=> chore: list vault in profile dm

package.json, pnpm-lock.yaml, src/env.ts, src/types/api.ts, src/utils/wrap-error.ts
=> chore: add sentry

src/adapters/profile.ts, src/commands/inbox/index/processor.ts, src/types/api.ts, yarn.lock
=> chore: update inbox

src/commands/wallet/view/address/slash.ts, src/commands/wallet/view/profile/slash.ts
=> fix: wallet view - NaN total

src/commands/wallet/view/address/slash.ts, src/listeners/discord/interactionCreate.ts
=> fix: unknown interaction

src/listeners/discord/messageReactionAdd.ts
=> fix: message reaction add

src/listeners/discord/messageReactionAdd.ts
=> fix: reaction add unknown user

src/commands/profile/index/processor.ts
-   [x] filter vault which has server name when dm /profile
=> chore: filter vault

src/adapters/profile.ts, src/commands/activity/index/processor.ts, src/commands/inbox/index/processor.ts, src/commands/profile/index/processor.ts
=> chore: remove usage of count activities api

src/commands/deposit/index/processor.ts, src/commands/deposit/index/slash.ts, src/commands/vault/info/slash.ts
Deep links for deposit addresses:
-   [x] EVM -> metamask
**Media**
1. EVM -> Metamask:
2. Not EVM:
=> fix: deposit list - deep links

src/commands/deposit/index/processor.ts
-   [x] /deposit: embed deeplink in details view
=> fix: deposit deeplink

src/adapters/config.ts, src/types/api.ts
=> fix: role level set

src/commands/ticker/index/processor.ts
=> fix: render wl fiat

src/commands/nft/add/processor.ts, src/commands/nft/integrate/processor.ts, src/commands/nft/processor.ts
=> fix: nft add msg id

src/adapters/mochi-pay.ts, src/commands/invest/claim-rewards/slash.ts, src/commands/invest/index.ts, src/commands/invest/portfolio/slash.ts, src/commands/invest/stake/slash.ts, src/commands/invest/status/slash.ts, src/commands/invest/unstake/slash.ts, src/types/mochipay.ts
-   [x] Add unstake and claim command
- `/invest unstake`
- `/invest claim`
=> feat: invest unstake and claim

src/adapters/mochi-pay.ts, src/commands/transfer_request/index/processor.ts, src/listeners/discord/interactionCreate.ts, src/types/api.ts, src/utils/profile.ts
=> feat: transfer request notification

src/commands/invest/portfolio/slash.ts, src/commands/profile/index/processor.ts, src/commands/profile/index/slash.ts, src/types/api.ts
-   [x] Add invest portfolio view to profile
- use `/profile`
=> feat: add invest portfolio to profile

.husky/pre-commit, src/adapters/defi.ts, src/commands/ticker/index/processor.ts, src/commands/ticker/index/slash.ts, src/types/api.ts
=> chore: add geckoterminal info

.husky/pre-commit, src/commands/ticker/index/processor.ts, src/types/api.ts
=> chore: update token info view

src/commands/transfer_request/index/processor.ts, src/types/api.ts
-   [x] Handle transfer request error: expired or not found
**Media**
=> fix: handle transfer request error

.husky/pre-commit, src/commands/ticker/index/processor.ts, src/types/api.ts
=> chore: token info show only 3 explorers

src/commands/ecocal/view/processor.ts
-   [x] add action button if ecocal view is empty
**Edge cases**
=> feat: add action button if ecocal view is empty

src/commands/ticker/index/slash.ts, src/commands/watchlist/add/processor.ts, src/types/api.ts
-   [x]  add ticker watchlist to ticker and token info
- /token info
- after click * btn
=> fix: watch list token

src/commands/index.ts, src/env.ts, src/listeners/discord/interactionCreate.ts, src/queue/kafka/index.ts
=> chore: send audit log

src/adapters/defi.ts, src/commands/tip/index/processor.ts, src/types/api.ts
-   [x] /tip command: migrate to `/transfer-v2` API
=> chore: transfer v2 migration

src/commands/gainer/index/slash.ts, src/commands/loser/index/slash.ts, src/types/api.ts
-   [x] check gainer and loser command
=> fix: check gainer and loser command

src/commands/airdrop/index/handler.ts
-   [x] /airdrop: migrate to transfer-v2 API
=> chore: airdrop - transfer v2 migration

src/commands/convert/index/processor.ts, src/commands/invest/stake/slash.ts, src/types/api.ts
-   [x] fix: sentry issue 24 & 202 & 203
=> fix: type error convert and stake

src/commands/balances/index/processor.test.ts, src/commands/convert/index/processor.ts
-   [x] Fix [sentry 200](https://sentry.daf.ug/organizations/dwarves-foundation/issues/200/)
-   [x] Update balance test case
=> fix: [sentry-200] convert command type error

src/commands/chotot/index.ts
-   [x] fix [sentry-199](https://sentry.daf.ug/organizations/dwarves-foundation/issues/199): This happen when the url doesnt start with https
=> fix: [sentry-199] chotot type error

src/commands/guess/end/slash.ts, src/commands/guess/new/slash.ts, src/commands/guess/view/slash.ts
-   [x] fix [sentry-133](https://sentry.daf.ug/organizations/dwarves-foundation/issues/133), [sentry-134](https://sentry.daf.ug/organizations/dwarves-foundation/issues/134), [sentry-183](https://sentry.daf.ug/organizations/dwarves-foundation/issues/183) guess game type error
=> fix: [sentry-133][sentry-134][sentry-183] guess game type error

src/commands/pay/link/processor.ts
=> fix: check pay link

src/commands/ticker/index/processor.ts, src/commands/transaction/index/processor.ts
-   [x] check type error transaction
=> fix: check type error transaction

src/commands/airdrop/index/handler.ts
-   [x]  fix [[sentry-217](https://sentry.daf.ug/organizations/dwarves-foundation/issues/217)] airdrop interaction already replied
=> fix: [sentry-217] airdrop interaction already replied

src/adapters/mochi-pay.ts, src/commands/withdraw/index/processor.ts, src/utils/constants.ts
-   [x] /withdraw: migrate to withdraw v2 API
=> chore: withdraw-v2 migration

src/commands/guess/end/slash.ts
-   [x] fix [[sentry-215]](https://sentry.daf.ug/organizations/dwarves-foundation/issues/215) guess game choice error
=> fix: [sentry-215] guess game choice error

src/commands/tip/index/processor.ts, src/types/transfer.ts
=> fix: transfer v2

package.json, src/adapters/mochi-pay.ts, src/commands/balances/index/processor.test.ts, src/commands/balances/index/processor.ts, src/commands/transaction/index/processor.ts, src/commands/transaction/index/slash.ts, src/utils/formatter.ts, yarn.lock
-   [x] Fix transaction data shape  (effected feat: `/bal`, `/transaction`)
- `/bal`
- `/transaction`
**Image**
=> fix: transaction data shape

src/adapters/profile.ts, src/commands/pay/me/processor.ts, src/commands/pay/me/slash.ts, src/types/common.ts, src/utils/kafka.ts
-   [x] Handle payme with reciept and platform
=> chore: add handle noti for pay-request

src/adapters/mochi-guess.ts, src/commands/guess/choice/slash.ts, src/commands/guess/end/slash.ts, src/commands/guess/new/slash.ts, src/commands/guess/view/slash.ts, src/utils/formatter.ts
=> chore: improve guess game

.releaserc, package.json, pnpm-lock.yaml
=> ci: update semantic cfg

src/adapters/mochi-pay.ts, src/commands/pay/link/processor.ts, src/commands/pay/me/processor.ts, src/commands/tip/mail/processor.ts, src/commands/tip/telegram/processor.ts, src/commands/tip/twitter/processor.ts, src/commands/wallet/new/processor.ts, src/types/api.ts
- Update request to adapt paylink & payme API changes
=> chore: pay-request v2 migration

src/adapters/defi.ts, src/commands/token/index.ts, src/commands/token/verbose/slash.ts, src/types/api.ts
=> feat: token verbose

src/commands/guess/choice/slash.ts, src/commands/guess/end/slash.ts, src/commands/guess/new/slash.ts
=> feat: move game thread to channel

src/commands/token/verbose/slash.ts
=> fix: fix fail dexpair type (#1467)

src/adapters/defi.ts, src/commands/token/verbose/slash.ts, src/types/api.ts
=> fix: fix fail dexpair type

src/adapters/profile.ts, src/listeners/discord/messageCreate.ts, src/types/api.ts
-   Update param: no-fetch-amount -> no_fetch_amount (get profile by discord/telegram)
=> fix: no_fetch_amount param

.github/workflows/test.yml, package.json, pnpm-lock.yaml, src/api.ts, src/commands/airdrop/index/handler.ts, src/commands/index.ts, src/commands/sup/index.ts, src/index.ts, src/utils/common.ts
=> feat(sup): what's new command for user to check out latest changelog

.husky/pre-commit, .husky/prepare-commit-msg, src/adapters/mochi-pay.ts, src/commands/balances/index/processor.ts, src/commands/pay/link/processor.ts, src/commands/pay/me/processor.ts, src/types/api.ts
- /paylink, /payme: update request payload to adapt changes from API
- /bals: update recent txns - only show `success` txns
=> fix: pay request payload

src/commands/guess/end/slash.ts, src/commands/guess/new/slash.ts
=> fix: move question to embed field

pnpm-lock.yaml, src/adapters/mochi-guess.ts, src/commands/guess/new/slash.ts
=> fix: highlight guess game question

src/commands/tip/index/processor.ts, src/types/transfer.ts
=> feat(tip): show moniker in tip message

src/adapters/config.ts, src/commands/tip/index/processor.ts
=> feat(tip): show hashtag template in tip

src/commands/tip/index/processor.ts, src/types/api.ts, src/types/transfer.ts
-   [x] add discord channel to tip noti
=> fix(tip): show discord channel to tip noti

src/commands/airdrop/index/processor.ts
-   [x] add channel info for notification airdrop
=> fix(airdrop): add channel info for notification airdrop

src/commands/airdrop/index/handler.ts, src/types/transfer.ts
-   [x] Update airdrop related messages
- `/airdrop`
=> fix(airdrop): update airdrop messages

src/commands/airdrop/index/handler.ts
-   [x] Change emoji + color of airdrop msg when user joining
-   [x] Remove send dm to participants after airdrop end, since we already send notification through mochi-notification service
=> fix(airdrop): update styling airdrop dm message

src/commands/profile/index/processor.ts
=> fix: optimize profile cmd

src/commands/airdrop/index/processor.ts
-   [x] pass channel url to tip
=> refactor: pass channel url to tip

src/commands/tip/index/processor.ts
-   [x] update  import in tip processo
=> refactor: import in tip processor

src/adapters/profile.ts, src/commands/pay/me/processor.ts, src/commands/pay/me/slash.ts, src/types/common.ts, src/ui/discord/embed.ts, src/utils/constants.ts
-   [x] fix payme cmd in discord platform
**Command**
**Result**
**Noti**
=> fix(payme): fix payme cmd allow send payme request in discord platform

src/commands/ticker/index/processor.ts, src/commands/vault/threshold/processor.ts, src/commands/wallet/view/profile/slash.ts
-   [x] Fix type error ticker
-   [x] fix type error vault threshold
-   [x] fix type error wallet view profile
=> chore(general): fix type error

src/commands/airdrop/index/processor.ts, src/commands/tip/index/processor.ts, src/utils/discord.ts
-   [x] Update notification channel format more readable
=> fix(notification): update notification channel format more readable

src/listeners/discord/guildCreate.ts, src/listeners/discord/guildDelete.ts, src/listeners/discord/guildMemberAdd.ts, src/listeners/discord/guildMemberRemove.ts, src/listeners/discord/messageCreate.ts, src/listeners/discord/messageDelete.ts, src/listeners/discord/messageReactionAdd.ts, src/listeners/discord/messageReactionRemove.ts
-   [x] remove discord webhook
=> refactor(webhook): remove discord webhook

src/listeners/discord/ready.ts
-   [x] use mochi api for getting gas price
=> refactor(gas-presense): use mochi api for getting gas price

.github/workflows/test.yml, src/utils/wrap-error.ts
-   [x] update sentry context: add user, cmd that caused bug
=> chore(sentry): update sentry context

package.json, pnpm-lock.yaml, src/adapters/mochi-pay.ts, src/commands/pay/index.ts, src/commands/pay/link-status/processor.ts, src/commands/pay/link-status/slash.ts, src/commands/pay/me-status/processor.ts, src/commands/pay/me-status/slash.ts, src/types/api.ts
-   [x] Add payme - paylink cmd
=> feat(pay): add payme and paylink status cmd

package.json, pnpm-lock.yaml, src/commands/pay/link-status/processor.ts, src/commands/pay/me-status/processor.ts, src/types/common.ts
-   [x] fix render payme paylink status list cmd
=> fix(pay): fix render ui cmd payme paylink status

src/types/api.ts, src/utils/wrap-error.ts
-   [x] add app version to sentry context
=> chore(sentry): add app version to sentry context

src/listeners/discord/messageCreate.ts
=> fix(gm): brings gm back

src/commands/help/index/slash.ts, src/commands/nft/query/processor.ts, src/commands/nft/query/text.ts, src/commands/nft/ticker/processor.ts, src/commands/pay/me/processor.ts, src/commands/quest/daily/processor.ts, src/commands/sales/remove/processor.ts, src/commands/setup/processor.ts, src/handlers/tagme.ts, src/utils/default-setters.ts, src/utils/dm.ts
-   [x] Add await to catch error properly
=> chore(general): handle log error

src/commands/help/index/slash.ts
=> chore(general): handle catch error

src/adapters/fetcher/index.ts, src/types/api.ts
-   [x] Fix redis connection issue `Connection is closed`
=> fix: redis connection

package.json
-   [x] Upgrade packages version: mochi-rest and mochi-ui
=> feat: upgrade mochi packages

src/adapters/defi.ts, src/env.ts
- Add authorization header for transfer-v2
=> fix: transfer-v2 authorization

src/index.ts
-   [x] handle uncatch exception error
=> chore: handle uncatch exception error

scripts/sync-commands.js, src/adapters/unleash/types.ts, src/adapters/unleash/unleash.ts, src/index.ts, src/utils/slash-command.ts
-   [x] sync commands from unleash to reg global command
-   pnpm cmd:sync
- make start: to test event onchange from Unleash
=> fix: sync commands from unleash to reg global command

src/commands/tip/index/processor.ts, src/types/transfer.ts
=> fix: track tx channel avatar

src/utils/slash-command.ts
-   [x] Fix: sync guild slash commands
=> fix: sync commands

package.json, pnpm-lock.yaml, src/api.ts
-   [x] Fix: apply auth for @consolelabs/mochi-rest
=> fix: mochi-rest auth

src/handlers/tagme.ts, src/listeners/discord/messageCreate.ts
-   [x] handle tag me error and remove gm
=> fix: handle tag me error and remove gm

src/adapters/unleash/unleash.ts, src/index.ts, src/utils/slash-command.ts
-   [x] fix bug that unleash does not trigger to sync global / guild command correctly
=> fix: fix unleash not trigger to redeploy cmds correctly

src/listeners/discord/messageReactionAdd.ts, src/listeners/discord/messageReactionRemove.ts
-   [x] bring reaction role back
=> fix: bring reaction role back

package.json, pnpm-lock.yaml, src/adapters/fetcher/utils.ts, src/adapters/mochi-pay.ts, src/commands/transfer_request/index/processor.ts, src/env.ts
- Transfer request button interaction handler: attach application headers to mochi-pay requests
=> fix: transfer request interaction

src/handlers/tagme.ts, src/listeners/discord/messageCreate.ts
-   [x] mochi should not show eror when tagme fail
=> fix: mochi should not show eror when tagme fail

package.json, pnpm-lock.yaml
=> fix: update dependencies

.husky/prepare-commit-msg, src/adapters/fetcher/index.ts
- Refactored Redis connection logic to support Redis sentinel
- Updated Redis connection URL including the `REDIS_MASTER_NAME` and `REDIS_HOST`
=> feat: refactor Redis connection and error handling

src/adapters/fetcher/index.ts
-   [x] mochi should not show error to user if background task fail
=> fix: mochi should not show error to user if background task fail

src/listeners/discord/messageCreate.ts
-   [x] mochi should handle gm
=> fix: mochi should handle gm

src/commands/withdraw/index/processor.ts
-> current prod: not handle this case
=> fix: handle withdraw all

src/commands/tip/index/processor.ts
=> fix: handle null

src/commands/tip/index/processor.ts
-   [x] handle error for follow tip
=> fix(follow-tip): handle error

package.json, pnpm-lock.yaml
-   [x] update typing for transaction
=> fix: update typing for transaction

src/commands/tip/index/processor.ts, src/listeners/discord/interactionCreate.ts
=> fix: allow multiple follow tip

src/commands/tip/index/processor.ts
=> fix: bump ver

package.json, pnpm-lock.yaml
-   [x] update package.json to use mochijs latest version
=> feat: update package.json to use mochijs latest version

package.json, pnpm-lock.yaml
-   [x] update transaction time format
=> fix: update transaction time format

src/commands/tip/index/processor.ts
-   [x] update correct balance when follow tip
=> fix(follow-tip): update correct balance when follow tip

src/commands/pay/me/processor.ts
=> fix(payme): update pay me notify

src/commands/tip/mail/processor.ts
-   [x]  add missing token_id field when send tp through email
=> fix: add missing token_id field when send tip through email

src/commands/tip/mail/processor.ts
=> feat: migrate tip email with new method

src/commands/tip/index.ts, src/commands/tip/mail/processor.ts
=> fix: sp tip email without prefixes

src/commands/tip/index.ts, src/commands/tip/mail/processor.ts
=> fix: validate tip email argument

src/commands/ticker/index/processor.ts, src/commands/watchlist/view/processor.ts
=> fix: update cache ttl watchlist view

src/adapters/defi.ts, src/commands/watchlist/view/processor.ts
-   [x] update wlv sort pagination logic
=> fix(watchlist-view): update wlv sort pagination logic

src/commands/ticker/index/processor.ts
-   [x] ticker parse type error
=> fix(ticker): parse type error

src/commands/tip/index/processor.ts
-   [x] update channel name metadata
=> fix(tip): update channel name metadata

src/commands/balances/index/processor.ts, src/commands/transaction/index/processor.ts
-   [x] show correct actor of transactions
=> fix(transactions): show correct actor of transactions

src/commands/tip/index/processor.ts
-   [x] update formatter render for join tip
=> fix(tip): update formatter render for join tip

package.json, pnpm-lock.yaml, src/commands/changelog/index.ts, src/types/api.ts
-   [x]  update changelog component
=> fix(changelog): update changelog component

src/commands/ticker/index/processor.ts, src/commands/ticker/index/slash.ts, src/ui/discord/select-menu.ts
=> fix(ticker): allow query other ticker option

src/ui/discord/select-menu.ts
=> fix(ticker): change label select other ticker

package.json, pnpm-lock.yaml
-   [x] handle bold case for changelog component
=> fix(changelog): handle bold case

src/commands/balances/index/processor.ts
=> fix(profile): remove simple binance balance

src/commands/tip/index/processor.ts, src/types/api.ts
-   [x] fix case follow tips with multiple recipients
=> fix(follow-tips): fix follow tips with case multiple recipients

package.json, pnpm-lock.yaml, src/commands/ticker/index/slash.ts, src/index.ts
-   [x] remove amount sign in feed transaction
=> fix(feed): remove amount sign in feed transaction

src/adapters/mochi-pay.ts, src/commands/transfer_request/index/processor.ts
=> fix: transfer request - adopt new endpoints

src/commands/airdrop/index/processor.ts
-   [x] update transfer data for airdrop command
=> fix(airdrop): update transfer data for airdrop command

src/commands/airdrop/index/processor.ts
-   [x] bump version formatter
=> fix: bump version formatter

src/commands/tip/index/processor.ts, src/types/api.ts
-   [x] fix render correct users receiver name in follow tip
=> fix(tip): render correct user displayname in follow tip

src/commands/tip/index/processor.ts
=> fix(tip): handle case type error

src/commands/airdrop/index/processor.ts
-   [x] update guild avatar data
=> fix(airdrop): update guild avatar data

package.json, pnpm-lock.yaml, src/commands/feed/index.ts, src/index.ts, src/types/api.ts
-   [x] update format feed transaction
=> fix(feed): update format feed transaction

src/commands/transaction/index/processor.ts
-   [x] remove groupdate transaction
=> fix(transaction): remove groupdate

src/utils/tip-bot.ts
=> fix: tip - parse amount starts with dot

src/commands/tip/index/processor.ts
-   [x] Handle undefine usdAmount when tip
=> fix: handle undefine value when tip

package.json, pnpm-lock.yaml
-   [x] render sibling transactions
=> fix(transaction): render sibling transactions

src/adapters/mochi-api.ts, src/commands/changelog/index.ts, src/commands/profile/index/processor.ts
-   [x] add new unread changelog
+ add create changelog views when user use `/changelog` command
+ get latest changelog and check user have read latest changelog
=> fix(profile): add new unread changelog

package.json, pnpm-lock.yaml
-   [x] chaneglog: handle parse list item
=> fix(changelog): handle parse list item

src/commands/tip/index/processor.ts
=> fix(tip): update ui join tip

pnpm-lock.yaml, src/commands/changelog/index.ts
-   [x]  Changelog content exceed max length
=> fix(changelog): content exceed max length

src/commands/tip/index/processor.ts
-   [x] handle format tip number amount
=> fix(tip): handle tip amount format number

src/commands/changelog/index.ts, src/index.ts
=> fix(changelog): prettify changelog

src/adapters/mochi-api.ts, src/commands/changelog/index.ts, src/env.ts, src/listeners/discord/interactionCreate.ts
-   [x] handle public changelog event
=> fix(tip): handle public changelog event

package.json, pnpm-lock.yaml, src/commands/changelog/index.ts, src/index.ts, src/types/api.ts
-   [x] update changelog format
=> fix(changelog): update changelog format

src/commands/changelog/index.ts, src/listeners/discord/interactionCreate.ts
-   [x] handle dismiss button after click
=> fix(changelog): handle dismiss button after click

src/commands/changelog/index.ts
-   [x] get changelog real time
=> fix(changelog): get changelog real time

src/commands/balances/index/processor.ts
-   [x] check empty transaction
=> hotfix(bal): check empty transaction

src/commands/balances/index/processor.ts
-   [x]  check empty transaction
=> fix(bal): check empty transaction

src/commands/balances/index/processor.ts
=> fix(bal): handle case empty tx

src/commands/airdrop/index/handler.ts
=> fix(airdrop): update transaction id

src/commands/profile/index/processor.ts, src/commands/wallet/view/address/slash.ts, src/commands/wallet/view/profile/slash.ts, src/types/api.ts
-   [x] update ron address format
=> fix(general): update ron address format

src/commands/pay/me/processor.ts
-   [x]  show prettier payme error
=> fix: show prettier payme error

src/commands/airdrop/index/handler.ts
=> fix: handle parallel airdrops

src/adapters/config.ts, src/commands/sync/index.ts, src/errors/missing-access.ts, src/index.ts, src/listeners/discord/interactionCreate.ts, src/types/api.ts, src/utils/commands.ts
-   [x] add permission checking
=> feat: add permission checking

src/commands/config/index.ts, src/commands/config/verify/index.ts
=> fix: temp disable config verify captcha

src/commands/tip/index/processor.ts
- Tip: fix validation for "same" amount
=> fix: tip - validate 'same' amount

src/commands/tip/index/processor.ts
-  fix render msg when follow tip
=> fix(follow_tip): fix msg follow tip

src/commands/ticker/index/processor.ts
- /ticker: handle insufficient market data
=> fix: ticker - handle insufficient market data

src/commands/airdrop/index/handler.ts, src/commands/airdrop/index/processor.ts, src/commands/tip/index/processor.ts, src/commands/tip/mail/processor.ts, src/types/transfer.ts
- Tip + Airdrop: update `/transfer-v2` - add `token_id` into request payload
=> fix: transfer-v2 with token_id

src/commands/ticker/index/processor.ts
- /ticker: add address info
**Image**
=> feat: ticker - add address

src/commands/ticker/index/processor.ts
-   [x] update ticker not support response
=> fix(ticker): update ticker not support response

src/commands/watchlist/add/processor.ts
-   [x] show token chain and address in suggestion
=> fix(watchlist): show token chain and address in suggestion

src/commands/ticker/index/processor.ts
=> fix: ticker - market data format

package.json, pnpm-lock.yaml
=> fix: update mochi.js

src/commands/inbox/index/processor.ts
=> fix(inbox): fix format data inbox for txs

src/commands/inbox/index/processor.ts
=> fix(inbox)/fix-render-emoji-10-records-data-inbox

src/commands/inbox/index/processor.ts
=> fix(inbox): fix render max length data of embeded msg discord

src/commands/inbox/index/processor.ts
=> fix(inbox): fix msg withdraw inbox data

src/adapters/defi.ts, src/commands/ticker/index/processor.ts
=> fix: ticker - support dex-screener pair

src/commands/ticker/index/processor.ts, src/ui/discord/embed.ts
=> fix: ticker - update age calculation

src/commands/ticker/index/processor.ts
=> fix: ticker fdv

src/commands/ticker/index/processor.ts
=> fix: ticker UI

src/commands/ticker/index/processor.ts
=> fix: ticker - age emoji

src/commands/ticker/index/processor.ts, src/utils/convert.ts
-   [x] Ticker: format `Max supply`
=> fix: ticker - format supply

src/commands/ticker/index/processor.ts, src/ui/discord/embed.ts
=> fix: ticker - update format

src/commands/vault/transfer/slash.ts
-   [x]  vault transfer support chain base
=> fix: vault transfer support chain base

src/commands/ticker/index/processor.ts
-   [x] ticker update address format
=> fix: ticker update address format

src/commands/ticker/index/processor.ts
-   [x] Ticker: use Dexscreener FDV
=> fix: ticker - use dexscreener FDV

src/commands/ticker/index/processor.ts
=> fix: update ticker layout

src/utils/slash-command.ts
-   [x]  register global command
=> fix: register global command

src/commands/ticker/index/processor.ts
=> fix(ticker): fdv type error

src/commands/token/add/slash.ts
-   [x]  support add base token
=> fix: support add base token

src/commands/profile/index/processor.ts
-   [x] render top 3 roles of users in profile cmd
=> fix(profile): render top 3 roles of user in profile cmd

src/commands/profile/index/processor.ts
=> fix(profile): render profile in dm cmd

src/commands/ticker/index/chart.ts, src/commands/ticker/index/processor.ts, src/ui/canvas/chart.ts
=> feat: ticker - add liquidity and contract renounced

src/commands/balances/index.ts, src/commands/balances/index/slash.ts
=> feat: balance - all option

src/commands/balances/index/processor.ts, src/commands/ticker/index/processor.ts
=> fix: ticker and bals (all)

src/commands/balances/index/processor.ts, src/commands/ticker/index/processor.ts
-   [x] Ticker: Update renounced, filter out trading plat without URL
=> fix: ticker and wlv

src/adapters/defi.ts, src/commands/balances/index.ts, src/commands/balances/index/processor.ts, src/commands/balances/index/slash.ts
=> fix(binancespottxns): add binance spot txns

package.json, pnpm-lock.yaml
-   [x] Upgrade mochi-formatter to v20.0.9
=> fix: upgrade mochi-formatter

src/commands/balances/index/processor.ts, src/types/api.ts
=> fix(binancespottxns): add binance earn usdt to spot

src/adapters/mochi-api.ts, src/commands/balances/index/processor.ts
=> feat: add binance avg cost

src/commands/balances/index/processor.ts
=> fix(balance): change format view binance spot bal with avg cost

src/commands/vault/info/processor.ts
=> fix: vault detail render

package.json, pnpm-lock.yaml
=> fix: add momentjs

src/commands/watchlist/view/processor.ts
-   [x] update usd format for watch list view
=> fix: update usd format for watch list view

src/commands/balances/index/processor.ts, src/commands/wallet/view/address/slash.ts
-   [x] show balance of native token on different chains
=> fix: show balance of native token on different chains

src/errors/base.ts
=> fix: wla exist error msg

src/commands/vault/info/processor.ts, src/commands/vault/list/processor.ts
-   [x] /vault list (and detail selection): Update data
=> fix: update vault list data

src/commands/vault/info/processor.ts, src/commands/vault/list/processor.ts
=> fix: vault detail format

src/commands/ticker/index/processor.ts
-   [x] update logic when data undefined
=> fix(ticker): update logic when data undefined

src/commands/balances/index/processor.ts
=> fix(balance): support deposit and wd tx in bal type cex

src/commands/vault/info/processor.ts, src/commands/vault/list/processor.ts
- Trading vault detail: adapt API changes
=> fix: trading vault detail - adapt data changes

src/commands/ticker/index/processor.ts
=> fix: ticker compare

src/commands/balances/index/processor.ts
=> fix(balance): change format render binance spot tx

src/commands/balances/index/processor.ts
=> fix(balance): fix render spot tx for bal type cex

src/commands/balances/index/processor.ts
=> fix(balances): render format spot tx type cex

src/commands/balances/index/processor.ts, src/commands/vault/info/processor.ts
=> fix(vault): fix render vault info

src/adapters/mochi-api.ts, src/commands/balances/index/processor.ts
-   [x] onchain asset avg cost
=> feat: onchain asset avg cost

src/adapters/mochi-pay.ts, src/commands/vault/info/processor.ts, src/commands/vault/info/slash.ts, src/commands/vault/list/processor.ts, src/commands/vault/list/slash.ts, src/commands/vault/view/slash.ts
=> feat: vault commands flow

src/commands/vault/info/processor.ts, src/commands/vault/info/slash.ts
-   [x] Vault report: fix `Back` btn interaction
=> fix: vault report - back btn interaction

src/commands/profile/index/slash.ts, src/commands/vault/info/processor.ts
-   [x] update select vault for profile
=> fix: update select vault for profile

src/adapters/mochi-pay.ts, src/commands/vault/view/processor.ts, src/commands/vault/view/slash.ts, src/utils/profile.ts
-   [x] /vault config view: real data for trading vaults
=> feat: trading vault config view

src/commands/balances/index/processor.ts, src/utils/constants.ts
=> fix(balances): render recent tx for onchain bals

src/commands/balances/index/processor.ts
=> fix(balance): filter spam tx when render onchain bal

src/commands/balances/index/processor.ts
-   [x] parse average cost onchain asset
=> fix: parse average cost onchain asset

package.json, pnpm-lock.yaml, src/commands/balances/index/processor.ts
=> fix(balances): fix format number in onchain tx

src/commands/vault/info/processor.ts, src/commands/vault/info/slash.ts
- Trading vault: render full closed trades
=> fix: trading vault - render full closed trades

src/commands/balances/index/processor.ts, src/commands/balances/index/slash.ts
=> fix: remove invest section

src/ui/discord/embed.ts
- Remove `Mochi is confused` reply to unknown commands
=> fix: ignore unknown cmds

src/commands/vault/info/slash.ts
-   [x] display wallet detail when deposit token to vault
=> fix: display wallet detail when deposit token to vault

src/adapters/mochi-pay.ts, src/commands/vault/info/processor.ts, src/commands/vault/list/processor.ts
=> feat: list global vaults

src/adapters/icy.ts, src/commands/tip/index/processor.ts, src/env.ts, src/types/api.ts, src/utils/constants.ts
-   [x] add satoshi convert for tip
=> fix: add satoshi convert for tip

package.json, pnpm-lock.yaml
=> fix: install rpc websocket

scripts/generate-types.js, src/adapters/icy.ts, src/commands/tip/index/processor.ts, src/types/api.ts, src/types/icy.ts
=> fix: update tag

package.json, pnpm-lock.yaml
=> fix: update package

Dockerfile
=> fix: update Dockerfile - manually build canvas

src/adapters/mochi-pay.ts, src/commands/airdrop/index.ts, src/commands/airdrop/index/handler.ts, src/commands/airdrop/index/processor.ts, src/types/transfer.ts, src/utils/tip-bot.ts
- Update command /airdrop: can select application vault as source
```
/airdrop amount:0.1 token:icy duration:10s from_vault:test1
```
- Confirm
- Airdrop ended (author DM)
=> feat: airdrop from vault

src/adapters/mochi-pay.ts, src/commands/airdrop/index.ts, src/commands/vault/list/processor.ts
=> feat: vault list - support app vaults

docs/KUDOS_FEATURE.md, docs/Overview.md, docs/adr/0002-kudos-discord-command-architecture.md, docs/changelog/0001-app-transfer-timeout-and-race-condition-fixes.md, src/adapters/mochi-pay.ts, src/commands/index.ts, src/commands/kudos/index.ts, src/commands/kudos/slash.ts
=> feat: kudos cmd

src/adapters/mochi-pay.ts, src/commands/kudos/slash.ts, src/commands/transfer_request/index/processor.ts, src/types/api.ts
=> fix: update kudos cmd
